### ISSUE TITLE
Blur Effect Issues

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/libopenshot#144]
1. Not really an issue but something for others to test out... it seems the blur effect is a tad more computationally expensive than others for some reason. I haven't looked into the code but did notice significant more time consumption when the effect was applied.
2. The application of blur seems to be stepped. Even in the preview and in the render, instead of gradually increasing, the blur effect seems to increase at certain intervals, visibly. The following video should make it clear.
[Blur test png.mp4.tar.gz](https://github.com/OpenShot/libopenshot/files/2187412/Blur.test.png.mp4.tar.gz)

Sorry this report isn't quite elaborate. I've been meaning to submit it here for quite a long time but couldn't find the time to do so. So this is a bare minimum version of it that I hope some of the devs/testers/debuggers/contributors will be able to understand and hopefully fix. :)

**Comment by ferdnyc** [comment]
> 1. Not really an issue but something for others to test out... it seems the blur effect is a tad more computationally expensive than others for some reason. I haven't looked into the code but did notice significant more time consumption when the effect was applied.

Oh, Blur is unquestionably slow AF. Which is **somewhat** understandable, as it simply _is_ a computationally heavy process — even a "fast" Gaussian blur requires an awful lot of calculus. Whereas brightness/contrast, pixelation, etc. are just simple calculations on chunks of the frame image, nothing more involved than addition or multiplication. Still, even in the context of how slow it can be expected to be, Blur is _slow_.

It's still slow, and will probably always be slow, but since #423 it's a lot _less_ slow. I added some parallelization and streamlining that got it to run, at least on my 4-core Intel i5 system, literally 10× as fast as the old Blur.

(Which is still slow, because we're talking about a speedup from barely 1 frame per second on export, to a whopping 12-ish frames per second. That's still a fraction of the speed OpenShot exports video with no effects on my system, and on audio-only projects it's been known to break 100 fps.)

> 2. The application of blur seems to be stepped. Even in the preview and in the render, instead of gradually increasing, the blur effect seems to increase at certain intervals, visibly. The following video should make it clear.

That _may_ be due to the lack of Sigma processing.

When I was rooting around in Blur, I noticed that although the `initBoxes()` function (which applies the `Sigma` parameter) was being called, the results it returned were never used anywhere in the rest of the code. So I ripped it out entirely, which is one of the ways I was able to get such a huge improvement in speed.

But it's possible that correctly applying `initBoxes()` / `Sigma` would've helped to smooth out Blur's intensity. Right now, it's only adjustable by either the blur radius in intervals of whole pixels (which is a pretty coarse adjustment), or in terms of the number of intervals which is _exponential_.

Then again, restoring `Sigma` would make Blur slower again, and I'm not sure it can afford it.

For now, closing as fixed to some extent in #423.
