### ISSUE TITLE
Fastest settings to encode video ?

### ISSUE THREAD

**Issue by Le-G** [OpenShot/libopenshot#146]
This isn't really an issue but the website redirects here to ask questions so here I am...

I'm starting to play around with the lib and I've started with a really basic example that consists in taking a few seconds from two short videos to make a third one.

It appeared to me that the rendering time was quite long and exceeded the length of the generated video.

What would be ideal input/output formats and settings to minimize the rendering time ?
Knowing that i'm dealing with 1080p videos, and that quality has to be decent but doesn't have to be perfect.
I'm currently using h264 as both input and ouput.

Cheers !

**Comment by jeffski** [comment]
I'd allow 1-2 seconds rendering time per second of video depending on if you are applying effects etc... I'd recommend h264 for the output just for the quality. Also the more processor threads you have the better. One way to speed things up might be to reduce the number of frames per second - for example if your output is 30fps can you get away with 24fps? Also is 1080p essential, could you use 720p?

**Comment by Le-G** [comment]
I'm not currently using any effects, I'm just doing a concat on 2 videos and it's already quite long to render... I'm already rendering in h264 and my dev rig is a decent i7 so I allow openshot to use 8 threads which I guess should be enough. I've already narrowed the fps down to 24 and I'd ideally would like to keep rendering 1080p vids.

I noticed in the logs that x264 always runs with the "high" profile even though I tried passing different values to the "profile" setting using SetOption(). Has someone succeeded changing x264 profile using openshot ?

**Comment by peanutbutterandcrackers** [comment]
Currently, the sanest export quality seems to be 'medium', that gives pretty decent output in a pretty decent time.

However, currently works are in progress to 1. add hardware acceleration support for openshot and 2. to fix the bitrate-related export issues. So, it might be a while before this issue is fixed.

Also, it seems, if you are just trying to concat 2 videos, something like [avidemux](http://fixounet.free.fr/avidemux/) is a better suited tool for you?

Perhaps this issue can be closed now, for the time being, so as to control the clutter of issues? Thanks!
