### ISSUE TITLE
Low audio and video quatily

### ISSUE THREAD

**Issue by v1993** [OpenShot/libopenshot#154]
I try to create simple video reverser (there is no such thing in whole internet!).

However, resut video sometimes skip frames and audio also have poor quatily. This is main part of my code (leaving some things aside):

		std::unique_ptr<FFmpegReader> reader;
		{
			auto fail = []() {
				std::cerr << "Failed to open input file" << std::endl;
				exit(1);
			};
			try {
				reader = std::make_unique<FFmpegReader>(o.ifile);
				if (!reader) {
					fail();
				}
				reader->Open();
			} catch(const std::exception&) {
				fail();
			}
		}
		std::cerr << "Open reader: success" << std::endl;

		auto& i = reader->info;
		int64_t len = i.video_length;

		auto writer = std::make_unique<FFmpegWriter>(o.ofile);
		std::cerr << "Open writer: success" << std::endl;
		writer->SetVideoOptions(
			i.has_video,
			o.vcodec, // Use proper codec
			i.fps,
			i.width,
			i.height,
			i.pixel_ratio,
			i.interlaced_frame,
			i.top_field_first,
			i.video_bit_rate);

		writer->SetAudioOptions(
			i.has_audio,
			o.acodec, // Use proper codec
			i.sample_rate,
			i.channels,
			i.channel_layout,
			i.audio_bit_rate);

		std::cerr << "Writing…" << std::endl;
		writer->Open();
		for (int64_t i = 1; i <= len; ++i) {
			showProgress((float) i / (float) len);
			writer->WriteFrame(reader->GetFrame(len - i + 1));
		}
		writer->WriteTrailer();
		writer->Close();
		reader->Close();
However, result video inlude some frame dropping and major audio problems. How can I fix this problems?

**Comment by peanutbutterandcrackers** [comment]
@N3WWN @jeffski - Calling you for help here, gentlemen!

**Comment by jeffski** [comment]
I tried to test your code but I'm using C++11 and I think `std::make_unique` is only available in C++14 so I couldn't try it.

However, have a look at this unrelated issue: https://github.com/OpenShot/libopenshot/issues/122 - my sample code looks like it does more or less the same thing as yours - open an input video, loop through the frames and write them to an output video.

That's just the way I did it, I'm far from a C++ expert, but I do not get any issues with quality, dropped frames or audio problems. I also managed to reverse the output video with the following:

```
for (long int frame = 25; frame >=0; frame--)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = inputReader.GetFrame(frame_number);
	outputWriter.WriteFrame(f);
}
```

Hopefully that will give you a few pointers, what you want to do should be possible without any problems.

**Comment by ferdnyc** [comment]
The tricky thing about reversing digital video is that any codec that keeps the file sizes down to manageable levels encodes the stream into blocks of full-image I-frames, followed by a list of P- and B-frame updates that are _not_ complete images. If a video is encoded with an I-frame every 10 frames, say, then the **only** way to get the image for frame 8 (numbering from 0) is to read frame 0, then apply the deltas for frames 1, 2, 3 , 4, 5, 6, and 7, before finally applying the frame 8 deltas and constructing the full frame image for frame 8. Then to construct frame 7, it's back to 0, then apply 1, 2, 3, 4, 5, 6, and 7. Lather, rinse, repeat.

So, the results of "reversing" any given video will depend greatly on the video format/codec, the number and frequency of I-frames as opposed to P- or B-frames, and the method the code uses to progress through the video.

If you're lucky and your video is largely uncompressed and mostly made of I-frames, it's not too bad. If your video is encoded in the manner of most highly-efficient codecs today and is _very_ conservative with the I-frames, using P- and B-frames for as long as possible until a scene change or significant on-screen movement makes it just  as expensive to use interframe updates as to store an entire frame, so it  just creates a new I-frame instead.

If you're _clever_ and can afford the disk/memory, the best way to reencode a video in reverse is with a two-stage chain — you run the video through a decoder that blows every frame out into a full image, and then feed that (incredibly large and memory-hungry) sequence into an encoder that will do the work of encoding it back down to some reasonable size and video bitrate. But it might require an insanely fast CPU, more memory than you know what to do with, and a fairly low-bandwidth video all the same.

Barring that, if you can scrounge up enough buffer space to store just one single GOP ("group of pictures", an I-frame followed by the set of P- and B-frames that update it) completely decoded, then you can make the work of reversing the video a lot easier by walking through it a GOP at a time, rather than a frame at a time. (But that also requires your video to have relatively predictable I-frame locations and GOP sizes, which codecs like h264/h265 don't promise at all.)

Like, take our theoretical I-frame-every-10th-frame video. Say it's 2 seconds long at 30fps. It'll have I-frames at frame 0, 9, 19, 29, 39, and 49, and then might have one more at the very last frame (59) but let's ignore that.

If you want to reverse that video, you _could_ request frames 58, 57, 56, 55, 54, 53, 52, 51, 50, and 49 in order, but you'll force the decoder to do a near-exponential number of frame reads. To get frame:
* 58: Seek to I-frame 49, apply deltas for 50, 51, 52, 53, 54, 55, 56, 57, 58
    ...next...
* 57: Seek back to I-frame 49 again, apply deltas for 50, 51, 52, 53, 54, 55, 56, 57
* 56: Seek back to I-frame 49 again, apply deltas for 50, 51, 52, 53, 54, 55, 56
* 55: Seek back to I-frame 49 again, apply deltas for 50, 51, 52, 53, 54, 55
...and so on.

Whereas, if you can manage it, it's much more efficient if you seek to frame 49 and read forward from 49-58, retrieving each full frame image (essentially uncompressing the video, for that one GOP) and storing all of the frames in memory. Then, you can reverse them, feed them to the encoder, and seek to frame 39 (the previous I-frame) to start reversing the preceding GOP. 

If `n` is the number of delta frames between each I-frame (9, in our example), then the number of frames the decoder's had to process to read the entire GOP in to memory for reversal gets reduced from `n(n+1)/2` (the formula for computing `1+2+3+4+...+n`), to just plain `n+1`.
