### ISSUE TITLE
This is no real issue, but imagemagick 6** is too old

### ISSUE THREAD

**Issue by cyberhoffman** [OpenShot/libopenshot#162]
There is an issue in upgrading media-gfx/imagemagick from ver. 6.9.10.11 to ver. 7.0.8.11 last time. I've found out that this is because of hardcoded dependency in libopenshot ebuild:
```
RDEPEND="
...
29     imagemagick? ( <media-gfx/imagemagick-7:0=[cxx] )
...
33 "
```
To be honest, it is not very big problem, but those annoying strokes during updating system...

**Comment by ferdnyc** [comment]
I can barely read that (it's a very... "efficient" use of characters, huh?), but am I to interpret it as an assertion that the ImageMagick version number must be less than 7?

As far as I can _tell_ libopenshot should be compatible with ImageMagick 7, though I don't know whether anyone's actually tried yet. There are no versioned dependencies that I can find anywhere in the cmake build definitions, and the ImageMagick team [say the Magic++ API is unchanged](http://www.imagemagick.org/script/porting.php) from IM6 to IM7.

Where is that hardcoded dependency coming from? (Meaning, where does the ebuild definition come from?) It isn't anything generated by the project AFAIK, so it's possible this is a packager/distro issue.

**Comment by cyberhoffman** [comment]
I cant get rid of imagemagic-6 because it is needed to libopenshot. And there is no solution to install imagemagic-7 except adding virtual slots or uninstalling the whole openshot. (Yes, you may say me that there is still possible to make own local overlay instead of using official gentoo repo but I dont want to mess them). 
> Where is that hardcoded dependency coming from?
It is kept in media-libs/libopenshot ebuild.

**Comment by ferdnyc** [comment]
> I cant get rid of imagemagic-6 because it is needed to libopenshot. 

Understood, and... that's true, currently, because your libopenshot is apparently compiled against ImageMagick 6. The thing that's preventing you from recompiling it against IM7 is the dependency definition that's restricted to IM versions < 7.0. (IIRC ebuilds are compiled locally from source, as opposed to binary package distributions, correct? — I know almost _nothing_ about Gentoo, honestly, so please correct me on anything I have wrong here.) 

Anyway, that version restriction...

> It is kept in media-libs/libopenshot ebuild.

Which wasn't written by the libopenshot team. That's why the ebuild file presumably says "Copyright... Gentoo Foundation" at the top. (At least, every one I can find in a quick web search says that.) 

I'm not clear on what you're asking the libopenshot team to do, since that file isn't part of libopenshot. It's part of Gentoo.

(In fact, even though the 0.2.0 ebuilds say © Gentoo Foundation, it seems the [official Gentoo ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libopenshot) tree for libopenshot only goes up to 0.1.8 and is marked "maintainer needed", so I'm guesing the 0.2.0 ebuilds come from community-contributed... "overlays", I guess is the term?)

I guess there are two questions here:
1. Does compiling libopenshot with ImageMagick 7.0 _work_? (Presumably there's some way to override or edit the ebuild definition, so you can at least try to build it with 7.0?)
1. If it does, is there some way to reach the author/maintainer of the libopenshot ebuild, to let them know that the version restriction is unnecessary/invalid? 

Or, of course, there's always the option to run OpenShot from [the official AppImage](https://www.openshot.org/download/) self-contained package, at which point you could uninstall the system libopenshot and it would no longer block IM7.

**Comment by cyberhoffman** [comment]
First of all sorry for bother you. I'd mistakely considered this page as a gentoo libopenshot maintaining place. Anyway thank you for your attempt to help me. But I have already given up and will wait for that moment when gentoo maintainer resolves the problem. And if you are interesting for the steps I've made:
I created local overlay and put in it libopenshot-0.1.8.ebuild from the official gentoo repo.
Generated manifest and removed a mention about  version of imagemagick from ebuild at all:

`imagemagick? ( <media-gfx/imagemagick:0=[cxx] )`

 After that imagemagick version 7 was pulled and installed successfully but libopenshot failed. 
I tried to install libopenshot version 0.2.0 but it failed too.

Here is my build log:
[ ](url)https://paste.pound-python.org/show/3mFWhQebpMzZuWWnqM1f/

**Comment by ferdnyc** [comment]
Heh, completely understood, sorry I couldn't be more help.

> After that imagemagick version 7 was pulled and installed successfully but libopenshot failed.
> I tried to install libopenshot version 0.2.0 but it failed too.
> 
> Here is my build log:
> [ ](url)https://paste.pound-python.org/show/3mFWhQebpMzZuWWnqM1f/

Thanks, that's actually helpful (if hard to read, looks like it was color-terminal output? so many escape characters!), since it looks like the core of the problem is here:

```
linux-gnu-g++ -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DOPENSHOT_IMAGEMAGICK_COMPATIBILITY=0 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DUSE_IMAGEMAGICK=1 -Dopenshot_EXPORTS -I/usr/include/ImageMagick-7 -I/usr/include/libopenshot-audio -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtMultimediaWidgets -I/var/tmp/portage/media-libs/libopenshot-0.2.0/work/libopenshot-0.2.0/src/../thirdparty/jsoncpp/include   -DNDEBUG -std=c++11           -g -ggdb  -fopenmp  -fPIC   -fPIC -std=gnu++11 -o CMakeFiles/openshot.dir/KeyFrame.cpp.o -c /var/tmp/portage/media-libs/libopenshot-0.2.0/work/libopenshot-0.2.0/src/KeyFrame.cpp
[01m[K/var/tmp/portage/media-libs/libopenshot-0.2.0/work/libopenshot-0.2.0/src/Frame.cpp:[m[K В функции-члене «[01m[Kstd::shared_ptr<Magick::Image> openshot::Frame::GetMagickImage()[m[K»:
[01m[K/var/tmp/portage/media-libs/libopenshot-0.2.0/work/libopenshot-0.2.0/src/Frame.cpp:905:16:[m[K [01;31m[Kошибка: [m[K«[01m[Kusing element_type = class Magick::Image {aka class Magick::Image}[m[K» has no member named «[01m[Kmatte[m[K»
  magick_image->[01;31m[Kmatte[m[K(true);
                [01;31m[K^~~~~[m[K
```

Or, cleaned up,
```
/var/tmp/portage/media-libs/libopenshot-0.2.0/work/libopenshot-0.2.0/src/Frame.cpp: 
В функции-члене «std::shared_ptr<Magick::Image> openshot::Frame::GetMagickImage()»:
/var/tmp/portage/media-libs/libopenshot-0.2.0/work/libopenshot-0.2.0/src/Frame.cpp:905:16: 
ошибка: «using element_type = class Magick::Image {aka class Magick::Image}» has no 
member named «matte»
  magick_image->matte(true);
                ^~~~~
```

Which is unexpected, since `matte()` is still [documented](http://www.imagemagick.org/Magick++/Image++.html#Image%20Attributes) as an attribute of the Magick::Image class, so that _should_ still work. Obviously, it would be preferable if libopenshot compiles with IM7, so it's worth tracking down this issue to determine whether it affects all builds or if it's a problem specific to Gentoo.  As a result, I'm building IM7 now for my local machine (running Fedora 28, as they currently have no plans to package IM7 officially even for the _next_ release of Fedora 29), and once I have that working I'll try building libopenshot with so I can see if I hit the same issue.

**Comment by ferdnyc** [comment]
It looks like you may have hit ImageMagick/ImageMagick#236 where it's reported that `matte()` was renamed to `alpha()`, which kind of puts the lie to the website documentation's [claim](http://www.imagemagick.org/script/porting.php) that "The Magick++ and PerlMagick API's have not changed and matches that of the ImageMagick version 6." and invalidates those website docs I previously linked to that still show `matte()` as being a valid attribute of `Magick::Image`.

(Though that's kind of a relief, as so far my own attempts at building ImageMagick 7 have all been failing the unit tests.)

I'll take it up with the IM team at that bug report, and see if I can't at least get them to fix their docs to include some sort of notice regarding the name-change from `matte()` to `alpha()`.

Regarding libopenshot itself, just changing the code to use `alpha()` would mean it no longer compiles with IM6, so any fix will have to be conditionalized to the IM version in use. Bother.
