### ISSUE TITLE
Python Install Path Logic is Invalid

### ISSUE THREAD

**Issue by jonoomph** [OpenShot/libopenshot#218]
With previous versions of libopenshot, the install path for our Python bindings were determined with the following code:

```
EXECUTE_PROCESS ( COMMAND ${PYTHON_EXECUTABLE} -c "import site; print(site.getsitepackages()[0])"
OUTPUT_VARIABLE _ABS_PYTHON_MODULE_PATH
OUTPUT_STRIP_TRAILING_WHITESPACE )

Output on my system: /usr/local/lib/python3.5/dist-packages
```
And now we use the following code:

```
execute_process ( COMMAND ${PYTHON_EXECUTABLE} -c "\
from distutils.sysconfig import get_python_lib; \
print( get_python_lib( plat_specific=True, prefix='${CMAKE_INSTALL_PREFIX}' ) )"
OUTPUT_VARIABLE _ABS_PYTHON_MODULE_PATH
OUTPUT_STRIP_TRAILING_WHITESPACE )

Output on my system: lib/python3/dist-packages
```

While the newer version supports custom prefixes, it does not seem to find the correct place on Ubuntu and Linux Mint (and probably other distros as well). Not sure what the best solution is, but I wanted to document this in a bug report, and get some additional eyeballs on it.

**Comment by jonoomph** [comment]
@ferdnyc I would love to hear your thoughts on this. :smile:

**Comment by ferdnyc** [comment]
I'll be able to give more meaningful input in a couple of hours when I'm back home, responding on my phone right now while I'm in the waiting room for an appointment in a few minutes.

Offhand, the GNUInstallDirs suggestion another user made for libopenshot-audio might help here, too, if we applied it. (Which we can, now that we're using CMake 3.)

But I also seem to remember CMake 3 having a slightly _different_ variable for explicitly accessing an **absolute** path, maybe something like `${CMAKE_INSTALL_PATH_FULL}` -- that might work to get the required behavior. I'll check the docs when I get home in an hour or so. (Just finished the appointment, actually.)

**Comment by ferdnyc** [comment]
I was also trying to remember what we do in Fedora, but as I suspected we just explicitly define everything to excess rather than querying for values. Like, you can see the build log for my most recent build here. I'd love to copy and paste the `cmake` command line but my phone locks up every time I try to select text on that page. The relevant point, though, is that it's like 400+ characters and explicitly passes in every path variable CMake recognizes. ☺️

http://koji.rpmfusion.org/kojifiles/packages/libopenshot/0.2.3/1.fc29/data/logs/x86_64/build.log

**Comment by ferdnyc** [comment]
So here's what I've discovered:

#### 1. It's GNUInstallDirs that has the "absolute form of path variables" feature
I'd misremembered this note from [that module's docs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) as being about CMake in general:
> Each `CMAKE_INSTALL_<dir>` value may be passed to the `DESTINATION` options of `install()` commands for the corresponding file type. If the includer does not define a value the above-shown default will be used and the value will appear in the cache for editing by the user. Each `CMAKE_INSTALL_FULL_<dir>` value contains an absolute path constructed from the corresponding destination by prepending (if necessary) the value of `CMAKE_INSTALL_PREFIX`.

(So, with GNUInstallPrefix you can use e.g. `CMAKE_INSTALL_FULL_LIBDIR` to get an absolute-path version of the library installation dir.)

#### 2. Python queries
That Python output appears to be consistent with an _empty_ `CMAKE_INSTALL_PREFIX`, which is weird because it should be pretty hard to get that set to empty.
On my Fedora 29 system:
```sh
$ python3  -c "from distutils.sysconfig import get_python_lib;\
print( get_python_lib( plat_specific=True, prefix='' ) )"

lib64/python3.7/site-packages
$ python3  -c "from distutils.sysconfig import get_python_lib;\
print( get_python_lib( plat_specific=True, prefix='/usr/local' ) )"

/usr/local/lib64/python3.7/site-packages
$ python3 -c "from distutils.sysconfig import get_python_lib;\
print( get_python_lib(plat_specific=True ) )"               

/usr/lib64/python3.7/site-packages
```
#### 3. CMake execution
I guess my main question becomes, how do you _know_ the output of the command? As of what's committed to the repo today, we never display it during the build file generation.

I modified `src/bindings/python/CMakeLists.txt` like so, to change that:
```cmake
        ### FIND THE PYTHON INTERPRETER (AND THE SITE PACKAGES FOLDER)
        execute_process ( COMMAND ${PYTHON_EXECUTABLE} -c "\
from distutils.sysconfig import get_python_lib; \
print( get_python_lib( plat_specific=True, prefix='${CMAKE_INSTALL_PREFIX}' ) )"
                          OUTPUT_VARIABLE _ABS_PYTHON_MODULE_PATH
                          OUTPUT_STRIP_TRAILING_WHITESPACE )
        message(STATUS "Detected Python library dir: ${_ABS_PYTHON_MODULE_PATH}")
        GET_FILENAME_COMPONENT(_ABS_PYTHON_MODULE_PATH
                               "${_ABS_PYTHON_MODULE_PATH}" ABSOLUTE)
        FILE(RELATIVE_PATH _REL_PYTHON_MODULE_PATH
             ${CMAKE_INSTALL_PREFIX} ${_ABS_PYTHON_MODULE_PATH})
        SET(PYTHON_MODULE_PATH ${_REL_PYTHON_MODULE_PATH})
        message(STATUS "Using Python module path: ${PYTHON_MODULE_PATH}")
```
And here's what I got when I ran `cmake ..` in a clean `build` directory:
```
-- Found SWIG: /usr/bin/swig (found suitable version "3.0.12", minimum required is "2.0") 
-- Found PythonLibs: /usr/lib64/libpython3.7m.so (found suitable version "3.7.2", minimum required is "3") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.2", minimum required is "3") 
-- Detected Python library dir: /usr/local/lib64/python3.7/site-packages
-- Using Python module path: lib64/python3.7/site-packages
```
Which is consistent with a `CMAKE_INSTALL_PREFIX` of `/usr/local`, the default (as I can see in `CMakeCache.txt` in the build dir).
If I override it by using `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..`, I get:
```
-- Found SWIG: /usr/bin/swig (found suitable version "3.0.12", minimum required is "2.0") 
-- Found PythonLibs: /usr/lib64/libpython3.7m.so (found suitable version "3.7.2", minimum required is "3") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.2", minimum required is "3") 
-- Detected Python library dir: /usr/lib64/python3.7/site-packages
-- Using Python module path: lib64/python3.7/site-packages
```
(The `PYTHON_MODULE_PATH` remains unchanged, because it's relative to the `CMAKE_INSTALL_PREFIX` — as it should be, since CMake's `install()` command takes relative `DESTINATION` arguments unless it's called with `ABSOLUTE DESTINATION`.)

**Comment by ferdnyc** [comment]
@jonoomph 
Ugh, sorry, ignore all that. Point is the difference between `lib/python3/` and `lib/python3.5/`, of course.

The current code came via [this stackoverflow question](https://stackoverflow.com/questions/14784134/make-install-with-cmake-swig-python), or actually a comment there which pointed me to [the libftdi example](http://developer.intra2net.com/git/?p=libftdi;a=blob;f=python/CMakeLists.txt;h=93410544fac2a45eec51cb8dd344708b3bbdfe67;hb=HEAD) it's cribbed from. It worked on my Fedora box, but if it causes problems elsewhere we'll need to find an alternative.

It's strange because `distutils` is the same module that provides the foundation for `setuptools`, which is what the `setup.py` for OpenShot itself uses... so I would expect that if it was the problem, we'd see issues there as well.

Anyway, I'm building a Ubuntu 18.10 VM installation now, I'll take a look once that comes up. At least once I've gotten my bearings I'll be able to ask more intelligent questions.

We certainly COULD go back to the previous `getsitepackages()` method, the main problem is blindly picking the first path on the list. Even when that's right, it's more coincidence than anything else.

One possibility, if it came down to it, would be [building CMake rules like this](https://bloerg.net/2012/11/10/cmake-and-distutils.html) that would actually use `setuptools` to build and install the Python bindings. Then they'd be installed via the same process OpenShot itself is. I suspect it's a little trickier with SWIG in the mix, but not impossible.

**Comment by ferdnyc** [comment]
So, here's what I've discovered so far:

On Ubuntu 18.10:
```console
$ python3 -c 'import sys; print(sys.path)'
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload',\
 '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']

$ python3 -c "import site; print(site.getsitepackages())"
['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages',\
 '/usr/lib/python3.6/dist-packages']
```

(That's what I was saying about the first list entry being correct only "by coincidence". And only if you're using `/usr/local`, which many distros don't at all.)

```console
$ python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib());"
/usr/lib/python3/dist-packages

$ python3 -c "...; print(get_python_lib(prefix='/usr'));"
/usr/lib/python3/dist-packages

$ python3 -c "...; print(get_python_lib(prefix='/usr/local'));"
/usr/local/lib/python3/dist-packages

$ python3 -c "...; print(get_python_lib(prefix=''));"
lib/python3/dist-packages

$ python3 -c "...; print(get_python_lib(prefix='/tmp/'));"
/tmp/lib/python3.6/site-packages

$ python3 -c "...; print(get_python_lib(prefix='/home/ferd/'));"
/home/ferd/lib/python3.6/site-packages
```

It's only for the `/usr/` and `/usr/local` prefixes where `distutils` uses the `python3/dist-packages` path, and apparently those are locations where it's _not_ actually an incorrect path. `/usr/lib/python3/dist-packages` and `/usr/local/lib/python3/dist-packages` are apparently the _intended_ module destinations on Debian-based systems, by design:

```console
$ pydoc3 site
Help on module site:

NAME
    site - Append module search paths for third-party packages to sys.path.

MODULE REFERENCE
    https://docs.python.org/3.6/library/site

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    ****************************************************************
    * This module is automatically imported during initialization. *
    ****************************************************************

    This will append site-specific paths to the module search path.  On
    Unix (including Mac OSX), it starts with sys.prefix and
    sys.exec_prefix (if different) and appends
    lib/python3/dist-packages.
```

In fact, neither `/usr/lib/python3.6/dist-packages/` nor `/usr/lib/python3.6/site-packages/` exist on my freshly-installed 18.10 VM, but `/usr/lib/python3/dist-packages/` contains 71 directories (excluding `egg-info` dirs), and things like PyQt5, apt, systemd, and setuptools itself all install their modules there.

* `python3 setup.py install --install-layout=deb` inside a cloned copy of the OpenShot/openshot-qt repo will cause it to use `/usr/lib/python3/dist-packages` as its install destination.
* `python3 setup.py install --install-layout=deb --prefix=/usr/local` will cause it to use `/usr/local/lib/python3/dist-packages/`. 

The `--install-layout` flag is documented in the [Python Support Policy](https://debian-python.readthedocs.io/en/latest/debian-policy.html) for Debian-and-derivatives' distutils.

The `/usr/local/lib/python3/dist-packages`-vs-`/usr/local/lib/python3.6/dist-packages` thing seems to have grown out of that policy, which dates back to 2015 and was confusing even then. There seems to be some theory that the "system python" shouldn't pick up `/usr/local/` modules, so you'd install a "local python" if you wanted to use anything in `/usr/local/`. But you shouldn't install local packages to `/usr/lib/python3`, that's bad. (But I gather that for building PPA packages, `/usr/lib/python3` would be an acceptable install destination. For any other purpose, _not_ using `/usr/local/` would work around Debian's nonsense.)

...I don't understand what they're trying to accomplish with this policy and I'm not convinced they're even following it correctly themselves. (If the "system python3" isn't going to look in `/usr/local/lib/python3` then "system python" modules like `distutils` and `site` shouldn't be referencing it!) None of the other distros or platforms maintains any such policy.

We're not the first ones to get screwed by this.
* https://github.com/pothosware/SoapySDR/issues/129
* https://gitlab.gnome.org/GNOME/meld/issues/225
* https://trac.osgeo.org/gdal/ticket/6671

**Comment by jonoomph** [comment]
@ferdnyc Thanks for the super detailed research! So, now that we all agree that Debian has some crazy Python policies, what do you suggest we do in `src/bindings/python/CMakeLists.txt`? Return to our previous logic? Sorry if I missed the conclusion from above, haha.

**Comment by ferdnyc** [comment]
@jonoomph 
Yeah, there really wasn't one. I have no good answers.

I'd say, if we're going to have to return to the old logic, we should do that _conditionally_, and only when we're on a Debian platform. For other distros, the current logic is more correct, and will work fine as-is.

Now, the question becomes, what's the best way to detect a Debian-derived Linux distro from within CMake?

We might be able to use [`pybuild`](https://wiki.debian.org/Python/Pybuild). It appears to be a pretty standard part of Debian's Python distribution, but it _**only**_ exists on Debian's python distribution, because it was created as a tool to implement their wacky policy.

Could you check whether the `pybuild` command exists on all of your oldest and most esoteric Debian-based builders? The wiki page says it's "new" as of 2013, which hopefully might cover all of our needs?

**Comment by jonoomph** [comment]
I'm going to close this issues since I think we have a solution now: https://github.com/OpenShot/libopenshot/pull/222/
