### ISSUE TITLE
openshot-test complains [AudioData @ 0x7f800b7f78a0] invalid NULL pointer for src[0]

### ISSUE THREAD

**Issue by RussNelson** [OpenShot/libopenshot#24]
This error printed by openshot-test is in FFmpegWriter_Tests.cpp, where it calls Frame::GetAudioChannelsCount. That function is in Frame.cpp, and is a wrapper around audio->getNumChannels . `audio` is juce::AudioSampleBuffer, which is defined by libshotaudio's juce_AudioSampleBuffer.h . The function getNumChannels simply returns an integer. Not sure where the error message is coming from, unless `audio` is NULL and being caught by an exception handler.

**Comment by ghisvail** [comment]
Same here.

**Comment by komackaj** [comment]
I've enabled logging for [aforementioned line in tests](https://github.com/OpenShot/libopenshot/blob/46c25dc3ec5eb663f6d05dabf100c51841372eff/tests/FFmpegWriter_Tests.cpp#L64) and tracked this error down to avresample_convert call in FFmpegReader::ProcessAudioPacket.
It seems to me that there is a unhandled case in processing an audio packet that doesn't produces whole audio frame (first frame in this case).

The issue arises when [avcodec_decode_audio4](https://github.com/OpenShot/libopenshot/blob/46c25dc3ec5eb663f6d05dabf100c51841372eff/src/FFmpegReader.cpp#L936) returns 0 for frame_finished - audio frame looks like this

```
(gdb) p *audio_frame
$13 = {data = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, linesize = {0, 0, 0, 0, 0, 0, 0, 0},
```

and consequent [avresample_convert call](https://github.com/OpenShot/libopenshot/blob/46c25dc3ec5eb663f6d05dabf100c51841372eff/src/FFmpegReader.cpp#L1040) prints this error, because input frame data is NULL.

Log for relevant call:

```
FFmpegReader::GetFrame (requested_frame=1.0000, last_frame=0.0000)
FFmpegReader::ReadStream (requested_frame=1.0000, OPEN_MP_NUM_PROCESSORS=8.0000)
FFmpegReader::ReadStream (GetNextPacket) (requested_frame=1.0000, processing_video_frames.size()=0.0000, processing_audio_frames.size()=0.0000, minimum_packets=8.0000, packets_processed=0.0000)
FFmpegReader::CheckMissingFrame (requested_frame=1.0000, has_missing_frames=0.0000, missing_video_frames.size()=0.0000, checked_count=1.0000)
FFmpegReader::ReadStream (GetNextPacket) (requested_frame=1.0000, processing_video_frames.size()=0.0000, processing_audio_frames.size()=0.0000, minimum_packets=8.0000, packets_processed=1.0000)
FFmpegReader::GetAudioPTSLocation (Audio Gap Ignored - too big) (Previous location frame=-1.0000, Target Frame=1.0000, Target Audio Sample=0.0000, pts=0.0000)
FFmpegReader::GetAudioPTSLocation (tracking missing frame) (missing_audio_frame=-1.0000, previous_audio_frame=-1.0000, new location frame=1.0000)
FFmpegReader::GetAudioPTSLocation (tracking missing frame) (missing_audio_frame=0.0000, previous_audio_frame=-1.0000, new location frame=1.0000)
FFmpegReader::ProcessAudioPacket (Before) (requested_frame=1.0000, target_frame=1.0000, starting_sample=0.0000)
FFmpegReader::ProcessAudioPacket (Decode Info A) (pts_counter=0.0000, PTS=0.0000, Offset=-48.0000, PTS Diff=0.0000, Samples=0.0000, Sample PTS ratio=-nan)
FFmpegReader::ProcessAudioPacket (Decode Info B) (Sample Diff=0.0000, Total=0.0000, PTS Seconds=0.0000, Sample Seconds=0.0000, Seconds Diff=0.0000, raw samples=0.0000)
FFmpegReader::ProcessAudioPacket (ReSample) (packet_samples=0.0000, info.channels=2.0000, info.sample_rate=44100.0000, aCodecCtx->sample_fmt=8.0000, AV_SAMPLE_FMT_S16=1.0000)
[AudioData @ 0x7fffffffb5a0] invalid NULL pointer for src[0]

```

I would send a PR to fix this, but don't know whether this function is the right place to fix this and whether it is safe just return from ProcessAudioPacket after this case is detected.
Can anyone more experienced with FFmpeg (and libopenshot) take a look on this?

**Comment by rrd108** [comment]
I got the same error, and I do not have audio on the preview

**Comment by ferdnyc** [comment]
Is this still an issue for anyone? The audio processing code has been updated a great deal since this report, I'm going to assume the issue was addressed. (I know that the test executable reports no errors on my system, at least.)

I'll close this as outdated and presumed resolved, please file new issues with updated details if not.
