### ISSUE TITLE
codec_type has number of references in FFmpeg, while usage specific in libopenshot is not mentioned

### ISSUE THREAD

**Issue by SuslikV** [OpenShot/libopenshot#299]
Logically the `AV_GET_CODEC_TYPE`  always points to part of `AVCodecContext` structure through the next code of libopenshot (audio and video):
https://github.com/OpenShot/libopenshot/blob/05c21ae2d5adabf36916ce6804a08fa54d587450/src/FFmpegWriter.cpp#L1080
https://github.com/OpenShot/libopenshot/blob/05c21ae2d5adabf36916ce6804a08fa54d587450/src/FFmpegWriter.cpp#L1213

but uses different places where the data from `AVCodecContext` structure is referenced. Here I mean, that the source of the `codec_type` pointer inside libopenshot - only `AVCodecContext` structure (which it belongs too).

I think the `AV_GET_CODEC_TYPE` should point only to `codec_type` (enumeration) as part of the `AVCodecContext` structure, no matter where this structure pointer is mentioned.
**Thus,**
current `AVStream` structure specific reference to `codec_type` should be named as `AV_GET_CODEC_TYPE_AVSTREAM` (instead of just `AV_GET_CODEC_TYPE`)
**or**
new definition added as `AV_GET_CODEC_TYPE_CODEC_CONTEXT` that points exclusively to the `AVCodecContext`'s corresponding field.

The AVCodecContext Struct itself is using different types of enumerations (`CodecType` and `AVMediaType`) for the same pointer (`codec_type`), for FFmpeg below v2.x:
https://ffmpeg.org/doxygen/0.5/structAVCodecContext.html
https://ffmpeg.org/doxygen/1.0/structAVCodecContext.html

while in the code, for FFmpeg 2.x, it just points to "some" data of unknown type (I hope, that FFmpeg below 2.x is not possible to use with the libopenshot and nobody will try it ever, so this is minor part of the issue).
https://github.com/OpenShot/libopenshot/blob/05c21ae2d5adabf36916ce6804a08fa54d587450/include/FFmpegUtilities.h#L266

**Comment by ferdnyc** [comment]
@SuslikV 

I'm not _completely_ following what you're saying here, but `codec_type` is not a pointer. It's a value from an enumeration, so effectively it's a simple integer. 

The enumeration was _renamed_ between FFmpeg 0.5 and 1.0, but it's the exact same enumeration with the exact same values. Only the name is changed, and it only exists under one name or the other, depending on the versions — you'll never encounter both names in the same code. So, that's not any sort of issue. 

FFmpeg's APIs went through a lot of renaming, over the first few years, as they settled on the scheme they wanted to use and prefixed more generic names with `AV_`. 

(If their `RSHIFT` implementation was named `AV_UTIL_RSHIFT` like it _should've_ been, we wouldn't have this trouble in the Ruby bindings, due to a naming conflict:)
```
%{
/* Ruby and FFmpeg define competing RSHIFT macros,
 * so we move Ruby's out of the way for now. We'll
 * restore it after dealing with FFmpeg's
 */
#ifdef RSHIFT
  #define RB_RSHIFT(a, b) RSHIFT(a, b)
  #undef RSHIFT
#endif
```
```
/* Move FFmpeg's RSHIFT to FF_RSHIFT, if present */
#ifdef RSHIFT
  #define FF_RSHIFT(a, b) RSHIFT(a, b)
  #undef RSHIFT
#endif
/* And restore Ruby's RSHIFT, if we captured it */
#ifdef RB_RSHIFT
  #define RSHIFT(a, b) RB_RSHIFT(a, b)
#endif
%}
```

But going back to your issue, the AVStream `codec_type` **IS** the AVCodecContext `codec_type` — it's the exact same `AVMediaType` enum, and in fact here's the relevant code from the [FLV decoder's create_stream()](https://ffmpeg.org/doxygen/trunk/libavformat_2flvdec_8c_source.html#l00161) (just as a random search-result pick):

```c
static AVStream *create_stream(AVFormatContext *s, int codec_type)
{
    FLVContext *flv   = s->priv_data;
    AVStream *st = avformat_new_stream(s, NULL);
    if (!st)
        return NULL;
    st->codecpar->codec_type = codec_type;
    if (s->nb_streams>=3 ||(   s->nb_streams==2
                           && s->streams[0]->codecpar->codec_type != AVMEDIA_TYPE_SUBTITLE
                           && s->streams[1]->codecpar->codec_type != AVMEDIA_TYPE_SUBTITLE
                           && s->streams[0]->codecpar->codec_type != AVMEDIA_TYPE_DATA
                           && s->streams[1]->codecpar->codec_type != AVMEDIA_TYPE_DATA))
        s->ctx_flags &= ~AVFMTCTX_NOHEADER;
    if (codec_type == AVMEDIA_TYPE_AUDIO) {
        st->codecpar->bit_rate = flv->audio_bit_rate;
        flv->missing_streams &= ~FLV_HEADER_FLAG_HASAUDIO;
    }
    if (codec_type == AVMEDIA_TYPE_VIDEO) {
        st->codecpar->bit_rate = flv->video_bit_rate;
        flv->missing_streams &= ~FLV_HEADER_FLAG_HASVIDEO;
        st->avg_frame_rate = flv->framerate;
    }
```
AVStream itself doesn't contain a `codec_type`, what it _does_ contain is a `codecpar` poiinter to an `AVCodecParameters` struct. And `AVCodecParameters::codec_type` is a value from the same enum as `AVCodec::type`: `AVCodecContext` once again references that same type. They're meant to be interchangeable / comparable to each other:

![image](https://user-images.githubusercontent.com/538020/62588637-8060aa00-b894-11e9-9487-7682d998c7e4.png)

---

![image](https://user-images.githubusercontent.com/538020/62588625-78086f00-b894-11e9-917d-9ac9d79543bb.png)

----

![image](https://user-images.githubusercontent.com/538020/62588756-e0575080-b894-11e9-9bbb-c619fe0c8f3e.png)


The only reason there's an `AV_GET_CODEC_TYPE()` macro on libopenshot _at all_ is because, depending on the FFmpeg version in use, the stream's `codec_type` will be accessed as either `av_stream->codec->codec_type` or `av_stream->codecpar->codec_type`. They renamed the `AVStream` member between... looks like, between FFmpeg 3.0 and 3.2. `FFmpegUtilities.h` only contains wrappers for the FFmpeg operations that have different semantics (due to API changes) for different versions of the library.

Yes, `AV_GET_CODEC_TYPE_FROM_STREAM` would be a more precise (but excessively long) name for the macro, but even if we renamed it there wouldn't need to be a `AV_GET_CODEC_TYPE_FROM_CODEC_CONTEXT()` macro to go with it. If you want the `codec_type` of an `AVCodecContext`, just access it directly as `ctx->codec_type`. There's no need for a macro to wrap that call, since the code is exactly the same for any FFmpeg version back to time immemorial. (Or at least back as far as they have documentation.)

**Comment by ferdnyc** [comment]
Actually, let's compromise. I think renaming the macro to `AVSTREAM_GET_CODEC_TYPE()` makes sense, as it more clearly indicates the (limited) purpose of that macro, and doesn't leave it open to misinterpretation that it might be useful in other contexts (no pun intended).

But like I said, there's no reason to have a macro at all, for accessing _other_ paths to `codec_type`, since that code doesn't change based on the library version.

**Comment by SuslikV** [comment]
> But like I said, there's no reason to have a macro at all, for accessing _other_ paths to `codec_type`, since that code doesn't change based on the library version.

When I did it in #219 , I was told that this is wrong usage of it in libopenshot.

**Comment by ferdnyc** [comment]
> When I did it in #219 , I was told that this is wrong usage of it in libopenshot.

Well, then it is, so that's that. Whether or not it's **technically** permissible to look up the `codec_type` through the context, project coming style is to always use the macro, and go through the stream. So unless there's some reason why that'll cause _undesirable_ behavior, that's the way it should be coded. "They're the same, it doesn't matter" isn't a good enough reason to do it differently. If they **are** the same, then there's no reason to break with the established coding style.

Part of submitting code to any project is having to do things in the manner the maintainer(s) prefer, for any reason or for **no** reason at all. Sometimes there are technical reasons behind the scenes (or that have been encountered in the past), sometimes it's just personal preference.

Whoever maintains the codebase is the one who's going to have to understand the submitted code, debug it, and make further modifications to it in the future. They don't have to justify the way _they_ do things, anyone submitting code has to justify not following their preferred standards. 

(Sometimes there are good reasons **not** to follow the existing norms, and in those situations the submitter can make their case for adopting a change in style. But it's their case to make, since no PR ever _has_ to be merged. And unless the project maintainers are happy with it, it won't be.)

 In fact, now that I've read that history, it's making me reconsider my macro rename PR. When I put that together, I hadn't considered that it might be **intentional** that all requests for `codec_type` go through the stream. It sounds like that's the case, which means my PR is a bad idea. Even if it's possible to get the `codec_type` another way, code in libopenshot **isn't _supposed to_**. It's not about macro or no macro, it's about the preferred way of coding certain operations.
