### ISSUE TITLE
Memory increasing in TextReader

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#327]
When I run the code below memory usage just keeps increasing, it will keep increasing until the system crashes. On a 8GB machine it hits 45% with just 15 clips. By comparison I can create videos with 40-50 QtImageReader clips, if not more, without a problem.

```
Timeline timeline(1280, 720, Fraction(25,1), 44100, 2, LAYOUT_STEREO);
timeline.color = Color("#000000");

Clip clip1(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip1.Position(0);
clip1.Layer(1);
clip1.Start(0);
clip1.End(3);

Clip clip2(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip2.Position(4);
clip2.Layer(1);
clip2.Start(0);
clip2.End(3);

Clip clip3(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip3.Position(8);
clip3.Layer(1);
clip3.Start(0);
clip3.End(3);

Clip clip4(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip4.Position(12);
clip4.Layer(1);
clip4.Start(0);
clip4.End(3);

Clip clip5(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip5.Position(12);
clip5.Layer(1);
clip5.Start(0);
clip5.End(3);

Clip clip6(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip6.Position(16);
clip6.Layer(1);
clip6.Start(0);
clip6.End(3);

Clip clip7(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip7.Position(20);
clip7.Layer(1);
clip7.Start(0);
clip7.End(3);

Clip clip8(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip8.Position(24);
clip8.Layer(1);
clip8.Start(0);
clip8.End(3);

Clip clip9(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip9.Position(28);
clip9.Layer(1);
clip9.Start(0);
clip9.End(3);

Clip clip10(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip10.Position(32);
clip10.Layer(1);
clip10.Start(0);
clip10.End(3);

Clip clip11(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip11.Position(36);
clip11.Layer(1);
clip11.Start(0);
clip11.End(3);

Clip clip12(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip12.Position(40);
clip12.Layer(1);
clip12.Start(0);
clip12.End(3);

Clip clip13(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip13.Position(44);
clip13.Layer(1);
clip13.Start(0);
clip13.End(3);

Clip clip14(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip14.Position(48);
clip14.Layer(1);
clip14.Start(0);
clip14.End(3);

Clip clip15(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip15.Position(52);
clip15.Layer(1);
clip15.Start(0);
clip15.End(3);

timeline.AddClip(&clip1);
timeline.AddClip(&clip2);
timeline.AddClip(&clip3);
timeline.AddClip(&clip4);
timeline.AddClip(&clip5);
timeline.AddClip(&clip6);
timeline.AddClip(&clip7);
timeline.AddClip(&clip8);
timeline.AddClip(&clip9);
timeline.AddClip(&clip10);
timeline.AddClip(&clip11);
timeline.AddClip(&clip12);
timeline.AddClip(&clip13);
timeline.AddClip(&clip14);
timeline.AddClip(&clip15);

timeline.Open();

FFmpegWriter writer("output.mp4");
writer.SetVideoOptions(true, "libx264", Fraction(25, 1), 1280, 720, Fraction(1,1), false, false, 0);
writer.PrepareStreams();
writer.SetOption(VIDEO_STREAM, "crf", "23" );
writer.WriteHeader();
writer.Open();
writer.WriteFrame(&timeline, 0, (52 + 3) * 25);
writer.Close();

timeline.Close();
```
I tried this with the new QtTextReader and QtHtmlReader I've been working on (#305) and they also have the same issue so not sure if this is something to do with text/font handling or something else. I thought initially it was an ImageMagick issue but looks like it affects Qt as well.

**Comment by ferdnyc** [comment]
Hmm. It's not clear to me that it's _technically_ a memory **leak**, yet, because there are no explicit attempts to release the memory in use

(By which I mean, if you were to stop before you ran out of memory, then close the writer (but not the timeline), would some/all of the extra memory be freed? If so, then like what was happening with my memory profiling tests in OpenShot/openshot-qt#2811, I'd consider it less a _leak_ per se than simply a failure in some part of the export process to release allocations as quickly as it should. That distinction is important because it can help us track down the culprit.)

All that being said, this does sound frightfully similar to #239 (which was the cause of the growth I was seeing in OpenShot/openshot-qt#2811, and which @ckirmise fixed with #240 — BTW, you're running post-0.2.3 code with that patch included, right?), and may be a similar form of unreleased cache issue.

Two more tests that would be instructive:

1. What happens if you use explicit single `GetFrame()` and `WriteFrame()` calls in a loop to write the file, like in `src/examples/Example.cpp` and/or like OpenShot itself does it, instead of via a single large `WriteFrame(*reader, start, end)`? Is the extra allocation coming from `WriteFrame()` not releasing the individual frames when it handles them internally, or is it happening no matter where they're managed?

1. What's the primary factor in the extra memory consumption: the number of clips, or the length of the timeline? If you construct the same length of timeline using two clips each 32 seconds in length, how does that change the results? What about four 16-second clips? That would help us determine whether the growth is in the readers generating the frames, or in the  timeline / writer as it consumes frames from the readers. 

The `memusage` command can be invaluable for capturing structured profiles of different scenarios for cross-comparison; the commands I used testing OpenShot's memory consumption are documented in OpenShot/openshot-qt#2811.

**Comment by jeffski** [comment]
I tried this, (please forgive the code) and memory was stable at about 4.5%:

```
FFmpegWriter writer("output.mp4");
writer.SetVideoOptions(true, "libx264", Fraction(25, 1), 1280, 720, Fraction(1,1), false, false, 0);
writer.PrepareStreams();
writer.SetOption(VIDEO_STREAM, "crf", "23" );
writer.WriteHeader();
writer.Open();

Clip clip1(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "1 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip1.Position(0);
clip1.Layer(1);
clip1.Start(0);
clip1.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip1.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip2(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "2 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip2.Position(4);
clip2.Layer(1);
clip2.Start(0);
clip2.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip2.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip3(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "3 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip3.Position(8);
clip3.Layer(1);
clip3.Start(0);
clip3.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip3.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip4(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "4 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip4.Position(12);
clip4.Layer(1);
clip4.Start(0);
clip4.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip4.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip5(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "5 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip5.Position(12);
clip5.Layer(1);
clip5.Start(0);
clip5.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip5.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip6(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "6 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip6.Position(16);
clip6.Layer(1);
clip6.Start(0);
clip6.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip6.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip7(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "7 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip7.Position(20);
clip7.Layer(1);
clip7.Start(0);
clip7.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip7.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip8(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "8 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip8.Position(24);
clip8.Layer(1);
clip8.Start(0);
clip8.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip8.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip9(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "9 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip9.Position(28);
clip9.Layer(1);
clip9.Start(0);
clip9.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip9.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip10(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "10 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip10.Position(32);
clip10.Layer(1);
clip10.Start(0);
clip10.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip10.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip11(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "11 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip11.Position(36);
clip11.Layer(1);
clip11.Start(0);
clip11.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip11.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip12(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "12 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip12.Position(40);
clip12.Layer(1);
clip12.Start(0);
clip12.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip12.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip13(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "13 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip13.Position(44);
clip13.Layer(1);
clip13.Start(0);
clip13.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip13.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip14(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "14 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip14.Position(48);
clip14.Layer(1);
clip14.Start(0);
clip14.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip14.GetFrame(frame_number);
	writer.WriteFrame(f);
}

Clip clip15(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, " 15 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip15.Position(52);
clip15.Layer(1);
clip15.Start(0);
clip15.End(3);

for (long int frame = 1; frame <= 100; frame++)
{
	int frame_number = frame;
	std::shared_ptr<Frame> f = clip15.GetFrame(frame_number);
	writer.WriteFrame(f);
}

writer.Close();

return 0;
}
```

Maybe this will help highlight an issue. I think it is the memory growing and not a leak as you suggest.

This wouldn't give me the same results though as working from the timeline, for example I should have 1 second gaps between clips. How does OpenShot go through a timeline and work out how all the clips are layered, there could be multiple clips at the same position with different transparencies for example. Any links to source code would be much appreciated.

I'll continue investigating your other points. I do have the latest changes from #240.

**Comment by jeffski** [comment]
> for example I should have 1 second gaps between clips
Ignore this bit, it's obvious now.

**Comment by jeffski** [comment]
Ran a couple more tests, it seems that the number of clips has a greater impact on the memory usage. I modified my initial script but with 15 clips, each 1 second long and memory usage was climbing to about 37%. With 2 clips of 30 seconds the memory usage was around 9.2% and then jumped up to 12.1%, I guess for each clip.

**Comment by ferdnyc** [comment]
Interesting...

I'm still curious about the effects of the timeline as the frame source, vs. the reader directly. What if you were to place a single, long clip on a timeline, and use that instead of pulling frames from the clip readers directly? Does that look more like the explosive case, or more like your second test?

**Comment by jeffski** [comment]
Do you mean something like this: 

```
Timeline timeline(1280, 720, Fraction(25,1), 44100, 2, LAYOUT_STEREO);

Clip clip1(new TextReader(1280, 720, 0, 0, GRAVITY_CENTER, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor", "Ubuntu", 24, "#ffffff", "#000000"));
clip1.Position(0);
clip1.Layer(1);
clip1.Start(0);
clip1.End(120);

timeline.AddClip(&clip1);

timeline.Open();

FFmpegWriter writer("/tmp/output.mp4");
writer.SetVideoOptions(true, "libx264", Fraction(25, 1), 1280, 720, Fraction(1,1), false, false, 0);
writer.PrepareStreams();
writer.SetOption(VIDEO_STREAM, "crf", "23" );
writer.WriteHeader();
writer.Open();
writer.WriteFrame(&timeline, 0, 120 * 25);

writer.Close();

timeline.Close();
```

With this the memory usage stays steady at 9.3%

I also tried this:

```
list<Clip*> clips = timeline.Clips();

for (Clip* clip : clips)
{
	for (long int frame = 1; frame <= (clip->Duration() * 25); frame++) {
		int frame_number = frame;
		std::shared_ptr<Frame> f = clip->GetFrame(frame_number);
		writer.WriteFrame(f);
	}
}
```

The memory also keeps increasing with this, could be my code is no good in this case though.

**Comment by jeffski** [comment]
Just confirming this only seems to affect the TextReader (and also the new readers I've been working on), I just tested now with images (QtImageReader) and it seemed fine with memory usage below 5%.

**Comment by jeffski** [comment]
This seems to be the offending line:

https://github.com/OpenShot/libopenshot/blob/febc2fbc7d4129491a7ca010bd51ed88519f40fb/src/TextReader.cpp#L130

It is creating the text reader that is 24 hours long with millions of frames in the FrameMapper which is causing the memory usage to explode for each text clip.

I changed to the value to 60 and then 1 and in both cases the memory issue is gone and rendering is much faster. There didn't seem to be any issues, I rendered a video with the 15 clips as above no problem and rendered another with a 40 second clip but an `info.duration` set to 1.

I am unsure why this value would be 24 hours (it is 24 hours in the ImageReaders and the new Qt Text/HTML readers).

Unless there is a good reason I think this value should be changed to 1 and will go ahead and create a pull request with all 24 hour duration's changed in all image based readers.

**Comment by ferdnyc** [comment]
This issue was just [re-reported downstream](https://bugzilla.rpmfusion.org/show_bug.cgi?id=5431) in RPM Fusion. 

The still-image readers aren't **SUPPOSED** to be consuming _any_ extra memory per frame, so duration "should" just be metadata. In _theory_, they know that they're still-frame sources so they just return the same frame every time, no matter what frame# is requested from them. But apparently that broke somewhere along the way, and the source of the breakage hasn't been tracked down yet. (Mostly for my lack of time to work on the bisect.)

**Comment by musteresel** [comment]
Could it be that `image_frame` (here: https://github.com/OpenShot/libopenshot/blob/develop/src/TextReader.cpp#L169) should be cached?

**Comment by ferdnyc** [comment]
@musteresel It would be great if it could be. I'm not sure that's possible, though — at least, not completely — since `GetFrame()` requests come with a frame number, and the resulting. `OpenShot::Frame` objects include that frame#.

We _might_ be able to keep the rendered image data as an `OpenShot::Frame` that we just copy and call [SetFrameNumber()](https://openshot.org/files/libopenshot/classopenshot_1_1Frame.html#af9b8e1e2735e27244708fa1e61c541ae) on before returning. That should certainly be less wasteful, especially if the Frame objects can point to the same shared image data, and only differ by the `frame_number` stored in them. But it seems like we probably need to return a unique frame object, at least, for each frame requested.

A more complete optimization would be possible if the caller were **aware** that it should only expect 1 frame from this source (without its duration having to be reduced). Then (in theory) it would only request the frame just _once_, and keep reusing the data for itself.

Still, it should be possible to at least streamline the `TextReader` further by storing its data in a more "cooked" form. (Including, as the `TODO` comment in the code says, using `QImage` to store the frame-bound image data instead of creating it with ImageMagick on every frame request.)

**Comment by ferdnyc** [comment]
(Note: I could also be wrong about that. I don't know the Writer / Frame-processing code very well. Maybe it'd be totally fine to ignore the `requested_frame`, and just return an `OpenShot::Frame` object with a `frame_number` of `1` each time.)

**Comment by ferdnyc** [comment]
> @musteresel It would be great if it could be. I'm not sure that's possible, though — at least, not completely — since `GetFrame()` requests come with a frame number, and the resulting. `OpenShot::Frame` objects include that frame#.

And I eventually realized, it's _vital_ that every returned frame have a unique frame# — those frame numbers will be used to match each Frame up with the right values for that point in time, when there are any Keyframe'd properties involved.

If a generative Reader that only output a single still frame image were to output the same Frame object repeatedly (all with the same frame#), then the Keyframe implementation would break down trying to apply properties to those frames (/ "that frame").

But, yeah, it does still seem like we could cache the _contents_ of the Frame objects, and make their duplication more lightweight than it is now.
