### ISSUE TITLE
Use MXE to build OpenShot for Windows?

### ISSUE THREAD

**Issue by mlocati** [OpenShot/libopenshot#35]
What about using [MXE](http://mxe.cc/) to cross-compile OpenShot for Windows? It already comes with [a lot of packages](http://mxe.cc/#packages), and supports both 32-bit and 64-bit Windows builds...

**Comment by ferdnyc** [comment]
I did give this a try, at one point... the problem with MXE is the problem with most cross-compilation environments, you end up having to build everything yourself from scratch. I don't think I even got as far as trying to build libopenshot or libopenshot-audio, I was still building things like Qt and FFmpeg last I remember going back to it. (And it already took up several gigs of disk space, to hold all that.)

Whereas MSYS2 with `pacman` lets me install binary packages for those things. (But it does require Windows, which is its own bummer.)

The other issue — well, I'm not sure how much of an issue it will be, ultimately — is that we normally link libopenshot with several Windows system DLLs during the build. I'm not sure how that sort of thing would be handled, in MXE. (As I said, I haven't gotten that far in the process yet.)

**Comment by ferdnyc** [comment]
Oh, right. Looking at it again, the other missing parts from their package list are SWIG and Python. In _theory_ SWIG isn't **necessary**, since the native Linux SWIG could be used in its place. All SWIG does is generate source code.

But _building_ the resulting SWIG-generated bindings requires linking them with the Python library, and it doesn't seem that the MXE build environment has a libpython DLL to link with.

**Comment by ferdnyc** [comment]
I'm going to close this as "not currently on the radar", since the only person who was looking into it (me) has abandoned the idea. The more I think about it, the more sure I am that the missing Windows system DLLs would be the real dealbreaker for compiling under MXE, since a libopenshot that isn't linked with those won't be correctly built.

It was an interesting idea, though, and worth exploring. Thanks!
