### ISSUE TITLE
Bug in CONSTANT interpolation between first two points?

### ISSUE THREAD

**Issue by musteresel** [OpenShot/libopenshot#369]
I've stumbled upon something strange... consider this:

```c++
Keyframe kf;
kf.AddPoint(Point(Coordinate(1,1), CONSTANT));
kf.AddPoint(Point(Coordinate(2,50), CONSTANT));
kf.AddPoint(Point(Coordinate(3,100), CONSTANT));

int const valueAt2 = kf.GetInt(2);
int const valueAt3 = kf.GetInt(3);
```

I'd expect `valueAt2 == 50` and `valueAt3 == 100`, but I get `valueAt2 == 1` (`valueAt3` is as expected).

This is due to a special case in `Keyframe::ProcessSegment` where the first segment (between the first two points) for `CONSTANT` interpolation is handled differently with:

```c++
		if (Segment == 0)
			// first segment has 1 extra value
			number_of_values++;
```

Git Blame shows this is here since the initial commit .. why does the first segment need an extra value? This seems like a bug to me?

Note that this is not about values *before* the first `Point` ... those are already handled before calling `ProcessSegment`.

**Comment by ferdnyc** [comment]
I'm not seeing that, in the Python interface. Running against `libopenhot` built from the develop branch...
```python
>>> k = openshot.Keyframe()
>>> k.AddPoint(openshot.Point(openshot.Coordinate(1,10), openshot.CONSTANT))
>>> k.AddPoint(openshot.Point(openshot.Coordinate(2,50), openshot.CONSTANT))
>>> k.AddPoint(openshot.Point(openshot.Coordinate(3,100), openshot.CONSTANT))
>>> print([k.GetInt(x) for x in range(0,10)])
[10, 10, 50, 100, 100, 100, 100, 100, 100, 100]
```

> This is due to a special case

It isn't. I don't believe what you're pointing out is/could-be causing that at all.

> the first segment (between the first two points) for `CONSTANT` interpolation

For all interpolations. They all do some version of the "increment `number_of_values`" thing. `BEZIER` _always_ does it (because it's building a side-list), while `CONSTANT` and `LINEAR` do it only for the first segment.

> why does the first segment need an extra value? This seems like a bug to me?

It's not. The extra value is the value _at_ the starting point.

> Note that this is not about values _before_ the first `Point` ... those are already handled before calling `ProcessSegment`.

True. And then when `ProcessSegment()` executes, it starts off by computing `number_of_values` as the difference in the points' `X` coordinates. So, if a segment runs from `x1 = 5` to `x2 = 10`, it'll push `(10 - 5) = 5` points, representing the values from `x1+1 ... x2`. 

That works because the value at `x1` has already been pushed by the previous `ProcessSegment()`... _**unless**_ there _is no_ previous `ProcessSegment()`. In that case, when it's the first time through, `ProcessSegment()` needs to push **`6`** values, representing all of `x1 ... x2`.

Without that logic, the `(1, 10)` point would never cause a value to be pushed at all, because `(1,10)` was never the _end_ of a segment. Normally (meaning, in every case other than the firs segment), a point's value is pushed at the end of its preceding segment, not the start of its following one. So, the list in my Python example would've come out as:
```python
>>> print([k.GetInt(x) for x in range(0,10)])
[10, 50, 100, 100, 100, 100, 100, 100, 100, 100]
```
With the lone `10` being added not by `ProcessSegment`, but by that pre-processing fill from before `Points[0]`.

**Comment by ferdnyc** [comment]
Note that if you try to access `kf.Values` _directly_, you may see weirdness because `kf.Process()` hasn't run yet. e.g:
```python
>>> k = openshot.Keyframe()
>>> k.AddPoint(openshot.Point(openshot.Coordinate(1,10), openshot.CONSTANT))
>>> k.AddPoint(openshot.Point(openshot.Coordinate(2,20), openshot.CONSTANT))
>>> k.AddPoint(openshot.Point(openshot.Coordinate(3,30), openshot.CONSTANT));
>>> print("\n".join([str((k.Values[x].X, k.Values[x].Y)) for x in range(0,k.Values.size())]))

>>> # Hmmm?
>>> k.Values.size()
0
>>> # Aha!
>>> k.Process()
>>> k.Values.size()
4
>>> print("\n".join([str((k.Values[x].X, k.Values[x].Y)) for x in range(0,k.Values.size())]))
(0.0, 10.0)
(1.0, 10.0)
(2.0, 20.0)
(3.0, 30.0)
```

But `GetInt()` should protect you from that, and trigger `Process()` automatically.

**Comment by musteresel** [comment]
Oh my; I found the issue.  It's on my side; I've run the tests with a version of libopenshot in which I already had modified the `Keyframe::AddPoint()` code but missed a bug that only occurs sometimes (when adding the point causes relocation of the `Points` vector). So in short: The `AddPoint()` failed to add the point with X = 2, and just duplicated the point with X = 3. Therefore `GetValue(2)` *correctly* returned 1 ...
