### ISSUE TITLE
Property Categories

### ISSUE THREAD

**Issue by mkarg** [OpenShot/libopenshot#372]
Some objects, like clips or effects, offer a rather long list of properties.

This is very beneficial but at the same time very unclear and rather confusion, particular for beginners.

In an attempt to find particular properties more easily, it might be a good idea if each property optionally could publish a category name, so GUIs would be able to group them in categories.

For example, a clip has four "crop" properties, among many others. A GUI could like to group properties in expandable boxes per topic, so there could be a collapsed box "Crop" which you can expand to see the four "crop" properties. To support such GUI enhancements, libopenshot needs to support optional category names for properties. For backwards compatibility, it still should be possible that properties do not have a category, so they show up in one common "Common" box.

**Comment by ferdnyc** [comment]
Alternatively, our properties get more complex. (Just throwing it out there, not saying it's the correct approach — in fact, I'm pretty sure it's not, at least from the UI perspective.)

For instance, instead of CropX and CropY, CropW and CropH...
```json
//
// A `crop` keyframe becomes a list of four values:
//
{ "crop" : {
   "Points": [
    { "x" : 1.0,
      "value" : [ "w", "h", "x", "y" ],
      "interpolation" : [ 2, 1 ]
  } ] }
}
// But using numeric values, not strings, of course.
// (n.b. re: interpolation: separate input and output curves?)

//
// Or maybe a pair of tuples:
//
{ "crop" : {
   "Points" : [
    { "x" : 1.0,
      "size" : [ "w", "h" ],
      "position" : [ "x", "y" ],
      "interpolation" : [ 2, 1 ]
  } ] }
}
//
// Or some other, slightly higher-level representation than this:
//
     "crop_x": {
      "Points": [
       {
        "interpolation": 2,
        "co": {
         "Y": 0.0,
         "X": 1.0
        }
       }
      ]
     },
     "crop_height": {
      "Points": [
       {
        "interpolation": 2,
        "co": {
         "Y": -1.0,
         "X": 1.0
        }
       }
      ]
     },
     "crop_y": {
      "Points": [
       {
        "interpolation": 2,
        "co": {
         "Y": 0.0,
         "X": 1.0
        }
       }
      ]
     },
     "crop_width": {
      "Points": [
       {
        "interpolation": 2,
        "co": {
         "Y": -1.0,
         "X": 1.0
        }
       }
      ]
     },
```

...Even this would be a major change, and it only addresses the backend data storage... new syntax for data files does nothing to help the user actually set those values.

Ideally rather than the values being directly manipulable in "raw" form (individual sliders, one per property), this would be coupled with new UI tools for adjusting values more implicitly.

The Transform interface is a model for how that sort of thing could work. It already provides an interface for altering ScaleX and ScaleY, along with LocationX and LocationY, without ever touching the raw numeric values. Certainly, things like cropping/scaling could offer a similar approach.

If those UI tools were the default/preferred/recommended method of setting those values, then maybe they don't need individual sliders in the Properties list anymore, maybe a single Properties entry representing the composite parameter set is enough. (But probably still expandable into individual components, or somehow able to be drilled-down into when necessary.)

**Comment by mkarg** [comment]
I do not see that support for such tooling is actually a *competitive* approach, but a *complementatory* one. Hence I'd propose that we open a second issue for that "alternative" proposal. The reason is that people think and work different. There might be some who don't like the new tooling and want to stay with the sliders. They might even get confused by the fact that every other group of properties has a different kind of tooling. There might be even cases when *both*, sliders and tooling, are needed (e. g. drawing a box is conventient, but if the box has to be accurate it is better to type in a value). There also might be lots of properties where sliders already *are* the perfect tooling, but still users like to have the sliders *grouped*. So, let's add *both*, property groups *and* tooling. They solve different problems (tooling solves the problem that properties are related and even might interfer, while sliders do not support that), and they serve different user expectations.

**Comment by musteresel** [comment]
> Alternatively, our properties get more complex. (Just throwing it out there, not saying it's the correct approach — in fact, I'm pretty sure it's not, at least from the UI perspective.)

> Ideally rather than the values being directly manipulable in "raw" form (individual sliders, one per property), this would be coupled with new UI tools for adjusting values more implicitly.

Please don't try to push this change down to the `Keyframe` class it will become *a lot* more complex than it currently is (even the new code).  And it will make it *much* harder to handle this with reasonable performance.  If more complex properties are desiered, then this should be handled on a higher level. Possibilities I can think of:

 - The UI, e.g. outside of libopenshot
 - A "wrapper" class, specifically for the respective data, e.g.:
    ~~~c++
    class CropKeyframe {
       Keyframe x, y, w, h;
       // code to handle splitting and merging the crop property
    };
    ~~~
- A generic wrapper class, e.g.:
    ~~~c++
    template<typename Property>
    class ComplexKeyframe {
      // code to get a list of sub-keyframes from the Property, code for splitting and merging
    };
    ~~~

The later two approaches could be combined with a change: `Keyframe` is renamed to `ValueKeyframe` (or something similar) and an interface class `Keyframe` is added, which is implemented by the wrappers and the `ValueKeyframe`.
