### ISSUE TITLE
Property Levels

### ISSUE THREAD

**Issue by mkarg** [OpenShot/libopenshot#373]
Typically beginners will be confused by too many properties, and they will use e. g. only 20% of the existing properties. Advanced users have learned the benefits of additional properties, and like to use e. g. 75%. And some people are experts and really use 100% (I doubt that actually).

If we always show 100% of the features, advanced users could be slightly irritated, but definitively beginners will be confused by all the stuff they do not need and do not understand.

So it might be a good idea if properties optionally could publish a "Level" string, so GUIs could offer to hide particular levels. For example, openshot-qt could build a list of all reported levels, and offer a system setting where the user can effectively hide all properties reporting the "Level" string "Expert" or "Advanced".

**Comment by ferdnyc** [comment]
Definitely something like that. I don't know about _levels_ per se. (I'm just not sure properties naturally fall into groupings like that — the "Advanced" properties are whichever ones a particular user doesn't use, realistically. If we did have more of a _hierarchy_ of properties, then that could make sense, but as things stand I think they're mostly pretty flat. And even the current, mostly flat set is overcrowded.)

What I would love to see is some _grouping_. (So that e.g. Start, End, Position, and Duration are together instead of being scattered by alphabetical ordering, for one thing.) And if the groups are collapsible, then that's a step right there.

Additionally, IMHO a win would be to simply _not_ show defaulted properties, unless they're made **non**-default. Like, instead of attaching a keyframe for _every_ keyframeable property to the Clip as soon as it's created, why not just assign the set of unique properties it _does_ have (Start, End, Position, Duration, ID, Track), maybe one or two others that we want to make available at all times (Volume, if nothing else)... and that's it. Don't attach ScaleX and ScaleY properties _at all_ unless the user wants to scale the video. Don't show "Waveform | No" when they _don't_ want the waveform to display, insead give them some way of enabling Waveform IFF they ever want it to be "Yes".

(And that goes for the project file data as well — JSON is most useful when it's used to communicate only relevant data, changes to some established baseline. There shouldn't be any keyframes present in the project data _**at all**_ until and unless the user adds their first one explicitly on the Timeline. IMHO. ...And if our project data did work like that, things like the saturation-properties bug we discussed, for instance, wouldn't — couldn't — occur.)

**Comment by mkarg** [comment]
We need to take care not to mix up things. Grouping properties is something different to giving them a level. Grouping means, the properties are *related*. Level means, the user is not experienced enough. Lots of software supports at least Basic vs. Advanced, and I know several people who would love to be able to reduce the amoung of visible properties by their personal experience (hence: limit to Basic).

Properties should not hide dynamically. This should be always a decision of the users. Otherwise he would search and search and search.

Whether you keyframe default values or not is a separate issue and I propose opening another ticket for that. *This* one solely is about people wanting to hide expert properties.

**Comment by ferdnyc** [comment]
That's my argument, though: Which properties are "basic"? Which are "expert"? Having _that_ conversation feels like a prerequisite for talking about implementing a feature to manage different skill levels for properties, because there first have to **be** properties of different skill levels. And... _are_ there?

> We need to take care not to mix up things.

See, I don't completely agree on that. At _this_ stage, IMHO we should be talking about properties-management — no, not even that, about the entire _editing workflow_ — **as a whole**.

No UX feature exists in a vacuum. In implementation, sure, siloed development is a good idea and it's important not to let feature creep derail things. But users' first priority is being able to use the software to accomplish their goals, and they want that to be made as painless and uncomplicated as possible. So, they want whatever features will best get them to that goal.

So, let's talk about the properties list. Here's the complete list of properties for a Clip in OpenShot:

* Alpha
* [Audio] Channel Filter
* [Audio] Channel Mapping
* Crop Height
* Crop Width
* Crop X
* Crop Y
* Duration
* Enable Audio
* Enable Video
* End
* Frame Number [Display]
* Gravity
* ID
* Location X
* Location Y
* [Timeline] Position
* Rotation
* Scale [Mode]
* Scale X
* Scale Y
* Shear X
* Shear Y
* Start
* Time
* Track
* Volume
* Volume Mixing
* Wave Color
* Waveform

Daunting, honestly. But, we can break it down quite a bit.

#### Static data
These properties are fixed, they aren't user-modifiable in any way.
* Duration
* ID

#### Clip-wide parameters (non-keyframeable)
These properties can only be set clip-wide, they're not keyframable. 
* End
* Frame Number [Display]
* Gravity
* [Timeline] Position
* Scale [Mode]
* Start
* Track
* Volume Mixing
* Wave Color
* Waveform

Does it even make sense to show those in the properties table? Probably not in the same way the _keyframable_ properties are shown, at least, since they don't need to be visible frame-to-frame. 

At the same time, that list holds some of the most critical properties, like Start and End. Some users will _never_ use the Properties list to edit them, preferring to make adjustments graphically on the Timeline. Others are constantly making precision adjustments.

#### Opaque data
These properties _are_ keyframable, technically, but realistically they're not anything the user will (or even _can_) typically adjust for themselves.
* [Audio] Channel Filter
* [Audio] Channel Mapping
* Time

Instead of user adjustment, the "Separate Audio" operations set the Channel properties automatically, and the "Time" operations (speed control, freeze-framing, and reversing) will create Time keyframes.

(Time is a particularly special case, because if the user even _attempts_ to manually adjust it... everything breaks, basically. The entire interface to speed-control and the Time property is just abysmal right now.)

#### The remaining list
...Peel all of _those_ sets of properties off, and here's everything that's left. This is the full set of user-adjustable, keyframeable Clip properties:
* Alpha
* Crop Height
* Crop Width
* Crop X
* Crop Y
* Enable Audio
* Enable Video
* Location X
* Location Y
* Rotation
* Scale X
* Scale Y
* Shear X
* Shear Y
* [Audio] Volume

I'd personally have a really hard time assigning skill levels to those, in a way that would seem at all meaningful and not completely arbitrary. I mean, sure, you can say that Shear X and Shear Y are more "expert" than the rest... I'll give up that pair. But other than that, it really feels to me like they're all on equal footing. The ones a person would pick as "expert" are simply whichever ones they don't personally use. Do you disagree?

**Comment by mkarg** [comment]
Yes I do disagree as I think it is actually pretty easy *and* it was performed by other vendors lots of times. It should not be the decision of of just one arbitrary person. It should be the decision of the inventor of the particular property (remember: I want that *optionally*, so the default is "show it always"). So the first candidates for "Advanced" clearly would be Saturation's new R/G/B sliders, as we all agree, these *cannot* be basic as they had not been there for a decade. If we do not agree on that, it should be either a voting by the users at large, or it should be a mechanical counting which property is adjusted how often (this is what commercial software would do, by spying the user and secretly sending it to the cloud).

**Comment by musteresel** [comment]
> (Time is a particularly special case, because if the user even attempts to manually adjust it... everything breaks, basically. The entire interface to speed-control and the Time property is just abysmal right now.)

@ferdnyc as far as I know @jonoomph wants to have that Time property keyframe'd; the currently most important issue about that is AFAIK handling the audio.  I hope I can get to that once I'm done with the keyframes!

> Whether you keyframe default values or not is a separate issue and I propose opening another ticket for that.

It's easier to just have them be a (constant) Keyframe. The (new) Keyframe code can handle this and it simplifies things  (e.g you don't have to check whether a property is using a Keyframe *or* a default value, you just set it as a Keyframe with a single point at `(0, default_value)` with `CONSTANT` interpolation )

**Comment by ferdnyc** [comment]
> If we do not agree on that, it should be either a voting by the users at large, or it should be a mechanical counting which property is adjusted how often (this is what commercial software would do, by spying the user and secretly sending it to the cloud).

Fair enough, but a commercial software project  would also have numbers to back up _these_ claims, before undertaking to add such a feature in the first place:
> Typically beginners will be confused by too many properties, and they will use e. g. only 20% of the existing properties. Advanced users have learned the benefits of additional properties, and like to use e. g. 75%. And some people are experts and really use 100% (I doubt that actually).
>
> If we always show 100% of the features, advanced users could be slightly irritated, but definitively beginners will be confused by all the stuff they do not need and do not understand.

(Numbers for real OpenShot users, specifically, not strawpersons.)

Anyway, as for the specific properties to be labeled "advanced", so far you've still only presented one candidate (well... three, I suppose, technically?):

> So the first candidates for "Advanced" clearly would be Saturation's new R/G/B sliders, as we all agree, these _cannot_ be basic as they had not been there for a decade.

I actually don't agree with that, TBH. If the misgivings I expressed about extending the existing Saturation effect are the motivation for this, then I'm afraid you've gotten the wrong impression of where I stand.

If it's a choice between adding the new properties to the existing effect hidden behind an "Advanced" mode toggle, vs. just adding them to the existing effect unilaterally so they're visible to everyone, of those two options I'd favor the latter. It's a _single_-property effect, making it four properties just doesn't warrant the complication of a multi-level hierarchy IMHO. Yes, I have some misgivings about the property addition, but I have bigger ones about skill levels.

Regardless, I've run out of patience to make my case here, so I retract all objections. If you want to attach skill levels to properties, then why not? They'll be ignored by OpenShot anyway until there's UI for it, so we get to do this all over again on that end.

Only thing I'll ask is, since it's optional, let's do level-assignment exclusively through a setter method, like `add_property_choice_json()`. Rather than adding an argument to `add_property_json()` (or adding a new overload for it), I mean. Because this is... just, unreadable really. Anybody adds even a single argument more to these calls, they're liable to achieve critical mass and implode.
https://github.com/OpenShot/libopenshot/blob/d539e468ca8934c7d72a20e817295c8af665b84a/src/Clip.cpp#L657-L669

**Comment by ferdnyc** [comment]
@musteresel 
> @ferdnyc as far as I know @jonoomph wants to have that Time property keyframe'd; the currently most important issue about that is AFAIK handling the audio. I hope I can get to that once I'm done with the keyframes!

Well, that's great news! **Something** has to give with `Time`, because right now it's practically useless. "Time" as a property (with the way it currently works, meaning its value at any given point in time is the _frame number_ of the source video that's currently visible) is unable to be configured by actual humans. I can only be modified by pre-set algorithms that can map out and generate all of the individual points of data necessary to populate each and every frame of the Keyframe's values list. And those algorithms do a terrible job of it, too, since they make a ton of assumptions and if any of them are wrong the algorithm messes up the values just as badly as a human would. (Which is why they break if you try to apply them after you've used Split Clip (#3071 & #2495), why exported videos that use Time adjustments sometimes don't match the project data (#2840), why it's impossible to _remove_ (or even adjust) Time keyframes once they've been applied to a Clip, except by completely resetting the **entire** clip's Time adjustments back to default Forward-1× speed playback (#2636), etc, etc....

What users want, understandably, is keyframing of _speed_. They want to pick a point, say "Play at 150% speed from this point", and have it do that. And then they want to be able to change their mind later and adjust that from 150% to 160% simply by scrubbing to the keyframe point and altering the parameter value. It's a tricky thing to implement because every speed adjustment has complex side-effect on the whole clip, so despite the occasionally-loud assertions to the contrary it's really not a simple request. But whether or not they have reasonable expectations of the software, it's _**definitely**_ unreasonable to ask that they accept our _current_ `Time` implementation as any kind of substitute.

> > Whether you keyframe default values or not is a separate issue and I propose opening another ticket for that.
> 
> It's easier to just have them be a (constant) Keyframe. The (new) Keyframe code can handle this and it simplifies things (e.g you don't have to check whether a property is using a Keyframe _or_ a default value, you just set it as a Keyframe with a single point at `(0, default_value)` with `CONSTANT` interpolation )

See... I'm glad you brought this up, actually, because populating the clip data with a set of initial parameters doesn't mean you don't _still_ need default values — **especially** if the user has access to modify the values from their initial state. And it's a pretty big design flaw in libopenshot's current properties system, that it _**doesn't**_ have any support for applying default values to the properties.

Try this in OpenShot:
1. New project, import a video, add it to the Timeline.
2. Set the Playhead on the Clip's start frame.
3. Adjust `Scale X` to 0.5
4. (Assume you perform a few other adjustments here that you want to keep, so "Undo" isn't an option.)
5. Decide you don't like that `ScaleX` adjustment you applied, now that you look at it.
6. Go to frame 1, right-click on the `Scale X` row, and choose "Remove keyframe".

What do you end up with? Not what you wanted, that's for sure.

![OpenShot-RemoveKeyframe](https://user-images.githubusercontent.com/538020/69538820-25d97f80-0f51-11ea-82ba-0d3de4cb8a28.gif)

Without defaults, there's no way to return the data to an unmodified state — clearing a property _zeroes_ it, rather than resetting it, which isn't the same thing. Zero happens to be the default for a few of the properties, but only by accident. And zeroing any of the rest just breaks them.

If your data set is mutable then you _still_ need defaults, and defaults by definition **CANNOT** be part of the mutable data. There's really no getting around that.

Implementation-wise, maybe that means inserting a keyframe somewhere the user _can't_ modify it, like at "frame 0". (hey, maybe it's a lucky thing after all, that we start from frame 1!) That's just behind-the-scenes details. But however it's accomplished, there needs to be an _immutable_ baseline state that's outside of the user's control, a state the data will return to when they remove their modifications. We haven't got truly non-destructive editing without it.
