### ISSUE TITLE
source video dimension changing - handling?

### ISSUE THREAD

**Issue by yamass** [OpenShot/libopenshot#382]
Hi,

I am trying to mix some videos files (webm, VP8, opus) from webrtc sessions using libopenshot (Python bindings). The videos have changing resolutions since the browser may change resolution dynamically.

When the resolution changes occur, the clip containing the video just displays the video in a cropped manner. The size of the clip does not change, nor does the content get scaled in any way to fit the clip.

I there any way to detect handle resolution changes in source video files using libopenshot?

**Comment by ferdnyc** [comment]
I was honestly not aware that it was even _possible_ for a video to change resolution mid-stream, TBH. I see that [it _is_](https://stackoverflow.com/questions/29750875/webrtc-change-video-resolution-in-the-middle-of-communication) for WebRTC, but that appears to be pretty non-standard / poorly-supported even in the browser context it's _meant_ for.

If you play one of the videos in the `ffplay` command-line player (FFmpeg), does it correctly follow the video resize events? If it _doesn't_ then there's no hope libopenshot would be able to support that. If it _does_, then support is theoretically **possible**, but it would have to be implemented because AFAIK _everything_ assumes a fixed size for the media that's determined on load.

The only thing I can think to suggest would be to split the stream into multiple files at the resolution changes, and import each one separately.

**Comment by yamass** [comment]
@ferdnyc Thanks for your quick reply! I can confirm that it works for ffplay.

```
ffplay --version
ffplay version 4.1.4-1build2 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
  configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
```

I've created two example videos featuring changing resolutions. One involving doubling the resolution, the other one rotating the device and therefore changing the aspect ratio/orientation/resolution of the video. Both work perfectly with ffplay.

[Archive.zip](https://github.com/OpenShot/libopenshot/files/3936124/Archive.zip)

Note that the rotating example makes openshot fail while reading. If you want, I can open a separate ticket for this.

```
Assertion abs(src_linesize) >= bytewidth failed at src/libavutil/imgutils.c:313
Caught signal 6 (SIGABRT)
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libc.so.6 ( abort                                     + 0x141 )  [0x7fcd155b8801]
  /usr/lib/x86_64-linux-gnu/libavutil.so.55 ( av_lfg_init                               + 0     )  [0x7fcd1247e107]
  /usr/lib/x86_64-linux-gnu/libavutil.so.55 (                                           + 0x2c806)  [0x7fcd1249b806]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.17 ( openshot::FFmpegReader::GetAVFrame()      + 0x48d )  [0x7fcd137e58f1]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.17 ( openshot::FFmpegReader::CheckFPS()        + 0x97  )  [0x7fcd137ef869]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.17 ( openshot::FFmpegReader::UpdateVideoInfo()  + 0x54f )  [0x7fcd137e37b7]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.17 ( openshot::FFmpegReader::Open()            + 0x6f5 )  [0x7fcd137e1db1]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.17 ( openshot::FFmpegReader::FFmpegReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)  + 0x422 )  [0x7fcd137e0dd4]
  /usr/lib/python3/dist-packages/_openshot.cpython-36m-x86_64-linux-gnu.so (                                           + 0xe4d4a)  [0x7fcd14218d4a]
  /usr/lib/python3/dist-packages/_openshot.cpython-36m-x86_64-linux-gnu.so (                                           + 0xe5296)  [0x7fcd14219296]
  python3                        ( PyCFunction_Call                          + 0x52  )  [0x567802]
  python3                        ( _PyEval_EvalFrameDefault                  + 0x55ae)  [0x51171e]
  python3                        (                                                   )  [0x508245]
  python3                        ( _PyFunction_FastCallDict                  + 0x2e2 )  [0x509642]
  python3                        (                                                   )  [0x595311]
  python3                        (                                                   )  [0x54a6ff]
  python3                        (                                                   )  [0x551b81]
  python3                        ( _PyObject_FastCallKeywords                + 0x19c )  [0x5aa6ec]
  python3                        (                                                   )  [0x50abb3]
  python3                        ( _PyEval_EvalFrameDefault                  + 0x449 )  [0x50c5b9]
  python3                        (                                                   )  [0x508245]
  python3                        ( PyEval_EvalCode                           + 0x23  )  [0x50b403]
  python3                        (                                                   )  [0x635222]
  python3                        ( PyRun_FileExFlags                         + 0x97  )  [0x6352d7]
  python3                        ( PyRun_SimpleFileExFlags                   + 0x17f )  [0x638a8f]
  python3                        ( Py_Main                                   + 0x591 )  [0x639631]
  python3                        ( main                                      + 0xe0  )  [0x4b0f40]
  /lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main                         + 0xe7  )  [0x7fcd15599b97]
  python3                        ( _start                                    + 0x2a  )  [0x5b2fda]
---- End of Stack Trace ----
```

Any ideas?

**Comment by yamass** [comment]
I managed to get my requirements met by preprocessing all videos using ffmpeg:

```
ffmpeg -i input-video.webm -vf "scale=800:600:force_original_aspect_ratio=decrease,pad=800:600:(ow-iw)/2:(oh-ih)/2:color=#EEEEEE" output-video.webm
```

See [here](https://superuser.com/a/1136305/1119536).

**Comment by ferdnyc** [comment]
An excellent solution, glad to hear you solved it! Yeah, the rotation crash is actually happening in FFmpeg's `libavutil`, but it's happening because we're requesting the wrong size frame image after the rotation. It's effectively the same problem as the resolution change, if the video dimensions change mid-stream we don't know how to handle that. (Typically with cell phone video rotation is exported as metadata, the video always has the _same_ (widescreen) dimensions even when it's portrait, it's just tagged with a rotation angle. 

If you had a perfectly square video stream that rotated mid-stream we'd probably handle it fine, but any change to the dimensions and it no longer fits the memory buffer we've allocated, so trying to load the first differently-sized frame causes a crash.

Tricky. The sample video will be immensely helpful, I'm sure (I'm on my phone right now), so thanks for that, and for the extremely informative report.

**Comment by chad3814** [comment]
I actually have a hack commit that fixes this in libopenshot, https://github.com/chad3814/libopenshot/commit/067e6dca2a90d88e208a30c5b10b9591d1d8802d but it could be made to not be a hack. We (Athenascope) need it because when someone is streaming to Twitch on mobile and they loose internet for a few seconds, twitch automatically switches their stream to a standby animation that is always in 1080p regardless of the resolution they were streaming in. So we get mp4s from ffmpeg that have multiple resolutions in them. I'm not sure if this is technically allowed, but like VLC plays them.

What I think the essential fix is, is not using `info.width` and `info.height` in the reader to set the `Frame` width and height, but instead use the `AVFrame` `width` and `height` which were just decoded. https://ffmpeg.org/doxygen/trunk/structAVFrame.html

**Comment by ferdnyc** [comment]
@chad3814 Huh! Interesting. Clever fix, and seems pretty straightforward... nice.

How does it affect the stream processing, does libopenshot's scaling adapt to the altered dimensions and fit the resized frame to the output profile?

**Comment by ferdnyc** [comment]
I also notice there's a context flag, [`AV_CODEC_FLAG_DROPCHANGED`](https://ffmpeg.org/doxygen/trunk/group__lavc__core.html#gab472a2f8b3c901d0c1bf398d512e9c26), that tells `avcodec_receive_frame()` to drop such frames on the floor. Which I suppose makes more sense than crashing, if you **are** working with fixed-size output buffers that can't handle mid-stream changes.

**Comment by chad3814** [comment]
> How does it affect the stream processing, does libopenshot's scaling adapt to the altered dimensions and fit the resized frame to the output profile?

Seems to work fine, though to be honest we've only used it for scaling down or the same. Eg source video is mixed 720p and 1080p, but our output is 720p. Like I said, it's a hack, which is why I didn't file a PR. I spent a couple days trying to do it correctly and gave up, maybe you'd have better luck. If you want I can provide a short clip that has this issue, in addition to @yamass' clips.
