### ISSUE TITLE
windows build instructions out of date ?

### ISSUE THREAD

**Issue by yvz5** [OpenShot/libopenshot#399]
hi there,

I was reading through the https://github.com/OpenShot/libopenshot/wiki/Windows-Build-Instructions and running all commands one by one. 

I have managed to compile the libopenshot and libopenshot-audio  packages, make and make install worked. 

Now the last step as describe in the docs is to run `make os-test` but cmake can not find that. so I tried other possible targets: `make os_test` did start but  threw an error:

```
Yavuz@YVZ-PC MINGW64 /e/openshot/libopenshot/build
$ make os_test
[  1%] Automatic MOC for target openshot
[  1%] Built target openshot_autogen
[ 78%] Built target openshot
[100%] Built target openshot-test
E:/openshot/libopenshot/build/tests/openshot-test.exe: error while loading shared libraries: libopenshot-audio.dll: cannot open shared object file: No such file or directory
make[3]: *** [tests/CMakeFiles/os_test.dir/build.make:57: tests/CMakeFiles/os_test] Error 127
make[2]: *** [CMakeFiles/Makefile2:570: tests/CMakeFiles/os_test.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:577: tests/CMakeFiles/os_test.dir/rule] Error 2
make: *** [Makefile:355: os_test] Error 2
```
I do have the system variable `LIBOPENSHOT_AUDIO_DIR=C:\msys64\usr` libopenshot could compile so the variable is correct I assume.

any ideas how to fix this ?

Furthermore, if I run make install, no dlls are installed under `C:\Program Files (x86)\openshot`. also the bindings are not installed.

I want to use the bindings in a python project.

**Comment by ferdnyc** [comment]
Ah, that's a typo. It should be `os_test`, or if you're using CMake 3.11+ you can even just type `make test`.

That info should've been in the output of the original `cmake` run, no?

```console
$ m CMakeCache.txt; cmake -DCMAKE_INSTALL_PREFIX=install-x64  ..
-----------------------------------------------------------------
          Welcome to the OpenShot Build System!

CMake will now check libopenshot's build dependencies and inform
you of any missing files or other issues.

For more information, please visit <http://www.openshot.org/>.
-----------------------------------------------------------------
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

Generating build files for OpenShot with CMake 3.16.1
  Building libopenshot (version 0.2.3)
  SO/API/ABI Version: 17

-- Found ImageMagick: /usr/lib64/libMagick++-7.Q16HDRI.so (found version "7.0.9-5") 
-- Found OpenShotAudio: /usr/lib64/libopenshot-audio.so (found suitable version "0.1.8", minimum required is "0.1.8") 
-- Could NOT find RESVG, using Qt SVG parsing instead (missing: RESVG_LIBRARY RESVG_INCLUDE_DIR) 
-- Looking for system JsonCpp
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Found jsoncpp: /usr/include  
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.54.100
-- Checking for module 'libavdevice'
--   Found libavdevice, version 58.8.100
-- Checking for module 'libavformat'
--   Found libavformat, version 58.29.100
-- Checking for module 'libavfilter'
--   Found libavfilter, version 7.57.100
-- Checking for module 'libavutil'
--   Found libavutil, version 56.31.100
-- Checking for module 'libpostproc'
--   Found libpostproc, version 55.5.100
-- Checking for module 'libswscale'
--   Found libswscale, version 5.5.100
-- Checking for module 'libswresample'
--   Found libswresample, version 3.5.100
-- Checking for module 'libavresample'
--   Found libavresample, version 4.0.0
-- Found FFmpeg: /usr/lib64/libavcodec.so;/usr/lib64/libavdevice.so;/usr/lib64/libavformat.so;/usr/lib64/libavutil.so;/usr/lib64/libswscale.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found ZeroMQ: /usr/lib64/libzmq.so  
-- Found SWIG: /usr/bin/swig (found suitable version "4.0.1", minimum required is "3.0") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.5", minimum required is "3") 
-- Found PythonLibs: /usr/lib64/libpython3.7m.so (found suitable version "3.7.5", minimum required is "3") 
PYTHON_MODULE_PATH: /home/ferd/rpmbuild/REPOS/libopenshot/build/install-x64/lib64/python3.7/site-packages
-- Found Ruby: /usr/bin/ruby (found version "2.6.5") 
-- Ruby executable: /usr/bin/ruby
-- Ruby vendor arch dir: /usr/lib64/ruby/vendor_ruby
-- Ruby include path: /usr/include;/usr/include
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.15") found components: doxygen dot 
-- Found DOXYFILE_IN: /home/ferd/rpmbuild/REPOS/libopenshot/Doxyfile.in  
-- Doxygen found, documentation target enabled

To compile documentation in doc/html, run: 'make doc'
-- Found UNITTEST++: /usr/lib64/libUnitTest++.so  
-- Could NOT find RESVG, using Qt SVG parsing instead (missing: RESVG_LIBRARY RESVG_INCLUDE_DIR) 
-- Tests enabled, test executable will be built as tests/openshot-test
-- Cmake 3.11+ detected, enabling 'test' target

To run unit tests, use: 'make os_test' or 'make test'
-- Displaying feature summary

Build configuration:
-- The following OPTIONAL packages have been found:

 * cppzmq
 * PythonInterp (required version >= 3)
 * PythonLibs (required version >= 3)
 * Ruby
 * Doxygen
 * PkgConfig
 * ImageMagick

-- The following REQUIRED packages have been found:

 * JsonCpp
 * Qt5Widgets
 * Qt5Core
 * Qt5Gui
 * Qt5Network (required version >= 5.12.5)
 * Qt5Multimedia
 * Qt5MultimediaWidgets
 * Qt5
 * FFmpeg
 * Threads
 * OpenMP
 * ZeroMQ
 * SWIG (required version >= 3.0)
 * UnitTest++
 * OpenShotAudio (required version >= 0.1.8)

-- The following features have been disabled:

 * IWYU (include-what-you-use), Scan all source files with 'iwyu'

-- The following OPTIONAL packages have not been found:

 * RESVG

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ferd/rpmbuild/REPOS/libopenshot/build

```

Oh, you know what... it _used_ to be right near the end, but after things got rearranged so that the FeatureSummary output is the last thing shown, it's a bit harder to spot.

Anyway, like I said, either `os_test` or `test` are the targets for running the unit tests. I'll update the wiki page to correct the typo. And maybe I can incorporate the target info into the FeatureSummary, so it's more visible.

**Comment by SuslikV** [comment]
The worst decision you can make it to use this library to your own project. This is port from Linux to Windows. Anyway the tests will not work without the Qt some dlls, some msys64 dlls (compiler one, for sure) and some luck.

**Comment by ferdnyc** [comment]
_libopenshot_ won't work without the Qt DLLs, either, so that's a pretty good test actually. (In fact I don't see how it could be *built* without the Qt DLLs.)

**Comment by SuslikV** [comment]
I'm a bit skeptic to these tests because last time I tried to run them - it was impossible for me to run preview window twice (one by one) after the first attempt something went wrong... each time. This was frustrating.

**Comment by ferdnyc** [comment]
OK, I've added PR #400 to include the test (and doc) target info in the CMake FeatureSummary output, where hopefully it's more visible. It'll automatically show the correct target name for the CMake version in use.

#### CMake 3.11+
```
-- Displaying feature summary

Build configuration:
-- The following features have been enabled:

 * Documentation, Build API documentation with 'make doc'
 * Testrunner, Run unit tests with 'make test'
 * Unit tests, Compile unit tests for library functions
```

#### CMake < 3.11
```
-- Displaying feature summary

Build configuration:
-- The following features have been enabled:

 * Documentation , Build API documentation with 'make doc'
 * Testrunner , Run unit tests with 'make os_test'
 * Unit tests , Compile unit tests for library functions
```

(Obviously, anything disabled would be listed in the disabled section instead.)

**Comment by ferdnyc** [comment]
@SuslikV 
> I'm a bit skeptic to these tests because last time I tried to run them - it was impossible for me to run preview window twice (one by one) after the first attempt something went wrong... each time. This was frustrating.

Hmm, you mean the `openshot-player` executable? Oh, yeah, I have no idea if that works correctly on Windows... or at all, really.

But the unit tests (`tests/openshot-test` executable in the build dir) are different, they don't run graphically, just do a bunch of programmatic operations to exercise (some of) the code paths in the library. They should be pretty reliable, IIRC all the builders (including Windows and Mac) run them after every compile.

The FFmpegWriter tests _do_ create output files in whatever's the current directory when you run them, so I suppose that theoretically could cause some issues with multiple runs. But normally it shouldn't, I've run them several times in a row with no problems.

(And the `src/openshot-example` program, that used to try to write to `/home/jonathan/` unless you changed the path in the code, which was a problem since it doesn't exist on 99.999% of systems. But at some point I fixed that, now it uses the current working directory for output as well.)

**Comment by yvz5** [comment]
But it doesnt install the dll files at all. If I dont skip the test step, will it install the bindings and dlls ?

**Comment by ferdnyc** [comment]
@yvz5 

Honestly, 'install' on Windows doesn't really work properly, at least not right from the CMake build. `make install` will install the built files inside whatever directory you specify as `CMAKE_INSTALL_PREFIX` in the build configs, generally on the builders we set a path under the build directory:
```command
$ mkdir build; cd build; cmake -DCMAKE_INSTALL_PREFIX=install-x64 ..
$ make
$ make install
```
Will leave you with the libopenshot DLLs in `install-x64/lib/`. But any other DLLs it needs (dependencies) won't be, since the library isn't useful by itself on Windows. When OpenShot is built for distribution, a script collects all of the required DLLs, along with the other application resources, and builds an InnoSetup installer package of the whole works. But if you're just building libopenshot, best bet is probably to manually copy the contents of `install-x64/lib/` (or wherever you specify) to wherever you need the DLLs.

**Comment by ferdnyc** [comment]
If you wanted to try it out, CMake does have an optional module that's intended to deal with this. It's _mostly_ for MSVC builds, as I understand, so I have no idea if it'd work when building with GCC in MSYS, but it can't hurt to try.

The module is [InstallRequiredSystemLibraries](https://cmake.org/cmake/help/v3.16/module/InstallRequiredSystemLibraries.html), and it can be added to `CMakeLists.txt` to add extra install rules.

The best place to add it is probably towards the end of `src/CMakeLists.txt`, since you'd want `${LIB_INSTALL_DIR}` defined first:

```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index b684aae..b25837d 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -434,6 +434,11 @@ INSTALL(DIRECTORY ${CMAKE_SOURCE_DIR}/include/
 		DESTINATION ${CMAKE_INSTALL_PREFIX}/include/libopenshot
 		FILES_MATCHING PATTERN "*.h")
 
+# Include required system DLLs in Windows builds
+set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION ${LIB_INSTALL_DIR})
+include(InstallRequiredSystemLibraries)
+
+
 ############### CPACK PACKAGING ##############
 IF(MINGW)
 	SET(CPACK_GENERATOR "NSIS")

```

(Or, without the diff markup):
```cmake
# Include required system DLLs in Windows builds
set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION ${LIB_INSTALL_DIR})
include(InstallRequiredSystemLibraries)
```

I have _no idea_ if it will do the right thing, or anything, but I'm certainly curious to find out. Let us know if you try it out, and what the results are.

**Comment by ferdnyc** [comment]
^ I've experimented some with the above, and AFAICT it has no effect whatsoever in the MSYS2/MinGW CMake. It may be exclusively meant for use when building CMake projects in Visual Studio. So, manually copying DLLs is still the way to go.

**Comment by timlash** [comment]
> 
> 
> But it doesnt install the dll files at all. If I dont skip the test step, will it install the bindings and dlls ?

@yvz5 

I assume this build is in relation to this question you posted sometime ago: https://github.com/OpenShot/openshot-qt/issues/1698

Did you get this to compile?  Have you achieved the CLI interface you described?

I'd be very interested in work along these lines, as I have the same automation goal.  I have a bunch of video, image and audio assets I want to feed parametrically into an editor to construct a timeline, and potentially start the render.  I started down the road with Blender, but it turned out way more complex than I needed.  Love to hear your status and help if I can.  Thanks.

**Comment by ferdnyc** [comment]
@timlash The libopenShot Python interface may be appropriate for that, or at least may be a reasonable building block for writing it. The major issue there would be that the libopenshot Python bindings have never really been usable in isolation under Windows, the way they are on Linux. Not necessarily that they _can't_ be, we've just never really tried it.

On Linux I can build libopenshot, then run `python3` with `PYTHONPATH=/path/to/build/src/binding/python` in the environment, and an `import openshot` automatically also imports `_openshot.so`, allowing me to use the full OpenShot API interactively from the Python REPL, even.

But that works because CMake links shared libraries directly to all of their dependencies, from the build tree, so they're directly executable for testing. (It then relinks everything on install.)

On Windows...
1. I don't know if `_openshot.pyd` (the Windows equivalent of `_openshot.so`) is usable from the build directory — perhaps if all of the other DLLs it needs are copied there as well. 
1. I don't know whether it's possible to install `openshot.py` and `_openshot.pyd` into a Windows Python installation (since our build uses MSYS Python) and use them that way. (Again, also presuming all of the other necessary DLLs are present, either in that directory or on the `PATH`.)

We've never made it to the point of packaging the Python bindings as a Python wheel or anything separately redistributable like that, mostly because of all the dependencies. The OpenShot application for Windows is built using cx_Freeze, which creates a launcher executable with a built-in Python runtime.

But getting a working Python install would probably be the quickest route to building what it sounds like you need. It _is_ awfully handy to be able to do things like this (again, on Linux...):
```python
$ cd /home/ferd/devel/libopenshot
$ PYTHONPATH=build/src/bindings/python python3
Python 3.8.5 (default, Aug 12 2020, 00:00:00) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openshot
>>> c = openshot.Clip("/var/tmp/testframes.mp4")
>>> r = c.Reader()
>>> r.DisplayInfo()
----------------------------
----- File Information -----
----------------------------
--> Has Video: true
--> Has Audio: false
--> Has Single Image: false
--> Duration: 3.00 Seconds
--> File Size: 0.11 MB
----------------------------
----- Video Attributes -----
----------------------------
--> Width: 1920
--> Height: 1080
--> Pixel Format: 14
--> Frames Per Second: 25.00 (25/1)
--> Video Bit Rate: 37 kb/s
--> Pixel Ratio: 1.00 (1/1)
--> Display Aspect Ratio: 1.78 (16/9)
--> Video Codec: h264
--> Video Length: 75 Frames
--> Video Stream Index: 0
--> Video Timebase: 0.00 (1/12800)
--> Interlaced: false
--> Interlaced: Top Field First: true
----------------------------
----- Audio Attributes -----
----------------------------
--> Audio Codec: 
--> Audio Bit Rate: 0 kb/s
--> Sample Rate: 0 Hz
--> # of Channels: 0
--> Channel Layout: 4
--> Audio Stream Index: -1
--> Audio Timebase: 1.00 (1/1)
----------------------------
--------- Metadata ---------
----------------------------
--> compatible_brands: isomiso2avc1mp41
--> encoder: Lavf57.71.100
--> handler_name: VideoHandler
--> language: und
--> major_brand: isom
--> minor_version: 512
>>> c.Open()
>>> f = c.GetFrame(1)
>>> f.Save("/tmp/frame1.png", 1.0)
>>> frames = [c.GetFrame(i) for i in range(2, 26)]
>>> [fr.Save("/tmp/frame{}.png".format(i), 1.0) for i, fr in enumerate(frames, start=2)]
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
>>> 
zsh: suspended  PYTHONPATH=build/src/bindings/python python3

$ ls /tmp/frame*.png
/tmp/frame10.png  /tmp/frame17.png  /tmp/frame23.png  /tmp/frame6.png
/tmp/frame11.png  /tmp/frame18.png  /tmp/frame24.png  /tmp/frame7.png
/tmp/frame12.png  /tmp/frame19.png  /tmp/frame25.png  /tmp/frame8.png
/tmp/frame13.png  /tmp/frame1.png   /tmp/frame2.png   /tmp/frame9.png
/tmp/frame14.png  /tmp/frame20.png  /tmp/frame3.png
/tmp/frame15.png  /tmp/frame21.png  /tmp/frame4.png
/tmp/frame16.png  /tmp/frame22.png  /tmp/frame5.png
```

**Comment by timlash** [comment]
@ferdnyc - Linux you say?  Bang!  You've hit the nail on the head for me.  Thanks for the advice!  This is exactly the direction I was hoping to go.  I'll transfer my development efforts to my linux box.  Already Googling up some sample Python code.  Any reference resources you'd recommend?  Thanks again for the tip.  What I've seen for Openshot so far, will offer me far more utility than what I encountered in Blender.  Blender is just so much more than I need.  This seems like the perfect tool for me.

**Comment by ferdnyc** [comment]
@timlash 

> Any reference resources you'd recommend? 

The official docs at Python.org are pretty good, both educational and reference. (The reference parts are also largely accessible via the `pydoc3` command installed with Python.)

Beyond that, fortunately Python is a _very_ hot topic on the stack exchange sites, as well as blogs and etc. in general. Which means that just googling for answers or examples is usually effective for just about anything you need to do. Its design has taken place in the open since inception, so you'll not- infrequently even end up at the original mailing list discussion or proposal (a PEP, or Python Enhancement Proposal, which is the process by which all language changes come into being) for the feature or syntax you're looking for info about.

> What I've seen for Openshot so far, will offer me far more utility than what I encountered in Blender.  Blender is just so much more than I need.  This seems like the perfect tool for me.

I hear you. Blender's Python api is impressively deep, but it's also impressively complex and "raw". You're basically automating the UI internals directly, which... isn't the most intuitive way to do a lot of things. (Though, in their defense, it does allow familiarity with the software to translate into familiarity with the API.)

libopenshot's Python bindings, for the most part, have NO UI at all. (That's all implemented in the OpenShot Python code, layered on top of libopenshot. The libopenshot UI consists of a few functions that dump data to the console, and a couple of "use Qt to open a window displaying this thing" calls that aren't even part of the API, they're purely debugging-oriented.) So, hopefully the actual API feels at least somewhat task-oriented, as that's the intent.

Not to say that it's perfect -- it isn't. For one thing, Depot what I just said it still suffers a bit from having OpenShot as its primary focus. Often, things will be implemented just enough to meet OpenShot's needs, and no farther. 

If you find holes in what you're able to do with libopenshot, and think there should be API calls that aren't there, feel free to open an issue at the OpenShot/libopenshot project. We're still growing the API. Just last week I added a set of lookups that, we all agreed, should've been there years ago. There are countless more places where that same thing could be done -- it's just that nobody has done it. Usually, nobody's even asked for it.

**Comment by timlash** [comment]
@ferdnyc - Thanks so much for the follow-up!  However, I wasn't seeking Python documentation.  The internet is littered with that.  I'm interested in any documentation for Openshot/libopenshot.  Doc that describes the object model, methods and properties.  If not, I'll just poke around with Python.  I just normally like to read-up a bit to familiarize myself with the overall structure to start.  Either way, I'm looking forward to diving in.

**Comment by ferdnyc** [comment]
@timlash Oh! Sorry about that.

The Python bindings are generated straight from the C++ API, so they don't have docs of their own. The libopenshot C++ API has Doxygen documentation that's buildable from the source tree using the 'doc' build target in CMake (only available if Doxygen is detected), and there's a copy generated from the current development source (may include changes not in the most recent release) at https://www.openshot.org/static/files/libopenshot/

**Comment by ferdnyc** [comment]
Basically, it translates from C++ to Python pretty directly. If the C++ is:
```c++
using namespace openshot;

Clip myclip1("/path/to/file.mp4");
myclip1.Open();
std::shared_ptr<Frame> frame1 = myclip1.GetFrame(1);
frame1.Save("/tmp/frame1.png", 1.0);  // (path, scale[, format="PNG", quality="100%"])
myclip1.Close();
```
then the Python is:
```Python
import openshot

myclip1 = openshot.Clip("/path/to/file.mp4")
myclip1.Open()
frame1 = myclip1.GetFrame(1)
frame1.Save("/tmp/frame1.png", 1.0)
myclip1.Close()
```

One wrinkle: all enum values are hoisted to the root of the library, so an `openshot::ChannelLayout` value of `LAYOUT_STEREO` is just `openshot.LAYOUT_STEREO`, `openshot::InterpolationType::LINEAR` is just `openshot.LINEAR`, etc. (So the contents of all enums have to be globally unique; no conflicts.)
