### ISSUE TITLE
Step by step usage

### ISSUE THREAD

**Issue by PeterAkakpo** [OpenShot/libopenshot#413]
is there any step by step guide on how to use the libopenshot library in a QT project.

I am getting  linker errors when i created a new project
these are the steps i took

1. i create a new QT c++ Application. 
2. updated the .pro  LIBS (path to libopenshot.dll.a and libopenshot-audio.dll.a) and 
INCLUDEPATH (libopenshot and libopenshot-audio include folders)

3. i added **#include "QtImageReader.h"**
4. Build the project

is there something i am not doing right?

![dialog](https://user-images.githubusercontent.com/7926382/72200249-1bab0c00-343f-11ea-8fe2-10c9ce5a5f85.png)
![Errors](https://user-images.githubusercontent.com/7926382/72200250-1c43a280-343f-11ea-9ad0-78bcca766f5a.png)
![project file](https://user-images.githubusercontent.com/7926382/72200251-1c43a280-343f-11ea-986f-4893bd67fb6d.png)

**Comment by ferdnyc** [comment]
@PeterAkakpo 

A step-by-step guide? No, sorry. In fact, I don't know if anyone has ever even tried that, and we don't really know if it would work. We don't currently support building libopenshot or anything using it with any compiler other than GCC or Clang; MSVC builds are completely untested.

It _**might**_ work, I'm not saying it doesn't — only that we have no knowledge of whether it's even possible or not, and can't really provide much in the way of guidance since you're pretty much blazing a trail there.

I can offer a few small observations that may or may not be any help:

1. The `OpenShot.h` header's sole purpose is to include all the _rest_ of the libopeshot headers, so if you're including that it should be all you need. Your `#include "QtImageReader.h"` is technically a double-include, since it was already pulled in by the previous `#include`. We have include guards in the headers, so there's no harm in doing it. It's just redundant.

1. To get an idea of how Qt code can use openshot, one place you can look is libopenshot's _own_ Qt code. The file [`src/Qt/PlayerDemo.cpp`](https://github.com/OpenShot/libopenshot/blob/develop/src/Qt/PlayerDemo.cpp) is a simple demonstration app which uses Qt and libopenshot to create a simple video player. The `src/Qt/demo/main.cpp` file wraps it into an executable, which gets compiled as `src/openshot-player.exe` in the libopenshot build tree. But it and its header (`include/Qt/PlayerDemo.h`) provide a simple, functioning example for how libopenshot can be used in Qt.
    
    Other files of interest:
    * `src/Qt/VideoRenderWidget.cpp` & `include/Qt/VideoRenderWidget.h`, a `QWidget` subclass that displays the video.
    * `src/Qt/VideoRenderer.cpp` and `src/Qt/VideoRenderer.h`, a `QObject` and `openshot::RenderBase` subclass which proxies frames from libopenshot to the VideoRenderWidget.
    * `src/Qt/PlayerPrivate.cpp` and `include/Qt/PlayerPrivate.h`, the central management thread that marshals the other thread classes for the player:
        * `src/Qt/VideoCacheThread.cpp` and `include/Qt/VideoCacheThread.h`
        * `src/Qt/VideoPlaybackThread.cpp` and `include/Qt/VideoPlaybackThread.h`
        * `src/Qt/AudioPlaybackThread.cpp` and `include/Qt/AudioPlaybackThread.h`

1. Looking at your screenshots, none of the messages have anything to do with the libopenshot files at all ­­— every one of the errors I can see references a standard library header file, presumably they're all part of the MSVC installation. It looks to me like Qt Creator isn't properly set up to compile with MSVC. Like I said, that's not something we've even tried (_either_ the Qt Creator part or the MSVC part), on Windows libopenshot gets compiled by automated scripts using MinGW `gcc`. But I'm pretty sure you'd be getting the same errors even without libopenshot.

    I'd recommend trying to build some of the Qt Creator sample projects, there are dozens to choose from. If Qt Creator can build those, then there might be an issue with how your project it set up... but make sure it's not just a general issue of Qt Creator interacting badly with MSVC, first.
