### ISSUE TITLE
What about AV1 ?

### ISSUE THREAD

**Issue by FrenchHope** [OpenShot/libopenshot#438]
Will Open Shot support AV1 encoding / decoding in a future update ?

**Comment by SuslikV** [comment]
Input - yes. Output - no.

**Comment by ferdnyc** [comment]
I believe @eisneinechse has been working on AV1 support some, it's not outside the realm of possibility, especially once [FFmpeg's AV1 encoding support](https://trac.ffmpeg.org/wiki/Encode/AV1) improves to where that page doesn't contain warnings like this:
> Note: AV1 encoding is very slow in comparison to VP9 or H.264, and considered experimental at this stage. Hence the use of `-strict experimental` (or the alias `-strict -2`) is necessary.

**Comment by eisneinechse** [comment]
@ferdnyc Kind of ;-)
Short version: I have a smallish patch to use AV1 encoders (plus decoders) but there are issues. Plus the main part is compiling a ffmpeg version with these codecs included (I have SVT-AV1, rav1e and libaom plus the dav1d decoder compiled in my ffmpeg).
For now VP9 may be a good replacement, it's far better than it's reputation.
Longer version: The issues are buggy encode (maybe a bug in the ffmpeg 4 part of libopenshort) and the use of options. The AV1 encoders have options that are quite different from what is used with h.264 in ffmpeg and the GUI is not ready for that. I hope that users, not just programmers, give some input how the advanced export dialog might be improved. But including AV1 is much easier to do than stuff that comes with it like HDR (10 bit and 12 bit) or the use of the GPU for image manipulation (I vote for Vulkan Compute as a way to get this done).
Libaom is included in all newer ffmpeg versions but it is the slowest. 
For now it might be the best option to use VP9. It is faster and it has support in hardware in consumer devices; I personally hope for a chromecast with AV1 support soon.
In addition to that I still some problems with the programs itself, like SVT-AV1 which uses up memory slowly but steadily since the huge patch on April 27 2019 when modes 0 to 5 are used (not in modes 6 and higher). I myself have a batch file which I use to re-encode clip to AV1 after it is exported. With SVT-AV1 in mode 5 or 6 I get speeds on a R5 3600 which are comparable to what I used to have 5 years ago with h.264 (the 3600 is twice as fast as my 1600 was!)
It will come! Maybe sooner than expected!
P.S. There is also SVT-VP9 which is very fast but does not get as much attention as SVT-AV1.

**Comment by ferdnyc** [comment]
Me, I need to at least get a GPU that at least supports hw-accelerated H.265 decoding. Because it's starting to get harder to find H.264-encoded anything out there... I mean, not _yet_, but the writing's on the wall. In 2 years nothing will still be using it.

**Comment by eisneinechse** [comment]
Agreed about h.264. On the other hand h.265 is a legal mine field. Now it's not just companies that protect their rights but also patent troll and unfortunately politics is now in it too and from being a BBF to becoming the public enemy #1 may just be one social media post apart. Using technology now that is under IP is almost a business suicide.
Decoding should be doable. May not be as dangerous.
I want to have videos with more than 8 bit colour depth. So that is VP9 and h.265 and later.
Also, it looks like I was right when I said that the problem with 4k and 60 fps might be the memory bandwidth. It is just to much data for most PCs to play without any problems. That are all problems that will be here soon, well they are already here. All the newer action cameras with 4k 60fps produce clips that are very memory intensive. And they are h.265. Plus they are (often) variable frame rate. All the things in this paragraph is something that is hard to get into OpenShot and should not be in the 2.x series but we should work towards it.
h.265 and other codec should be included now even if they cannot use all of their features. I agree. And using the hw decoder is fine too. There is no discussion about poor quality in the hw decoders. Unfortunately some of the features will not work until we implement these and that will be hard.
I personally want to get an action camera with HDR 10 support, this will allow me to see all of the problems these cameras produce for Openshot (4k resolution, 60 fps, VFR, more than 8 bit colour depth, ...). 
As for speed: I haven't looked at SVT-HEVC yet. Maybe that could help you for now even without hw support on the GPU; if it has a good encoder part. The SVT-xxx encoder scale really git with threat counts.
One last word about hw decoders: It would be nice if we could find an (easy) way to check what the installed hardware (GPU) supports.

**Comment by ferdnyc** [comment]
> One last word about hw decoders: It would be nice if we could find an (easy) way to check what the installed hardware (GPU) supports.

Mmm... well, I'm about 15 years on the other side of expecting anything with hardware to ever be "easy" anymore — hardware is where abstractions go to die, seems like doing **anything** ends up going in the opposite direction of common standards. Everything is its own special case.

(Though, that can be true of software as well. As you note in your first comment, and has always been true with FFmpeg, it feels like with each generation of codecs comes a new set of parameters for configuration, practically a whole new _model_ for how the encoding process is defined, so that the parameters used to configure one set of codecs bear little to no resemblance to the parameters used by their predecessors or successors.)

Still, in terms of hardware support, _interactively_ it's at least relatively simple to determine hardware **decoding** support. I mean, taking my own Nvidia GPU as an example, both `vdpauinfo` and `vainfo` can easily produce a list of what the card supports.

<details>
<summary>Full output of <code>vdpauinfo</code> for my GeForce GT710</summary>

```console
$ vdpauinfo
display: :1   screen: 0
API version: 1
Information string: NVIDIA VDPAU Driver Shared Library  440.59  Thu Jan 30 00:56:39 UTC 2020

Video surface:

name   width height types
-------------------------------------------
420     4096  4096  NV12 YV12 
422     4096  4096  UYVY YUYV 
444     4096  4096  NV24 YV24 

Decoder capabilities:

name                        level macbs width height
----------------------------------------------------
MPEG1                           0 65536  4032  4048
MPEG2_SIMPLE                    3 65536  4032  4048
MPEG2_MAIN                      3 65536  4032  4048
H264_BASELINE                  51 65536  4032  4080
H264_MAIN                      51 65536  4032  4080
H264_HIGH                      51 65536  4032  4080
VC1_SIMPLE                      1  8190  2048  2048
VC1_MAIN                        2  8190  2048  2048
VC1_ADVANCED                    4  8190  2048  2048
MPEG4_PART2_SP                  3  8192  2048  2048
MPEG4_PART2_ASP                 5  8192  2048  2048
DIVX4_QMOBILE                   0  8192  2048  2048
DIVX4_MOBILE                    0  8192  2048  2048
DIVX4_HOME_THEATER              0  8192  2048  2048
DIVX4_HD_1080P                  0  8192  2048  2048
DIVX5_QMOBILE                   0  8192  2048  2048
DIVX5_MOBILE                    0  8192  2048  2048
DIVX5_HOME_THEATER              0  8192  2048  2048
DIVX5_HD_1080P                  0  8192  2048  2048
H264_CONSTRAINED_BASELINE      51 65536  4032  4080
H264_EXTENDED                  51 65536  4032  4080
H264_PROGRESSIVE_HIGH          51 65536  4032  4080
H264_CONSTRAINED_HIGH          51 65536  4032  4080
H264_HIGH_444_PREDICTIVE       51 65536  4032  4080
VP9_PROFILE_0                  --- not supported ---
VP9_PROFILE_1                  --- not supported ---
VP9_PROFILE_2                  --- not supported ---
VP9_PROFILE_3                  --- not supported ---
HEVC_MAIN                      --- not supported ---
HEVC_MAIN_10                   --- not supported ---
HEVC_MAIN_STILL                --- not supported ---
HEVC_MAIN_12                   --- not supported ---
HEVC_MAIN_444                  --- not supported ---

Output surface:

name              width height nat types
----------------------------------------------------
B8G8R8A8         16384 16384    y  Y8U8V8A8 V8U8Y8A8 A4I4 I4A4 A8I8 I8A8 
R10G10B10A2      16384 16384    y  Y8U8V8A8 V8U8Y8A8 A4I4 I4A4 A8I8 I8A8 

Bitmap surface:

name              width height
------------------------------
B8G8R8A8         16384 16384
R8G8B8A8         16384 16384
R10G10B10A2      16384 16384
B10G10R10A2      16384 16384
A8               16384 16384

Video mixer:

feature name                    sup
------------------------------------
DEINTERLACE_TEMPORAL             y
DEINTERLACE_TEMPORAL_SPATIAL     y
INVERSE_TELECINE                 y
NOISE_REDUCTION                  y
SHARPNESS                        y
LUMA_KEY                         y
HIGH QUALITY SCALING - L1        y
HIGH QUALITY SCALING - L2        -
HIGH QUALITY SCALING - L3        -
HIGH QUALITY SCALING - L4        -
HIGH QUALITY SCALING - L5        -
HIGH QUALITY SCALING - L6        -
HIGH QUALITY SCALING - L7        -
HIGH QUALITY SCALING - L8        -
HIGH QUALITY SCALING - L9        -

parameter name                  sup      min      max
-----------------------------------------------------
VIDEO_SURFACE_WIDTH              y         1     4096
VIDEO_SURFACE_HEIGHT             y         1     4096
CHROMA_TYPE                      y  
LAYERS                           y         0        4

attribute name                  sup      min      max
-----------------------------------------------------
BACKGROUND_COLOR                 y  
CSC_MATRIX                       y  
NOISE_REDUCTION_LEVEL            y      0.00     1.00
SHARPNESS_LEVEL                  y     -1.00     1.00
LUMA_KEY_MIN_LUMA                y  
LUMA_KEY_MAX_LUMA                y  


```
</details>

<details>
<summary>Full output of <code>vainfo</code> for my GeForce GT710</summary>

```console
$ vainfo
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.6 (libva 2.6.0.pre1)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG4Simple            :	VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    :	VAEntrypointVLD
      <unknown profile>               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
```
</details>


(Very _different_ lists, it must be noted, indicating that support is a function of both the hardware capabilities and the path used to access those capabilities — an additional frustrating wrinkle.)

#### `vdpauinfo`
```
Decoder capabilities:

name                        level macbs width height
----------------------------------------------------
MPEG1                           0 65536  4032  4048
MPEG2_SIMPLE                    3 65536  4032  4048
MPEG2_MAIN                      3 65536  4032  4048
H264_BASELINE                  51 65536  4032  4080
H264_MAIN                      51 65536  4032  4080
H264_HIGH                      51 65536  4032  4080
VC1_SIMPLE                      1  8190  2048  2048
VC1_MAIN                        2  8190  2048  2048
VC1_ADVANCED                    4  8190  2048  2048
MPEG4_PART2_SP                  3  8192  2048  2048
MPEG4_PART2_ASP                 5  8192  2048  2048
DIVX4_QMOBILE                   0  8192  2048  2048
DIVX4_MOBILE                    0  8192  2048  2048
DIVX4_HOME_THEATER              0  8192  2048  2048
DIVX4_HD_1080P                  0  8192  2048  2048
DIVX5_QMOBILE                   0  8192  2048  2048
DIVX5_MOBILE                    0  8192  2048  2048
DIVX5_HOME_THEATER              0  8192  2048  2048
DIVX5_HD_1080P                  0  8192  2048  2048
H264_CONSTRAINED_BASELINE      51 65536  4032  4080
H264_EXTENDED                  51 65536  4032  4080
H264_PROGRESSIVE_HIGH          51 65536  4032  4080
H264_CONSTRAINED_HIGH          51 65536  4032  4080
H264_HIGH_444_PREDICTIVE       51 65536  4032  4080
VP9_PROFILE_0                  --- not supported ---
VP9_PROFILE_1                  --- not supported ---
VP9_PROFILE_2                  --- not supported ---
VP9_PROFILE_3                  --- not supported ---
HEVC_MAIN                      --- not supported ---
HEVC_MAIN_10                   --- not supported ---
HEVC_MAIN_STILL                --- not supported ---
HEVC_MAIN_12                   --- not supported ---
HEVC_MAIN_444                  --- not supported ---
```

### `vainfo`
```
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG4Simple            :	VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    :	VAEntrypointVLD
      <unknown profile>               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
```

I especially like the "unknown profile", on the VA-API side. SRSLY!?

But, of course, VDPAU is a decoding-only technology, and I'm only recently coming around to just how limited [FFmpeg's VA-API support](https://trac.ffmpeg.org/wiki/Hardware/VAAPI) is, period — for Nvidia they just punt and don't even discuss it, the AMD section of that page has a list of caveats and restrictions as long as your arm, and even the linked Intel QuickSync page dives right in by saying that yeah, VA-API _works_... but for encoding, Intel's (proprietary, natch) `libmfx` probably works **better**.

And for Nvidia, the big mystery is then NVENC / CUVID / whatever they're calling it this week, the only encoding method that **does** have a reputation for actually working — and for which they appear to provide no enduser-facing tools or information whatsoever.

All of which leaves us right back with Andrew Tenenbaum: "The nice thing about standards is, there's always so many to choose from." \*sigh\* :roll_eyes:

**Comment by eisneinechse** [comment]
I think I put it in the source that I would like to get these parts into a separate source file. The plus would be that it is much easier to see what is only for the part that is detecting what is possible with this decoder/encoder.
This is still one of the biggest problems, I simply cannot look at what all the hardware offers. Having this part in an extra file would make it easier for people to help out or start contributing without searching through the large FFmpegWriter and FFmpegReader sources.
As for the different approaches of different companies, that doesn't even stop there; we have different OSes too and naturally there had to be new ways implemented too.
The number of standard is not only ridiculous in IT. Just look at screws, bolts, and railway tracks.

**Comment by eisneinechse** [comment]
It would be nice to have a function that would return if a requested operation can be done in that hardware and if that is not possible have a test that basically goes like: encode/decode a pre-defined input and check a few points if they produced the expected result; if so that codec on that hardware works. That was Jonathans idea BTW.
It looks like Netflix is looking into using the picture version of AV1 to show preview pictures.
I would not concentrate only on AV1. The changes for AV1 can only be a starting point for more codecs ( like AV2 ;-) ). One of the common things of these new codecs is that the encoders have new settings  not just the bitrate (which might not even be the mostly used one) but like AV1 have modes (svtav1enc has encodermode 0 for the best and slowest way with godd and usable fast results with encodermode 5 or 6.
Right now me tests are all in encodermode 6 (when using SVT-AV1) because I have my memory slowly eaten up with 5 or better since the huge patch of SVT-AV1 of April 27 2019. I don't have a way to change the mode for now as that would need a change in the UI of Openshot.

**Comment by eisneinechse** [comment]
@ferdnyc Yub, I totally agree with you. It looks like in our days these companies think standards are only for the other ones!
A good start for ruining a company in the future, BTW.

**Comment by eisneinechse** [comment]
Actually if you have a version of Openshot that was compiled with a version of ffmpeg that has the AV1 support compiled in you should be able to export to AV1. But the option settings are not working without changes and after the export is almost done it stays at 100%; don't cancel, wait until the progress bar turns green.
@ferdnyc You might know which distribution already has a version of ffmpeg with av1 support.
To use av1 from aom enter the advanced settings in the export window and in the Video Settings set Video Format to webm and Video Codec to libaom-av1.
(With SVT-AV1 and/or rav1e compiled into ffmpeg the VideoCodec would be libsvt_av1 (underscore!!!) and/or librav1e)
But this is absolutely unusable until the options can be adjusted! Purely for fun, if you like waiting!

**Comment by eisneinechse** [comment]
@ferdnyc You could try and add a line in FFmpegReader.cpp, around line 222, where it says:
case AV_CODEC_ID_H264:
add a line
case AV_CODEC_ID_H265:
With luck you might be able to decode with hardware but don't do it in the main branch. This is the part where we have to find a way to get the information which decoders are supported on the installed GPU. IMHO this part will be big and should be in its own source file.
