### ISSUE TITLE
Precompiled dll/lib files

### ISSUE THREAD

**Issue by ggolda** [OpenShot/libopenshot#441]
Hey, is it possible to just include precompiled dll/lib files? If yes - where can I find them? Tried to search in releases and on website, but with no success. In case if I don't want to follow a build step.

Some libraries are distributed like that (e.g. glfw) and it makes it so much simpler just to try how it works 😄

**Comment by ferdnyc** [comment]
@ggolda Sorry, we don't make precompiled DLLs available, because libopenshot isn't a standalone library. It's dependent on a ton of other DLLs (various FFmpeg components, some Qt modules, ZeroMQ, etc, etc.) which would either have to be distributed with it (in binary form, which I imagine we're not even allowed to do, in some cases), or you'd have to have the exact corresponding versions installed on your system.

I mean, the glfw "64-bit Windows binaries" package actually contains a _separate_ set of binaries for MinGW and **each** of the Visual C++ releases it supports (VC2012, 2013, 2015, 2017, and 2019), because the DLL is linked with a different version of the runtime in each case. And that's just **ONE** dependency. We have dozens.

Of course, you can always download the OpenShot installer at https://openshot.org/download/, since the application bundle contains all of the DLLs necessary to use OpenShot (and therefore, by extension, the included `libopenshot.dll`).

**Comment by ggolda** [comment]
Thanks for response!

**Comment by ferdnyc** [comment]
> It's dependent on a ton of other DLLs [...] which would either have to be distributed with it (in binary form, which I imagine we're not even allowed to do, in some cases)

On further reflection, that parenthetical is obviously nonsense, given that we're doing exactly that for OpenShot itself.
