### ISSUE TITLE
MacOS build error

### ISSUE THREAD

**Issue by fitzmode** [OpenShot/libopenshot#464]
Running into build errors on Mac OS, not entirely sure what the problem might be.
Can provide any additonal details if required. Thanks.

MacOS Version 10.14.5
XCode Version 11.3.1

```
fitz:build fitzmode$ make
[  1%] Automatic MOC for target openshot
[  1%] Built target openshot_autogen
Scanning dependencies of target openshot
[  2%] Building CXX object src/CMakeFiles/openshot.dir/AudioBufferSource.cpp.o
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/dispatch/dispatch.h:63,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:17,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:60,
                 from /usr/local/include/libopenshot-audio/juce_core/system/juce_TargetPlatform.h:71,
                 from /usr/local/include/libopenshot-audio/juce_core/juce_core.h:65,
                 from /usr/local/include/libopenshot-audio/juce_audio_basics/juce_audio_basics.h:52,
                 from /usr/local/include/libopenshot-audio/JuceHeader.h:18,
                 from /Users/fitzmode/os/libopenshot/src/../include/AudioBufferSource.h:35,
                 from /Users/fitzmode/os/libopenshot/src/AudioBufferSource.cpp:31:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/dispatch/queue.h:926:3: error: 'dispatch_qos_class_t' has not been declared
  926 |   dispatch_qos_class_t qos_class, int relative_priority);
      |   ^~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/dispatch/queue.h:1109:1: error: 'dispatch_qos_class_t' does not name a type
 1109 | dispatch_qos_class_t
      | ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/openshot.dir/AudioBufferSource.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/openshot.dir/all] Error 2
make: *** [all] Error 2](url)
```

**Comment by ferdnyc** [comment]
Hey @fitzmode ... to be honest I'm not sure either, and as you can see the error is actually coming from one of the XCode header files (which we happen to `#include` indirectly, via `CoreFoundation.h`).

I'm not a Mac developer and in fact don't even have _access_ to a Mac, so I don't even know what the contents of that header file are. There's no `/usr/include/dispatch/` at all on Linux.

What I can say is that it's **very** strange that you'd hit this error building `libopenshot`, if you were previously able to build `libopenshot-audio` _without_ errors. You'd think it would have come up during the `libopenshot-audio` build.

That would seem to imply that something in the header files included by libopenshot (specifically, `AudioBufferSource.h`) is causing this error to occur. Yet, `AudioBufferSource.h` only contains two includes, which don't seem like they could possibly be at fault here:

https://github.com/OpenShot/libopenshot/blob/816118b6f62743142839b9a73631b7a9d7518a4e/include/AudioBufferSource.h#L34-L35

The first because it's a system header, the second because it's the result of that previous `libopenshot-audio` build process that _didn't_ result in the same error.

So, I'm kind of at a loss. As I said, I'm afraid MacOS building isn't my area, or even within my abilities.

We build the official `libopenshot-audio` and `libopenshot` releases for MacOS on system running a much older OS X release. (So old that it was still called OS X — and it's actually forced us to defer some recent updates to `libopenshot-audio`, because the JUCE library no longer supports the SDK it's using.) 

All of which is to say, it's certainly possible that the issue is some sort of incompatibility with the latest MacOS SDKs.

**Comment by ferdnyc** [comment]
> That would seem to imply that something in the header files included by libopenshot (specifically, `AudioBufferSource.h`) is causing this error to occur.

Actually, that's incorrect. It would imply _either_ that the contents of `AudioBufferSource.cpp` or its includes are causing the error, _or_ that something on the compiler command line is.

So, since it doesn't seem to be the headers, I'd suggest running the build with `make VERBOSE=1`, which will cause make to output the full command line for each of the build steps. Perhaps something there will help track this down.

**Comment by ferdnyc** [comment]
(You can also configure verbose builds as the default from the CMake command line, by adding `-DCMAKE_VERBOSE_MAKEFILE=1` to the command line when you generate the build environment using `cmake`. But for a one-time test, just telling make to run verbosely seems simplest.)

**Comment by fitzmode** [comment]
Managed to resolve this by reinstalling gcc.

**Comment by ferdnyc** [comment]
Great! I should mention that since #352, libopenshot _does_ now build with clang — on Linux, at least. I don't think anyone has tried it with XCode's Apple Clang, specifically. I'd be curious to hear whether that worked, in fact.

But glad to hear you got it working with GCC.
