### ISSUE TITLE
Pixelization = 1,0 does not pixelate at all

### ISSUE THREAD

**Issue by mkarg** [OpenShot/libopenshot#506]
**Describe the bug:**
The "Pixelization" values is not linear. It starts with 0,0 which means "no pixelization at all", through 0,9" which means "heavy pixelization", but ends with "1,0" which **does not pixelate at all** (i. e. 0,0 and 1,0 behave *the same*). This makes it hard to understand for the user, and hard to prevent failures in usage.

**Steps to reproduce the behavior:**
1. Use Pixelation effect
2. Set Pixelization = 1,0

**Expected behavior:**
Strongest possible pixelization

**System Details:**
- OpenShot Version 2.5.1-dev2
- Operating System Windows 10

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
N/A

**Comment by ferdnyc** [comment]
Not hard to see why this happens, looking at the code.
https://github.com/OpenShot/libopenshot/blob/15c3efb76be2a734bd3b73b6122048de85397959/src/effects/Pixelate.cpp#L70-L86

Guess that should've been
```c++
1.01 - std::min(fabs(pixelization.GetValue(frame_number)), 1.0);
```

**Comment by ferdnyc** [comment]
> The "Pixelization" values is not linear.

_That's_ a separate issue, and one that could really use correcting as well. The same thing was true in the old code, the effect really doesn't even **begin** to do anything visibly until you get to like 0.75.

The problem is actually that it's TOO linear (1.0 excepted) — it could really do with a curve function rather than the current constant-slope adjustment, since it defines what's essentially a size multiplier. Reducing the size of something by even 50-75% and then blowing it back up again doesn't result in what most people would really consider to be pixelization, it just makes your image look slightly crappier.
