### ISSUE TITLE
Intersection test of clip and timeline frame wrong; moves whole clip

### ISSUE THREAD

**Issue by musteresel** [OpenShot/libopenshot#544]
https://github.com/OpenShot/libopenshot/blob/8cc33b2e57496e7037ad4a4c64e9e56f72e16d77/src/Timeline.cpp#L909-L912

The way this test is done causes `Position` to be rounded to the next higher frame start.  In other words, `Position` of a clip can effectively only be a multiple of `1 / FPS`.

Demo:

~~~c++
#include "OpenShot.h"

using namespace openshot;

int main()
{
  FFmpegReader sin240_19sec("sin240_19sec.wav");
  FFmpegReader sin640_30sec("sin640_30sec.wav");
  sin240_19sec.Open();
  sin640_30sec.Open();
  Clip one(&sin240_19sec);
  one.Position(1.5);    // ############## 1.5 seconds, halfway into the frame
  Clip two(&sin640_30sec);
  Timeline timeline(640, 480, Fraction(1, 3), 44200, 1, LAYOUT_MONO);
  timeline.AddClip(&one);
  timeline.AddClip(&two);
  timeline.Open();
  timeline.GetFrame(1);
}
~~~

(the two files are audio only files with 44200Hz sample rate and 19s resp. 30s length, different sine waves generated with audacity, the actual content doesn't matter though).

Add the following after `bool does_clip_intersect = ...`:

~~~c++
				std::cout << "Intersection test: clip start: " << clip_start_position
						  << " frame_number: " << frame_number
						  << " intersect? " << does_clip_intersect
						  << " clip info duration: " << clip->Reader()->info.duration
						  << std::endl;
~~~

Output (for 4 timeline frames due to caching):

~~~
Intersection test: clip start: 1 frame_number: 1 intersect? 1 clip info duration: 30
Intersection test: clip start: 2 frame_number: 1 intersect? 0 clip info duration: 19
Intersection test: clip start: 1 frame_number: 2 intersect? 1 clip info duration: 30
Intersection test: clip start: 2 frame_number: 2 intersect? 1 clip info duration: 19
Intersection test: clip start: 1 frame_number: 3 intersect? 1 clip info duration: 30
Intersection test: clip start: 2 frame_number: 3 intersect? 1 clip info duration: 19
Intersection test: clip start: 1 frame_number: 4 intersect? 1 clip info duration: 30
Intersection test: clip start: 2 frame_number: 4 intersect? 1 clip info duration: 19

~~~

This shows clearly that for timeline frame 1 (timeline time 0s to 3s) it only uses a frame (frame 1) of the 30s long clip, and *not* of the 19s long clip, even though this clip should start at position 1.5s (thus during timeline frame 1).  This causes that whole clip being displaced 1.5s.

ASCII art for further explanation:

~~~

|---------|---------|--------- timeline frames
     |xxxx-----|---------|  frames of clip with 1.5s position
~~~

the first half of samples from that clip's first frame (the part marked with `x`) should be in the first timeline frame.

**Comment by ferdnyc** [comment]
> (the two files are audio only files with 44200Hz sample rate and 19s resp. 30s length, 

*44100. Still. (_...Every_ time!!! 😁 😉)

**Comment by ferdnyc** [comment]
> https://github.com/OpenShot/libopenshot/blob/8cc33b2e57496e7037ad4a4c64e9e56f72e16d77/src/Timeline.cpp#L909-L912
> 
> The way this test is done causes `Position` to be rounded to the next higher frame start.  In other words, `Position` of a clip can effectively only be a multiple of `1 / FPS`.

Which, you know, makes a lot of sense from a _video_ perspective, since you can't show an image for half of a frame. And in video terms, the second clip *doesn't* intersect the first for frame 1 -- its video image will not be visible until frame 2. 

(I've sort of always gone on the assumption that timeline positioning is best done in units of 1 frame's duration, since among other things keyframes can **only** be positioned at those intervals. So I wouldn't be surprised to hear that the code makes that same assumption.)

You have a point, though, that this breaks down for audio, which isn't limited to rendering data in frame-sized units. 

Still, though, I'm a bit reluctant to unequivocally declare this a bug. I don't doubt it's something we could handle better, but I'm not even 100% sure exactly what handling it "right" (or "perfectly") should look like. There are factors that potentially make a clip starting mid-frame a problem to support. For starters, while audio isn't processed exclusively in frame-sized chunks, Timeline data **is**, and FFmpeg encoder data **is**.  

Right now, the encoder checks `does_intersect` to determine what Frame objects it needs to incorporate data from, when sending composited Frames to the encoder. Right now, at frame 1 the answer will be yes for clip 1, no for clip 2.

If the answer becomes _yes_ for clip 2, then the audio encoder will need to at the very least:
1. Determine that the answer is actually still "no" for video, BUT "yes" for audio.
 1. Add some _offset padding_ to clip 2's audio data in frame 1, injecting silence for the portion of the frame where it doesn't provide any audio data, so that audio can be mixed down to frame 1.

Of course, obviously the whole clip shouldn't end up shifted out of position as a result of it being started intra-frame. But the way the frame processing works is, as I mentioned, very very frame-oriented. 

(Even the FrameMapper mostly just tweaks which input Frame, singular, is used when generating each output Frame. I can't say I'm familiar enough with the audio processing to know how it handles partials, last time I tried to read it my brain melted.)

**Comment by musteresel** [comment]
> *44100. Still. (...Every time!!! :grin: :wink:)

This is really hard to remember somehow ^^

> You have a point, though, that this breaks down for audio, which isn't limited to rendering data in frame-sized units.

Audio is handled in sample-sized units, thus it should (is) possible to handle audio with per-sample accuracy.

> I don't doubt it's something we could handle better, but I'm not even 100% sure exactly what handling it "right" (or "perfectly") should look like

When you want timeline frame X, then you know that it lasts from time `X / timeline_fps` to `(X + 1) / timeline_fps`.  Adjust these "timeline relative times" to "clip relative times" using the clip position and start. Now you know which frame(s) of the clip you need: from `start_time_clip_relative * clip_fps` to `end_time_clip_relative * clip_fps`. *If* the audio data for each frame is stored "perfectly" (spoiler: it isn't currently), then by getting these clip frames you also get all samples needed for that timeline frame.  You might need to drop some from the beginning (first clip frame starts "before" timeline frame), or the end (last clip frame ends "after" timeline frame) and apply offsets (first clip frame starts somewhere "within" the timeline frame).

All of this doesn't change the way video frames need to be handled in any way; but allows for exact audio positioning.  And IMO this is very important; consider making a stop motion movie from single frames; then you might have a fps of perhaps 1 or 2 frames per second but probably want your audio positioned at a much finer scale. (Yes, you can just increase fps and call it a day, but that's not really intuitive nor "efficient", no?)

During my search for the current audio issues with timeline I've written a demo code which does basically this; example image from it's visualization:
![demo-2](https://user-images.githubusercontent.com/912651/87482840-904f4500-c632-11ea-990a-1135884414e3.png)

(`SR` means sample rate, example shows how one timeline frame is file with audio from 3 clip frames, but the last sample of the last clip frame is dropped due to the clip end marker; this demo code requires the same sample rate for clips and timeline)
