### ISSUE TITLE
Cannot build openshot-player. 

### ISSUE THREAD

**Issue by meksor** [OpenShot/libopenshot#573]
Greetings!
After including libopenshot in my cmake project via:

```
ExternalProject_Add(libopenshot
  GIT_REPOSITORY "https://github.com/OpenShot/libopenshot"
  GIT_TAG "origin/develop"
  PREFIX ${CMAKE_BINARY_DIR}/libopenshot
  INSTALL_COMMAND ""
)
```
(I'm using the develop branch because of an ffmpeg incompatibility on tag "v0.2.5", as documented here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=967016)

...and trying to compile, I get the following linker error:

```
[...]
[ 22%] Performing build step for 'libopenshot'
[  1%] Automatic MOC for target openshot
[  1%] Built target openshot_autogen
[ 84%] Built target openshot
[ 85%] Linking CXX executable openshot-player
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::Image::columns() const'
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::Image::rows() const'
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::DrawableBase::DrawableBase()'
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::Geometry::height() const'
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::Geometry::width() const'
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::Image::draw(std::vector<Magick::Drawable, std::allocator<Magick::Drawable> > const&)'
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::Geometry::Geometry(unsigned long, unsigned long, long, long)'
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::Geometry::aspect(bool)'
/usr/bin/ld: libopenshot.so.0.2.5: undefined reference to `Magick::Image::alpha(bool)'
collect2: error: ld returned 1 exit status
make[5]: *** [src/CMakeFiles/openshot-player.dir/build.make:123: src/openshot-player] Error 1
make[4]: *** [CMakeFiles/Makefile2:258: src/CMakeFiles/openshot-player.dir/all] Error 2
make[3]: *** [Makefile:171: all] Error 2
make[2]: *** [CMakeFiles/libopenshot.dir/build.make:131: build/libopenshot/src/libopenshot-stamp/libopenshot-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/libopenshot.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

I saw an issue about incompatibility with imagemagick7, but as far as i could tell this should be fixed by now. 
Do I need to compile openshot-player when using libopenshot in my own project? If not: How can I disable the compilation of this executable?
I'm quite new to cmake especially and not well versed in the ways of C++, any help is appreciated.

cheers and thanks

**Comment by ferdnyc** [comment]
@meksor 

Heh, it's funny you should bring this up, because I had already been adding an option to CMake that can be used to disable ImageMagick. (Currently, it's always used if detected, even if that's not wanted.)

ImageMagick 7 support is indeed long since fixed, but my guess is that there's something in our CMake setup that interferes with being used as an ExternalProject. I can't promise that disabling ImageMagick will even fix that, but it should at least be a step closer. I'll open a PR for that change now, and merge it as soon as Travis passes it, since it's a relatively minor adjustment.

As I said, I don't know that disabling ImageMagick _alone_ will fix things. Disabling the _player_ build probably isn't worthwhile, since the only reason it wouldn't be able to link is if your libopenshot build was faulty. (There's no ImageMagick code in the player source, so the symbol issue must be internal to libopenshot itself.) So, while you _could_ avoid building the player by building only the "openshot" target, the player build is most likely finding real issues with the _library_ build — reason enough to keep it, I'd say.

Anyway, as I said I'll open that PR now, and it should be merged shortly, then we can go from there.

**Comment by ferdnyc** [comment]
OK, that's now merged, so you can pass `-DENABLE_MAGICK:BOOL=0` on the CMake command line (or in `CMAKE_ARGS`, when using ExternalProject) to explicitly disable any attempts to incorporate ImageMagick into the libopenshot build.

**Comment by ferdnyc** [comment]
(If you're only planning to use libopenshot as a C++ shared library, I'd also suggest `-DENABLE_RUBY:BOOL=0` and `-DENABLE_PYTHON:BOOL=0`, since there's no reason you need to waste time compiling bindings for languages you're not going to use.)

**Comment by meksor** [comment]
Awesome! Your code builds fine now!
My project still fails to compile (no doubt because of my own incompetence). 
If you immediately see a mistake I'd be very thankful, if not: don't bother, ill figure it out.
CMakeLists.txt: 
```
cmake_minimum_required(VERSION 3.18)

project(Mechanizm)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_BINARY_DIR ./build)

include(CheckIncludeFile)
include(CheckIncludeFileCXX)
include(CheckIncludeFiles)
include(ExternalProject)

add_subdirectory(src)

ExternalProject_Add(libopenshot-audio
  GIT_REPOSITORY "https://github.com/OpenShot/libopenshot-audio"
  GIT_TAG "origin/develop"
  PREFIX ${CMAKE_BINARY_DIR}/libopenshot-audio
  INSTALL_COMMAND ""
)

ExternalProject_Add(libopenshot
  GIT_REPOSITORY "https://github.com/OpenShot/libopenshot"
  GIT_TAG "origin/develop"
  PREFIX ${CMAKE_BINARY_DIR}/libopenshot
  INSTALL_COMMAND ""
  CMAKE_CACHE_ARGS
    -DENABLE_MAGICK:BOOL=0
    -DENABLE_RUBY:BOOL=0
    -DENABLE_PYTHON:BOOL=0
)
```

**Comment by ferdnyc** [comment]
@meksor 

Hmm. I'd probably need to see the rest of the files, as well — is the code you've got so far part of a GitHub repo? (Or any other public repo.)

One possible issue, I _thought_ CMake descended into an `add_subdirectory()` dir as soon as it's encountered, _before_ processing the rest of the parent `CMakeLists.txt` — which could means the `ExternalProject`s won't have run yet. I'm a bit surprised that works, if you're using the `openshot` or `openshot-audio` targets in your `src/CMakeLists.txt`... though I assume if there were a problem there, you'd be getting CMake errors about it rather than compile errors, so I'm probably wrong.

Because our CMake configuration is still **really** lacking in polish and niceties, it doesn't `EXPORT` any targets, and in fact still uses things like `include_directories()` and `add_definitions()` at the directory level, where they won't be available to your own code. IOW, it's almost aggressively _un_-friendly to anyone trying to use it in their own code, unfortunately.

Or at least, it _has_ been in the past... now that I look, almost all of that seems to finally be gone. (I actually hadn't realized I'd made that much headway on my modernization effort.) ImageMagick's configs are one of the only remaining instances, which explains why having it enabled was breaking things. The other instance is libopenshot-audio, but hopefully since you're also importing that as an `ExternalProject` you'll have whatever you need from there. (Of course, `libopenshot-audio` doesn't `EXPORT` any configs either... sigh...)

Feel free to post your build output, though — I'd suggest running with `--verbose` (or adding `-DCMAKE_VERBOSE_MAKEFILE:BOOL=1` to the `cmake` command), since seeing how the compile commands are generated can often reveal a missing include path or something of that nature, which is often the source of build errors.

Other than that, I'd _suggest_ **not** setting `CMAKE_BINARY_DIR` in your `CMakeLists.txt` file, only because it's the kind of thing that's really useful to be able to set on the command line at configure time. Especially if you ever want to have _multiple_ build dirs with different configs. (I often have 3 or 4 going at once, myself. But it's not any kind of problem to do it, certainly not one that would cause build failures AFAIK.

Setting it is just a matter of adding a <code>-B <var>dir</var></code> to the `cmake` command line, though.

The way I usually run builds these days is,
```sh
cd /path/to/project/repo
cmake -B build -S . -DCMAKE_INSTALL_PREFIX=wherever \
      -DCMAKE_BUILD_TYPE=Release -DANY_OPTIONS=...
cmake --build build [--verbose]
cmake --build build --target test
cmake --install build [--verbose]
```

...But if I'm testing some other configuration, `build` might become `build_debug` or `build_valgrind` or etc.

**Comment by meksor** [comment]
I think I managed to include both libopenshot and libopenshot-audio now.
Your tipps where very helpful and I will incorporate them as soon as I get the first version to compile (not setting CMAKE_BINARY_DIR seems like a good idea for example). 
Ǹow the compiler has trouble finding the JUCE dependencies:

```
[...]
[ 88%] Built target libopenshot-audio
Scanning dependencies of target mechanizm
[ 94%] Building CXX object src/CMakeFiles/mechanizm.dir/main.cpp.o
In file included from /media/data/Projects/механизм/./build/libopenshot/src/libopenshot/include/AudioBufferSource.h:35,
                 from /media/data/Projects/механизм/./build/libopenshot/src/libopenshot/include/OpenShot.h:102,
                 from /media/data/Projects/механизм/src/main.cpp:1:
/media/data/Projects/механизм/./build/libopenshot-audio/src/libopenshot-audio-build/include/JuceHeader.h:18:10: fatal error: juce_audio_basics/juce_audio_basics.h: No such file or directory
   18 | #include <juce_audio_basics/juce_audio_basics.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/mechanizm.dir/build.make:82: src/CMakeFiles/mechanizm.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:171: src/CMakeFiles/mechanizm.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```
I tried this:
`target_include_directories(mechanizm PUBLIC ${CMAKE_BINARY_DIR}/libopenshot-audio/src/libopenshot-audio-build/JuceLibraryCode/modules)`
But it does not seem to work. 

The repo can be found here: https://github.com/meksor/mechanizm/tree/master
(it is still very minimal and basically just your example code)

I also don't think it would even link correctly (or: at all), but I'll cross that bridge when I get the includes working.

Also (completely off topic), because you mentioned valgrind:
Do you know these gcc flags? They are what I use instead of valgrind since (as far as i can tell) they are a lot faster during execution:
```
asan: CXXFLAGS += -g3 -O0 -rdynamic -fno-omit-frame-pointer -fsanitize=address
asan: LDFLAGS += -Wl,--export-dynamic -fsanitize=address -lbfd -ldw
```
(Makefile excerpt)

**Comment by meksor** [comment]
Alright, I did it! Took 6 days, but my program finally builds!
If anyone is interested, here is my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.18)

project(Mechanizm)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)
# set(CMAKE_BINARY_DIR ./build)

set(CMAKE_AUTOMOC ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)

include(CheckIncludeFile)
include(CheckIncludeFileCXX)
include(CheckIncludeFiles)
include(ExternalProject)

find_package(Qt5Widgets REQUIRED)

ExternalProject_Add(libopenshot-audio-dl
  GIT_REPOSITORY "https://github.com/OpenShot/libopenshot-audio"
  GIT_TAG "origin/develop"
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/third
  CMAKE_CACHE_ARGS
    -DCMAKE_INSTALL_PREFIX:STRING=${CMAKE_CURRENT_BINARY_DIR}/third
)

SET(OSA_INCLUDE_DIR ${CMAKE_CURRENT_BINARY_DIR}/third/include/libopenshot-audio/)
SET(OSA_LIB_DIR ${CMAKE_CURRENT_BINARY_DIR}/third/lib)

ExternalProject_Add(libopenshot-dl
  GIT_REPOSITORY "https://github.com/OpenShot/libopenshot"
  GIT_TAG "origin/develop"
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/third
  CMAKE_CACHE_ARGS
    -DENABLE_MAGICK:BOOL=0
    -DENABLE_RUBY:BOOL=0
    -DENABLE_PYTHON:BOOL=0
    -DCMAKE_INSTALL_PREFIX:STRING=${CMAKE_CURRENT_BINARY_DIR}/third
)

SET(OS_INCLUDE_DIR ${CMAKE_CURRENT_BINARY_DIR}/third/include/libopenshot/)
SET(OS_LIB_DIR ${CMAKE_CURRENT_BINARY_DIR}/third/lib)

add_library(libopenshot-audio SHARED IMPORTED)
set_target_properties(libopenshot-audio PROPERTIES IMPORTED_LOCATION ${OSA_LIB_DIR}/libopenshot-audio.so)
include_directories(${OSA_INCLUDE_DIR})
link_directories(${OSA_LIB_DIR})

add_library(libopenshot SHARED IMPORTED)
set_target_properties(libopenshot PROPERTIES IMPORTED_LOCATION ${OS_LIB_DIR}/libopenshot.so)
include_directories(${OS_INCLUDE_DIR})
link_directories(${OS_LIB_DIR})

add_subdirectory(src)

target_link_libraries(mechanizm libopenshot)
add_dependencies(mechanizm libopenshot-dl)

target_link_libraries(mechanizm libopenshot-audio)
add_dependencies(mechanizm libopenshot-audio-dl)

target_link_libraries(mechanizm Qt5::Widgets)
```
