### ISSUE TITLE
MTS files don't work in all the daily builds 

### ISSUE THREAD

**Issue by 01BartvR** [OpenShot/libopenshot#581]
**Question:**
MTS files don't work in daily builds (Open Shot 2.5.1) from september until now. I've tried several workarounds and they are succesful (converted to mp4 files) But that is a temporary solution.  A MTS-file doesn't work in a daily build. The program crashes.
There are a lot of Sony and Panasonic camera owners that use the mts format. I think that I am not the only one that encounters this problem.

**System Details:**
Open Shot 2.5.1
- Operating System Windows 10 home

**Comment by jonoomph** [comment]
I tested the file this morning, and it appears that we read in the first 8 video packets successfully (i.e. thumbnail works in OpenShot), but something goes horribly wrong when we decode the first few audio packets... all the timestamps seem to start at frame 98, and thus, the first 98 video frames have no audio packets... which freezes up OpenShot while it tries to figure this out.

However, after a long pause, I am able to playback the video (with glitchy audio). I would suggest converting your MTS files into MP4 before editing... as a general work-around, it is a much nicer format for video editing. I will add this test file to my "queue" of broken videos, and try and find a better algorithm for mismatching audio timestamps.

**Comment by 01BartvR** [comment]
Thank you for the effort you made.  I used the workaround  in daily builds (MTS>MP4) for quite a while. Curiously mts files work fine in the original OpenShot 2.5.1 release. I hope you find a solution.

**Comment by ferdnyc** [comment]
@01BartvR That makes sense, yeah. The libopenshot audio processing is undergoing a fairly substantial rewrite from the 2.5.1 code (libopenshot 0.2.5), with the aim of addressing some longstanding reports of users experiencing audio artifacts in their output — things like clicking and popping at clip borders, other types of distortion, etc. 

Part of that effort entails some changes being made to the way libopenshot initially reads and stores audio data from the input files. You've discovered a file type that causes the new input processing code some headaches, it seems.

(So, thanks again. The time to find these things is now, _before_ the code is finished. Rather than have bug reports start flooding in after the next release.)

Hopefully this will be addressed before then. But as things stand, the Daily Build versions won't fully support TS files for at least some of the current development cycle.
