### ISSUE TITLE
No HW-ACCEL in App Image 

### ISSUE THREAD

**Issue by netzwanze** [OpenShot/libopenshot#605]
Hello,

first thanks for this program!

So now to the problem: if i will export the video -> Could not create hwdevice! The problem exist only in the App Image download of the site.

If i compile from source -> no problem. ( mint linux / ryzen5 3500U)

```
export:INFO (1551, 'Surround (5+1 Kanäle)')
      export:INFO (1599, 'Surround (7+1 Kanäle)')
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/square_pal_wide
      export:INFO AVI (h.264)
      export:INFO updateChannels
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/square_pal_wide
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/atsc_720p_30
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/atsc_720p_30
      export:INFO Low
      export:INFO None
      export:INFO MP4 (h.264)
      export:INFO None
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/square_pal_wide
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/square_pal_wide
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/atsc_720p_30
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/atsc_720p_30
      export:INFO Low
      export:INFO High
      export:INFO Valid framerate detected, sending to libopenshot: 30.0
      export:INFO MP4 (h.264 va)
      export:INFO None
      export:INFO None
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/square_pal_wide
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/square_pal_wide
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/atsc_720p_30
      export:INFO /tmp/.mount_ZtVfpA/usr/bin/profiles/atsc_720p_30
      export:INFO Low
      export:INFO High
      export:INFO Valid framerate detected, sending to libopenshot: 30.0
      export:INFO Export path: /mnt/Homevideos/Unbenanntes Projekt.mp4
project_data:INFO _set key: ['export_path'] values: /mnt/Homevideos add: False partial: False remove: False
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
 main_window:INFO updateStatusChanged


Encodiing Device Nr: 0
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[AVHWDeviceContext @ 0x279eac0] Failed to initialise VAAPI connection: -1 (unknown libva error).
      export:INFO Error type string: Could not create hwdevice
```

**Comment by ferdnyc** [comment]
@netzwanze Sorry for the late response, holidays and all.

You're correct, unfortunately hardware accel is intentionally disabled in the AppImage builds, as all it was useful for when we had it enabled was making OpenShot crash the moment you tried to activate it.

The problem is that AppImages are intentionally built to be as generic as possible, so that they'll work on any Linux system -- and that makes it basically impossible for them to access the system's gpu drivers, which are anything but generic. Every distribution uses different paths, different names, has different versions available...

Running on Linux, the best option for running OpenShot with HW accel turned on is to install from a distribution package, nearly all of them package OpenShot. And for Debian-based systems, since their own packaging tends to be frightfully out of date, there's an official PPA that's always caught up to the current release.

It's been on my to-do list for a long time now to at least hide the hardware accelerated settings and features in the AppImage UI, to avoid unnecessary confusion... but I still haven't gotten around to it. Sorry!
