### ISSUE TITLE
Video start_time not set to 0, black screen preview in QuickTime

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#644]
It seems that when rendering video, the very first frame is not written at start_time 0 but instead at 0.04 (at 25 fps, it skips one frame).

This might not seem like a big problem and I think most viewers/players get around this but QuickTime players (including iPhone) shows the first frame as black instead of the first frame of the video. I think this affects preview thumbnails on iPhones too.

QuickTime shows a black screen when the video loads:
![QT-player-black](https://user-images.githubusercontent.com/1064199/111067078-814cc980-8516-11eb-86a3-77de64e895a7.png)

To fix this I can run a simple ffmpeg command, which just copies the video but it resets the start_time setting to 0 and the preview/first frame displays correctly:

`ffmpeg -i original.mp4 -c copy fixed.mp4`

This is the expected result with the first frame used as a preview/poster image:
![QT-player-ok](https://user-images.githubusercontent.com/1064199/111067108-a6d9d300-8516-11eb-877d-718665f9baa5.png)

To recreate this issue:

Run the following code to render a video clip:

```
	Clip clip(new FFmpegReader("sample.mp4"));
	clip.Position(0.0);
	clip.Layer(1);
	clip.Start(0.0);
	clip.End(10);

	Timeline timeline(1280, 720, Fraction(25,1), 44100, 2, LAYOUT_STEREO);
	timeline.AddClip(&clip);
	timeline.Open();

	FFmpegWriter writer("original.mp4");
	writer.SetAudioOptions(true, "aac", 44100, 2, LAYOUT_STEREO, 128000);
	writer.SetVideoOptions(true, "libx264", Fraction(25, 1), 1280, 720, Fraction(1,1), false, false, 0);
	writer.PrepareStreams();
	writer.SetOption(VIDEO_STREAM, "crf", "23" );
	writer.WriteHeader();
	writer.Open();
	writer.WriteFrame(&timeline, 0, 10 * 25);

	writer.Close();
	timeline.Close();
```

Check the start_time using ffprobe:
`ffprobe -v error -select_streams v:0 -show_entries stream=start_time -of default=noprint_wrappers=1 original.mp4`

You should get a value:
`start_time=0.040000`

To fix it:
`ffmpeg -i original.mp4 -c copy fixed.mp4`

Check the start_time using ffprobe:
`ffprobe -v error -select_streams v:0 -show_entries stream=start_time -of default=noprint_wrappers=1 fixed.mp4`

You should get a value:
`start_time=0.000000`

You can compare in QuickTime too.

Is this something that can be fixed in libopenshot rather than afterwards using ffmpeg? Or is there a setting I'm missing that will force the first frame to be written at 0.00000. Is this a bug or a design choice? I think somewhere in the code it must be skipping frame 0 and starts at frame 1 (0.04 seconds at 25 fps).

Any feedback on this would be appreciated. If it's a bug we can probably dedicate some resources to fixing this.

**Comment by ferdnyc** [comment]
```c++
	writer.WriteFrame(&timeline, 0, 10 * 25);
```

That should be `writer.WriteFrame(&timeline, 1, 10*25);`, since OpenShot's frame numbers are 1-based, and WriteFrame works in frame numbers, not time positions. I suspect that may be the source of the issue, though it's arguably still a bug that it would accept a 0-based frame number and write a blank frame as a result.

**Comment by ferdnyc** [comment]
Interestingly, the loop in WriteFrame passes the `start` value straight through to `reader->GetFrame()`, which only _then_ corrects the frame number:

https://github.com/OpenShot/libopenshot/blob/9efa359283d74342198538d169122d48be05e779/src/FFmpegReader.cpp#L818-L827

There's also either a bug or a documentation bug in FFmpegWriter, since based on this loop:
https://github.com/OpenShot/libopenshot/blob/9efa359283d74342198538d169122d48be05e779/src/FFmpegWriter.cpp#L801-L812

The third argument to `WriteFrame` isn't a `length` but an `end_frame`. Otherwise, the loop should be:
```c++
for (int64_t number = start; number <= (start + length); number++) { 
```

**Comment by ferdnyc** [comment]
Still not super clear on why you're getting a blank first frame / offset, since it _seems_ like what should be happening is that the first frame ends up doubled (after the `0` frame request is adjusted to `1`, the first time, and then frame `1` is requested again for the following frame).

I suppose it could be that FFmpeg is detecting the duplicate frame, and applying some sort of mitigation that drops the first and shifts the start time to the time index of the second.

**Comment by ferdnyc** [comment]
Also, it seems incredibly dumb to me that the code would just forcibly _adjust_ an out-of-bounds frame number, then proceed as if nothing's wrong — rather than, say, throwing an exception. Hard to see how that's really doing anyone any favors.

There's even an exception defined _just for that purpose_:
https://github.com/OpenShot/libopenshot/blob/9efa359283d74342198538d169122d48be05e779/src/Exceptions.h#L284-L300

Currently `OutOfBoundsFrame` is only thrown at two places in the code:
1. In FrameMapper: https://github.com/OpenShot/libopenshot/blob/9efa359283d74342198538d169122d48be05e779/src/FrameMapper.cpp#L337-L340
2. In FFmpegReader(!??!): https://github.com/OpenShot/libopenshot/blob/9efa359283d74342198538d169122d48be05e779/src/FFmpegReader.cpp#L1249-L1252

...And I'm not even sure that second one is really a valid use of the `OutOfBoundsFrame` exception in particular.

**Comment by ferdnyc** [comment]
> ...And I'm not even sure that second one is really a valid use of the `OutOfBoundsFrame` exception in particular.

Actually, scratch that, I'm sure it's _not_. When built with any recent FFmpeg version, the `AV_ALLOCATE_FRAME()` macro just translates to a bare `av_frame_alloc()`. If it returns `nullptr` then the only reasonable exception to throw is `OutOfMemory`.

**Comment by jeffski** [comment]
Thanks @ferdnyc for your detailed analysis as always. I tried with:

`writer.WriteFrame(&timeline, 1, 10 * 25);`

But still got the same start_time of 0.040000

I also tried different start frame numbers, i.e.:

`writer.WriteFrame(&timeline, 10, 9 * 25);`

And still get the same start_time.

We're you able to recreate this issue?
