### ISSUE TITLE
MacOS: Linker error while using the libopenshot in QT project

### ISSUE THREAD

**Issue by jelazi** [OpenShot/libopenshot#735]
Hi, I am trying to use `libopenshot` in my project using Qt creator on macOS.

I successfully compiled both `libopenshot-audio` and `libopenshot` with `-DCMAKE_BUILD_TYPE="Debug"` (I coerced the libopenshot a little by manually setting `set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DDEBUG")` via `CMakeLists.txt` - otherwise it would complain about the JUCE library). However after I include everything in the Qt project, and the libraries are showing the linker throws JUCE error:

```
Undefined symbols for architecture x86_64:
  "juce::this_will_fail_to_link_if_some_of_your_compile_units_are_built_in_debug_mode::this_will_fail_to_link_if_some_of_your_compile_units_are_built_in_debug_mode()", referenced from:
      ___cxx_global_var_init in mainwindow.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried to add:
```
QMAKE_CFLAGS_DEBUG +="-DDEBUG"
QMAKE_CXXFLAGS_DEBUG +="-DDEBUG"
```
to project file as well as forcing it into build environment, but I still get the same error.

Could You provide any hint how to set the Qt project so it would work?

**Comment by ferdnyc** [comment]
@jelazi 
That's happening because your build of libopenshot-audio used different debug flags than your build of libopenshot. The JUCE framework (what's used for libopenshot-audio) has protections against that sort of thing.

What you need to do is go back and reconfigure your libopenshot-audio build using the same `-DCMAKE_BUILD_TYPE={Debug|RelWithDebInfo|Release|etc.}` option that you use when configuring the libopenshot build.

You shouldn't set `-DDEBUG` / `-DNDEBUG` flags manually, let CMake handle it via the `CMAKE_BUILD_TYPE` variable.

**Comment by ferdnyc** [comment]
Oh, sorry, it looks like you already did that — the other possibility is that your libopenshot-audio and libopenshot builds now don't match your _Qt_ build.

Unless you're linking with Qt libraries compiled in debug mode, you'll likely need to rebuild both libopenshot libraries as `-DCMAKE_BUILD_TYPE=Release` or `-DCMAKE_BUILD_TYPE=RelWithDebInfo` to link them all together.

**Comment by ferdnyc** [comment]
(RelWithDebInfo is a good, though oft-overlooked choice, and should get you debugging symbols without triggering JUCE's debug-build protections.)

**Comment by ferdnyc** [comment]
@jelazi 

One correction, regarding debug definitions — CMake doesn't automatically set `-DDEBUG` for debug builds (it does automatically set `-DNDEBUG` for all _non_-debug builds), so in libopenshot-audio we automatically add that to the `CMAKE_CXX_FLAGS_DEBUG` defaults. We should've been doing that in libopenshot as well, but weren't.

My PR #739 will be merged soon and that will be corrected, but you should make sure that (one-line) change is present in your libopenshot `CMakeLists.txt` if building with `-DCMAKE_BUILD_TYPE=Debug`.

**Comment by jelazi** [comment]
Hi, so ... 

I did try to rebuild it with the `RelWithDebInfo` for both the `libopenshot-audio` and `libopenshot`. In order to build `libopenshot` I however needed to set:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DNDEBUG")
```
Otherwise the compiler was complaining as usual about the JUICE NDEBUG/DEBUG stuff (I think it is the macOS related issue/behaviour).

All went well and the both libraries compiled. After I added them to the QProject it still shows the JUICE error even when I do the `Release` build which should set the `NDEBUG` flag.

Any other ideas where to look next?

PS. Just for sanity check, the actual build configurations:
```bash
#AUDIOLIB CONFIG
export CMAKE_EXTRA="-DCMAKE_OSX_DEPLOYMENT_TARGET=10.13
 -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++
 -DCMAKE_SHARED_LINKER_FLAGS=-stdlib=libc++"

cmake -B build -S ../../. -G "Unix Makefiles"
 -DCMAKE_BUILD_TYPE="RelWithDebInfomake"
 -DCMAKE_INSTALL_PREFIX="/Users/******/Workspace/Git/libopenshot-audio/build/debug/distro"
 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
 -DOpenShotAudio_ROOT="./audio/build" ${CMAKE_EXTRA}

#LIB CONFIG
cmake -G "Unix Makefiles" \
  ${CMAKE_EXTRA} \
  -DCMAKE_BUILD_TYPE="RelWithDebInfomake" \
  -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang  \
  -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt@5/5.15.2/     \
  -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Version/Current/include/python3.9/ \
  -DPYTHON_LIBRARY=/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Version/Current/lib/libpython3.9.dylib \
  -DPython_FRAMEWORKS=/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/
 -DENABLE_PYTHON=0 -DENABLE_RUBY=0             \
   ../
```

**Comment by ferdnyc** [comment]
@jelazi (I edited your comment just to wrap some of the longer lines so they're more easily digestible, no content changes.)

I'm far from an expert on macOS... ... ... well, _anything_, really, but for the purposes of this conversation I'm a relative novice at compiling and linking software for the platform, in fact I only recently (just last month) managed to add macOS to our list of CI platforms for libopenshot, and I've been leveraging that newly-acquired (if sadly non-interactive) access to a macOS build host to begin some experimentations of my own in #744.

But, ANYWAY... for the most part your command lines seem correct to me. I did want to check one thing, only because it appears the same way twice: You have the `CMAKE_BUILD_TYPE` listed as `"RelWithDebInfomake"` (twice), I assume that's a typo, yes? The actual name of the mode is just `"RelWithDebInfo"`. But I assume CMake would complain if you were giving it a mode that doesn't exist.
