### ISSUE TITLE
Is perspective still used?

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#759]
I can see that the perspective properties can be set, i.e. `perspective_c1_x` but I can't see where these are actually used. Are the perspective values used anywhere?

**Comment by ferdnyc** [comment]
Not really "still", AFAICT those values have _never_ actually been used since the Keyframes were added back in this 2012 commit: 2266a4ab7a3f88ec5deb655aca3ff6a8a4e69ca9 .

**Comment by ferdnyc** [comment]
(The list of commits that even _contain_ the string 'perspective' — in the **code** diffs — is... extremely brief. There are like 5 or 6, total, and most of them just by virtue of editing a comment adjacent to the data, or making changes to the JSON handling. They have never been involved in any of the rendering math in any way.)

**Comment by jeffski** [comment]
Thanks, didn't check the history. For some reason I presumed it had been removed in favour of `shear` but I think perspective would create a different visual effect.

**Comment by ferdnyc** [comment]
It would, and I'm not even sure the current perspective parameters are sufficient to define it.

The "perspective" parameters currently defined in `openshot::Clip` take the x/y values for four coordinates, presumably meant to represent deformations of the image bounding box. But true perspective isn't merely an issue of moving coordinates around on a 2D plane. Without a representation of the space in all THREE dimensions, the information isn't there to apply the correct math to all of the points **between**.

IOW, imagine taking a frame and moving the upper-left corner diagonally toward the bottom-right corner about 20% of the way. Is that corner jutting _out_ of the screen, or receding _into_ it? The scaling of the image inside that border will be different (and non-uniform) depending which of those answers is the right one, and without the information there's no way to KNOW which is correct — the position of the transformed corner point is the same regardless. But the answer will affect the position of all the other image pixels.

Corner deformations aren't the most efficient way to store perspective transformations anyway. I don't pretend to fully understand the math, but a 3x3 matrix is all that's required to perform any sort of 3D projection on a model in 3 dimensions. (Or in 2 dimensions, if we let the 2D image represent a flat plane with no thickness.) That 3x3 matrix is the same representation used internally to store the data of a [QTransform](https://doc.qt.io/qt-5.15/qtransform.html#basic-matrix-operations), which we're already using in `openshot::Clip` to perform the image transformations:

|      |      |      |
|:---:|:---:|:---:|
| _m11_ | _m12_ | _m13_ |
| _m21_ | _m22_ | _m23_ |
| _m31_ | _m32_ | _m33_ |

Most of those represent values we already have:

|                     |                     |       |
|:-------------------:|:-------------------:|:-----:|
|  _m11_<br>`scale_x` |  _m12_<br>`shear_y` | _m13_ |
|  _m21_<br>`shear_x` |  _m22_<br>`scale_y` | _m23_ |
| _m31_<br>`origin_x` | _m32_<br>`origin_y` | _m33_ |

The untransformed identity matrix is:

|   |   |   |
|:-:|:-:|:-:|
| 1 | 0 | 0 |
| 0 | 1 | 0 |
| 0 | 0 | 1 |

Everything short of perspective is an [Affine Transform](https://en.wikipedia.org/wiki/Affine_transformation#Representation), which can represent any simple 2D transform — uniform translation, scaling, reflection, and shearing. Rotation (around the center point) to an angle `θ` is performed by setting _m11_ and _m22_ to `cos(θ)`, _m21_ to `sin(θ)`, and _m12_ to `-sin(θ)`.

So all we need if we want add perspective to the mix are values for the third column. Qt's documentation says that _m31_ is the horizontal projection factor, _m32_ is the vertical projection factor, and _m33_  is the "division factor" (which I assume has something to do with that earlier ambiguity I mentioned, about whether the corner is receding into the screen or jutting out from it).

With three additional parameters: `projection_x`, `projection_y`, and `division`, we could store a `QTransform`'s complete matrix in the `openshot::Clip` keyframes, and have access to its full range of image transformations, including perspective.

Humans couldn't really be expected to set those values usefully "by hand", and I don't expect that modifying them along a linear curve would produce useful animation effects. The numbers need to be computed from outside representations that are more readily determined and animated. (The same way we store and animate Rotation as a separate parameter representing the θ value, because it will end up being applied to the matrix in a "cooked" form .)  So the raw values aren't necessarily useful _as keyframes_. But neither are the current coordinate values we don't use. We should get rid of those. (For one thing, they're _really_ cluttering up OpenShot project data.)

**Comment by ferdnyc** [comment]
Ohhh, I think I maybe know where that came from, now.

Inkscape has [a perspective Extension](http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Extensions-ModifyPath.html#Extensions-Perspective) that works by drawing a quadrilateral in 2D, and then it conforms your drawing to it. Here's the diagram from their documentation:

![](http://tavmjong.free.fr/INKSCAPE/MANUAL/images/EFFECTS/Effects_Perspective.png)

That relies on the user to _correctly_ project the outline they want to fill, though, and if they draw it wrong they get wonky perspective. I have to think there are better ways, using math in real 3D space, that we can achieve perspective using QTransform without having to resort to drawing misshapen rectangles using four corner points.

(Or if not QTransform, then perhaps [QMatrix4x4](https://doc.qt.io/qt-5/qmatrix4x4.html).) QTransform can be converted back and forth to QMatrix4x4, and the latter offers explicit operations like these:
```c++
QTransform tr();
auto mat4x4  = QMatrix4x4(tr);
mat4x4.perspective(float verticalAngle, float aspectRatio, float nearPlane, float farPlane);
mat4x4.ortho(float left, float right, float bottom, float top, float nearPlane, float farPlane);
tr = mat4x4.toTransform();
```
