### ISSUE TITLE
License of this project is not immediately obvious

### ISSUE THREAD

**Issue by JacksonChen666** [OpenShot/libopenshot#805]
This project is on GitHub (yes it is). There is no file called "LICENSE", but a folder called "LICENSES". GitHub didn't seem to pick up that folder, or what this project is licensed under, and isn't able to show what the project is licensed under in the sidebar.
While the license is declared in the README, some users might not scroll to the bottom of the README which can tell what the project is licensed under (in this case LGPL-v3.0-or-later), thus not being immediately obvious what this project (libopenshot) is licensed under.

This project: ![libopenshot repo homepage, sidebar without license section](https://user-images.githubusercontent.com/50755746/151176862-59ef28af-4c11-46d1-ad2c-85b09df5f534.png)

Example project with license file: ![return youtube dislike repo homepage, sidebar shows project licensed under GPL-v3.0](https://user-images.githubusercontent.com/50755746/151177023-2ed18b07-f899-4f46-8d06-9e2980a6e808.png)

**Comment by JacksonRG** [comment]
Good to know! I'll look into getting our license to display

**Comment by JacksonChen666** [comment]
@JacksonRG if you're not sure what to do, open github and create a new file called "LICENSE". the license picker should show up beside the file name, and you can pick the license. then commit the contents of the file and it should work.

**Comment by JacksonChen666** [comment]
any follow up on this?

**Comment by JacksonRG** [comment]
None currently, but we haven't forgotten, and it's on our todo list.

**Comment by jonoomph** [comment]
Apparently this used to be visible on our GitHub page, but we switched to use the `resuse` format (which I am actually not a big fan of yet), and apparently this removed our license from GitHub. @ferdnyc Any thoughts on how to fix this? Thx

**Comment by ferdnyc** [comment]
Whoops, sorry, just saw this.

Yeah, the problem is that "_the_ license" is at best a convenient fiction — the code _contained inside_ the repo isn't under a single license. It's under five:
```sh
$ reuse lint | grep Used
* Used licenses: BSD-3-Clause, CC-BY-3.0, CC0-1.0, LGPL-3.0-or-later, MIT
```
That's not even counting the dependencies.
* libopenshot-audio adds GPL-3.0-or-later, as does FFmpeg
* Qt adds LGPL-2.0, Apache-2.0, and FTL, in addition to also using BSD-3-Clause and MIT
* (and so on.)

The open-source ecosystem has largely matured to an understanding of licensing that accepts that inherent complexity, and presents license information accordingly. (Hence the [SPDX](https://en.wikipedia.org/wiki/Software_Package_Data_Exchange) standard license identifiers that `reuse` employs). GitHub, however, [hasn't gotten there  yet](https://softwareengineering.stackexchange.com/questions/304874/declaring-multiple-licences-in-a-github-project). This is known to be an issue, but their response [has largely been](https://github.com/licensee/licensee/issues/244) roughly, "We'd _like_ to do this better, eventually..." IOW, `¯\_(ツ)_/¯`

That being said, we can certainly do a better job in the README. It should probably explain, right at the start, what's covered under each of the licenses used in the project.

**Comment by JacksonChen666** [comment]
github is able to [detect multiple licenses](https://github.blog/changelog/2022-05-26-easily-discover-and-navigate-to-multiple-licenses-in-repositories/) (very recent) and [it works](https://github.com/JacksonChen666/multi-license-test/)

...not sure what's gonna be done about that in this repo though ¯\\\_(ツ)_/¯

**Comment by JacksonChen666** [comment]
still not complete

**Comment by JacksonChen666** [comment]
I only recently discovered what REUSE was, and I had incorporated that into one of my projects.
I've written in the LICENSE file roughly the following (actually it's extremely similar):

> This project is compliant with the REUSE specification (<link to spec>). Information defined in that format takes precedence over all other copyright notices/licenses.
>
> General rule of thumb:
> - Source code is under MIT
> - Content that's not source code is under CC-BY-4.0

Have the README point to the LICENSE file, and that's something helpful.
Maybe that could be a starting point?

GitHub will detect the license as "Unknown", but that's better than nothing.
