### ISSUE TITLE
Making OpenShot easier for newcomer developers

### ISSUE THREAD

**Issue by KeithCu** [OpenShot/libopenshot#83]
I've been watching your project, and it is very interesting, but appears to be moving slowly and not having too many outside contributors.

One of the reasons why is that contributing a new feature to your system (including the UI) requires knowledge in 3 domains: C++, Python, and Angular. Those are each huge. Imagine trying to find a writer that understood Spanish, Japanese, and Hindi. There are many millions of people who speak those languages, but not all three!

In fact, many people who use Python, don't like Javascript. Many people who use Javasript don't know Python. Many people who want to make videos don't know how to program C++.

Libopenshot is about 10K lines of code. I think it could be converted to Python / Numpy in a couple of weeks. That is a fast library, and there are other GPU and optimized Python libraries you could leverage. Porting to Python, and taking advantage of hardware would make Openshot faster and easier to contribute to. In my free time, I don't want to bother with C++. I'd be willing to help even though I don't know your codebase too much.

Once you've got a PyQT interface, putting Angular on top makes it more complicated. I'm sure it adds some features, but it raises the barrier to entry.

Can you consider this, and what Python libraries you could take advantage of if you restructured your code? Given the fact that you use ffmpeg and other tools to do the heavy lifting, it seems like you don't need to have much C/C++ to be very fast. Check out Mercurial as an example of a fast codebase with very little C/C++.

I took a look at this file, for example:
https://github.com/OpenShot/libopenshot/blob/master/src/TextReader.cpp

It seems like that could be converted to Python easily and be fast enough.

**Comment by KeithCu** [comment]
I also took a look at the FFMpeg writer:

https://github.com/OpenShot/libopenshot/blob/master/src/FFmpegWriter.cpp

That is definitely the sort of code that one would have to tweak to make ffmpeg use H.264 encoding with the Intel hardware (https://www.anandtech.com/show/9562/intels-skylake-gpu-analyzing-the-media-capabilities) That talks about Skylake, but everything in there is in the newer processors too, and older ones.

In Python, it would be much easier to try things without recompiling or anything. I don't have any C++ tools setup right now that let me step through code.

**Comment by KeithCu** [comment]
I found a program to do a mechanical port of C++ to Python:
https://github.com/pybee/seasnake

Unfortunately so far I can't get it to run. It complains about not finding LLVM even though it's installed and I setup the environment variables.

**Comment by KeithCu** [comment]
I found another program to do C++ to Python conversion:
https://github.com/andreikop/cpp2python

It actually does a pretty good job on TextReader.cpp. I can't upload .py files, so I put it in a zip[
[TextReader.zip](https://github.com/OpenShot/libopenshot/files/1976314/TextReader.zip)
](url)

**Comment by KeithCu** [comment]
I created a fork and did the port:
https://github.com/KeithCu/libopenshot I killed the include directory and the Json importer.
I haven't tried to get it to run, but it looks pretty reasonable.

**Comment by KeithCu** [comment]
I went and looked up the .c code for Mercurial again. Here's one of 3 C files:
https://www.mercurial-scm.org/repo/hg/file/default/mercurial/bdiff.c

It's a small amount of data-munging code with a very clear API, and code that basically they never needed to change.

**Comment by KeithCu** [comment]
I took at look at the Brightness effect and it goes through frame by frame, pixel by pixel:
https://github.com/KeithCu/libopenshot/blob/master/src/effects/Brightness.cpp.py

Just moving the inner loop to C or Cython would probably make it fast enough though.

Or, the code could be changed to leverage Pillow, ImageMagick, or other frameworks which have effects.

**Comment by peanutbutterandcrackers** [comment]
Hey there!

I see that you are interested in helping this project out.

It would be really nice to have you on board.

I am just a random guy who tries to do his bit in helping out others with the issues over at openshot-qt. It seems that you are really good with Python. I am not sure if this suggestion would be agreed upon by the devs. After all, OpenShot, even now, with it's C++ library, struggles greatly with speed and efficiency. However, would you like to help out over at openshot-qt? There are a few more devs who have been submitting PRs on a semi-regular basis now. And the project is slowly taking momentum. We need more talented programmers like you to help us out!

I hope to see your PRs soon. Maybe the library will be ported to Python, maybe it won't. But you can, with your knowledge, still help this project out!

[Here](https://gist.github.com/peanutbutterandcrackers/d9777079e428eb07dc0dd1351ac5d050) is a small, humble checklist of things that I made, about the things that need to be done in OpenShot. Perhaps you'd like to take a stab at a few?

**Comment by KeithCu** [comment]
Hi,

Thanks for the info!

It is true that plenty of C++ code suffers with speed. The problem is that people are so busy spending time getting it to work or fixing simple bugs, etc. that they don't have time to work on performance issues. That's why the Python-based Mercurial is faster than C++ Subversion. Python even has a nice perf analyzer built in.

There's plenty of ways to speed up Python, using Numpy or other high performance libraries like https://github.com/inducer/pyopencl, OpenCV, etc.: https://www.quora.com/What-is-the-best-image-processing-library-to-use-in-Python

In fact, by refactoring the code, leveraging optimized graphics libraries and the GPU, it is possible to be faster than the existing libopenshot. 

Thanks for that list of important issues. Good job keeping that to help prioritize. It's a shame there aren't more people to look into problems.

One idea that just occurred to me is that a move of libopenshot to Python could be done incrementally. For example, rather than fixing a bug in some C++ code, perhaps it could be ported to Python and the fix done in Openshot-Qt. The old C++ code could be ignored, and eventually removed.

I don't know the codebase very well. I'll try to look for a little bug like that and see what the devs think. One thing that is useful is to try to find out in which file or function the likely fix needs to go. If a developer can include the filename and function name then new people can be helpful faster.

**Comment by KeithCu** [comment]
BTW, I did some reading and in many cases, using the GPU might not be worthwhile because of the time it takes to shuffle things to and from GPU memory. However, there's a fork of Pillow that has some extra features for SIMD and AVX2 and runs much faster:
http://python-pillow.org/pillow-perf/  That link also lists some other libraries.

**Comment by peanutbutterandcrackers** [comment]
I shall try to get the attention of some of the developers I know, on this one. Let's see what they'd think about this. :)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Do you have comments, Cap'ain?
@N3WWN - Perhaps you have some comments regarding this one? o.O
@ferdnyc - Your constructive criticisms are always very interesting and well-informed. Perhaps you'd have some input here?

**Comment by jeffski** [comment]
Appreciate your enthusiasm and ideas @KeithCu.

My thoughts on this and a few things to consider:

- This library has been decoupled from the Qt GUI project so that it can be used in other applications. I am using this in my own C++ project and I am sure I am not the only one. If it is ported it to Python all these projects would be without a library - or we would just have to fork this project and maintain the C++ version or throw away our projects and port them to Python.

- If you port it to Python I think you would only make things easier for Python developers and harder for C++ developers. I agree Angular is a bit of a strange choice for the GUI but I'm not experienced in Qt to know how easy it would be to build the interface with that.

- I think it would be more valuable to look at how developers can optimise the performance of what is here already, I'm pretty sure whatever you can do in Python, you can do in C++ and a lot of the libraries are available for both languages - FFMpeg, ImageMagick, Qt, Juce I'm not sure about.

**Comment by jeffski** [comment]
On the topic of speed and performance I'm trying to work out the image handling and effects as I imagine that would be a bit of a bottleneck. I've read that GraphicsMagick can be much faster than ImageMagick and has a same/similar interface and features (Magick++).

Also I am trying to understand why QImage is being used instead of ImageMagick. It seems like effects need to be recreated pixel by pixel using the QImage where as a lot of these effects and a lot more are already available with ImageMagick. I'd imagine the developers of those projects would be concentrating on speed/performance too.

I'm guessing the choice of QImage is to be compatible with the interface? Could you use ImageMagick images up until the point where you need it in the interface and then just convert it?

**Comment by DylanC** [comment]
@KeithCu @peanutbutterandcrackers @jeffski - Overall, I do feel it makes sense about the barrier to entry being quite high. However, it probably doesn't make sense to start a big porting effort considering our limited resources at the moment. 

@jeffski - Makes sense about your comments on languages. We should be able to optimize what we have rather than starting over. 

On your recent comments of performance:

I use Graphicsmagick in my own project and it does seem faster. This may be a possibility for improving the performance. QImage is much more compatible with any Qt app and many Qt functions require a QImage as a param. In my own application I convert from QImage to Graphicsmagick and back to QImage for some of the effects. However, of course this causes a slight bit of a performance hit but its not all that bad.

**Comment by KeithCu** [comment]
Hi @jeffski and @DylanC,

It is great that there are external users of libopenshot. However, I doubt there will be very many because the library isn't well-known, very feature rich, fast, etc. There's a downside too because it creates a boundary right in the middle of a codebase that makes it harder to add new contributors and features.

It's too bad you have limited development resources. That's why a big priority should be making it easier for newcomers. I believe you aren't going to find many people who know Python, C++, and Angular.

It's true that more Python would make it a bit harder for C++ developers, but Python is becoming the language of data science, is more productive, and would make it easier for random people to contribute drive-by patches.

It's not a big porting effort for libopenshot. It's about 10,000 lines of code. I believe that's about the size of Linux 0.1. Someone who knew it fairly well could have it done in a few weeks especially with a tool that has done most of the typing:
https://github.com/KeithCu/libopenshot/blob/master/src/TextReader.cpp.py

I've not looked at the code till recently so it would take me longer.

BTW, there are optimizations in Python that aren't available in C++. I think Imagemagick starts another process, for example. Whereas if you use a Python library, it will just be in your address space. That's why it's even worth thinking about Python as you plan to optimize. Python is a great glue language.

**Comment by ferdnyc** [comment]
I'm currently at the ER because I fell off a ladder last night (I'll be fine, just hurt my back and can't sit down), which leaves me kind of light on access to resources but conversely means I have NOTHING but time. So, while I'd normally try to incorporate more explicit facts and research into responding to something like this, I'll have to leave that aside and just share my impressions/thoughts.

Angular is only used for the timeline, the entire rest of the interface is straight PyQT. And, in fact, Angular is only used specifically to DRAW the interface -- all of the code for managing GUI objects is PyQT, even objects on the timeline. That may be a bit unusual, but honestly it isn't a major, major concern because you can get very far working on the OpenShot code without ever having to touch the Angular portion.

The decoupling of libopenshot from the GUI, and the integration of C/C++ code into an application written in a higher-level language, is downright common. The reasons for doing it are almost always speed and reusability. That means the code has to be properly optimized, of course, but it's far from an unusual situation, nor is it necessarily a problematic one. If the separation of concerns is good, such a setup doesn't have to be a barrier to entry for developers either — in fact, it can attract MORE developers if others make use of the library, as they apparently do. Again, you can get very far coding OpenShot without having to ever touch the libopenshot code, if that's your thing.

Beware of "we rewrote our application in $LANGUAGE and it's so much faster and easier to maintain!" type stories. In my experience they are almost always red herrings, because the gains in efficiency and maintainability have NOTHING to do with the languages involved, and **everything** to do with the fact that the developers undertook a ground-up rewrite of their codebase, applying all of the lessons they'd learned along the way of working on the previous version, and avoiding the mistakes only discovered in hindsight. It also gives them a chance to apply lessons learned by watching other projects. 

That, in my humble opinion, is far more of the reason why Mercurial is faster than Subversion — because Subversion's code base is over 20 years old, and its design and operation are two decades out of date. The languages are _largely_ immaterial, in most cases, and similar results to those "language switch success" type stories could even be achieved rewriting a codebase in the SAME language, as long as it was done from the ground up, eliminating existing antipatterns and applying current best practices. The only advantage to switching languages is that it effectively **forces** you to ignore the old codebase, and makes it easier to avoid carrying old mistakes into the new code.

This is getting long and I'm writing on my phone, so I'll submit here and continue in Part 2 to follow.

**Comment by ferdnyc** [comment]
So, along the lines of what I said previously, _converting_ code from one language to another is almost always the worst mistake you can make. It means that you end up taking code that may or may not have been very good in one language, and you've turned it into code that's **guaranteed** to be a very, very poor example of code in it's new language, because its design and structure are based on the old language. Each programming language has its own strengths, patterns, efficiencies, and style, and lends itself to code designed — from the bottom up — in very different ways. (That's why straight-C coders write bad C++, because if you write C++ code like it's C code the syntax will technically be valid, but the code will be inelegant.) So since your converter can only translate your code, not redesign it, it will speak with a heavy accent of the old language. And the result will be a miserable chore to maintain, because it was written by a machine and will make little sense (conceptually) to anyone well-versed in the target language, with all sorts of weird decisions embedded in it from a combination of the source-language-based design and the rote machine conversion.

Now, on to OpenShot itself.

There are severe obstacles to new outside developers working on OpenShot, speaking _as_ one of those new outside developers. But they aren't the multiple languages used, or the separation of libopenshot from openshot-qt itself. They are:

1. How libopenshot (and libopenshot-audio) are integrated into the openshot-qt codebase. It's _fine_ from a build/release perspective, but for development it's the absolute pits, even on Linux. openshot-qt can be run from its development tree using `launch.py`, but I'll only use an **installed** `libopenshot` and `libopenshot-audio`. Which means that when there are API changes to the libraries, and openshot-qt incorporates them, it can no longer be run (even from the source tree) without _installing_ the updated libraries. I have a bug filed about this here, as we are currently in such a breakage: if you try to run openshot-qt from its git HEAD against the libopenshot-0.9 release it claims to be compatible with, it will not function correctly. This is not by any means an unsolvable problem, but IMHO the ability of new people to work on the code is severely impacted until it is solved.
1. Building OpenShot under Windows _**at all**_ is a Lovecraftian nightmare. The dependencies are nebulous and complicated, the resources for how to use them are years out of date, and the codebase itself doesn't even attempt to integrate with those dependencies, it just blindly assumes they're they're and functioning properly and compatible. I still have not succeeded in building OpenShot under Windows, and I've tried **really** hard. You can't write code if there's no way to test it.

**Comment by jeffski** [comment]
Would anyone be interested in joining an openshot developer Gitter group if it was created? To discuss topics like this and maybe help each other out with any coding issues.

**Comment by peanutbutterandcrackers** [comment]
There is a slack channel, @jeffski of OpenShot. If you are interested in joining, you could e-mail our BDFL, Mr. Thomas. :)

**Comment by KeithCu** [comment]
Hi! I decided to slowly plug away on this. I started by creating a new fork with all the latest changes, doing the mechanical port using the tool, and then trying to get modules to work. I started with the the Qt sample and then ZmqLogger. I'm not sure if the Zmq logging works yet, but it's getting closer and the file logging seems to be okay. https://github.com/KeithCu/libopenshot/blob/develop/src/ZmqLogger.py It's buffered for now.

**Comment by KeithCu** [comment]
Obviously this will take many days of work, but I'm next going to look at the FFmpegReader(). There is a Python library which can save some of the code.

**Comment by DylanC** [comment]
@KeithCu - Interested to see the progress on this. I will follow it even though I'm busy with my own non-Openshot stuff for a bit.

**Comment by KeithCu** [comment]
Most of the work is easy / mechanical. I don't know Qt, or this codebase etc. but I'm able to make fixes very quickly. There are some big questions about threading, etc. but getting it almost working shouldn't be too hard.

**Comment by KeithCu** [comment]
BTW, you can get a basic test going by going into the Qt/ directory and running "python main.py" It lets you choose a file but then crashes. I'm going to try to get that working with images / video.

Anyway, I'm not going to work on this too much since I don't think it's going to "succeed" , but it's good practice to get better at Python, and I can make tons of fixes per hour so it's fun. The cpp2python tool is a great first step, but leaves plenty of little changes to be working.

For now I'm removing the critical sections. With the Python GIL, it won't need it. However, if it calls out to ffmpeg, etc. for the heavy lifting, and if they all release the GIL, then you can effectively use multiple processors. It's possible to create multiple threads in Python without needing to worry about critical sections.

I may use it as a case study in the next version of my book. Given this code is mostly a wrapper on other tools, Python seems natural as the glue. It's hard to write reliable, high-performing, multi-threaded C++. To the extent it isn't wrapping other tools (like for effects), it should be.

**Comment by jonoomph** [comment]
@KeithCu, I agree with @ferdnyc above. I have actually been doing a bunch of documentation to make things easier for new contributors: https://github.com/OpenShot/libopenshot/wiki. I also have updated build instructions for Windows, Mac, and Linux... and step by step instructions on getting more involved as a developer in OpenShot. 

I'm very confused by your goal to remove the C++ dependencies of libopenshot and libopenshot-audio though, and hopefully I can save you the pain of that endeavor. I experimented originally with a Python-only video editing library, and the performance was so bad, that moving to C/C++ was an absolute necessity. Python is my very favorite language, but it is not designed to pixel push millions of pixels a second... never gonna happen.

Thus, I built a video editing library, wrapped in with SWIG to access it in Python, and kept the rest of OpenShot designed around Python. Qt is mostly used for performance also, as it it much easier to port to Windows and Mac (than GTK+), and has some amazingly fast graphic libraries for rendering images, scaling images, etc... Once again, Qt is built in C/C++ for speed, and then wrapped for other languages, such as PyQt. 

In the end, Python is awesome, but is just a terrible tool for building raw video editing functionality.

**Comment by KeithCu** [comment]
Hi Jon,

There is also Cython, Numpy, and other libraries which can do heavy lifting. I think Python would be fine for building raw video editing functionality when you consider all the libraries it has to build on (written in both Python and C++). 

Qt is built in C++ for legacy reasons. They've got millions of lines of code. libopenshot is about 10,000.

Compare the dividing line in libopenshot to Mercurial, which has about 3 modules of C, which they've almost never needed to change. I included a link to one file above. The general rule is that 10% of code takes 90% of the time, but here more than 10% was ported. The dividing line between openshot and libopenshot is too high up.

When I go through libopenshot, most of the code I see would be just fine in Python. For example, here is the naive port of TextReader.py: https://github.com/KeithCu/libopenshot/blob/develop/src/TextReader.py

It seems the Python version would be ok for perf, considering it is mostly calling into another library for the work. Several thousand lines of libopenshot can be removed since Python has a high-quality implementation.

The places I do see, like blur which would be slow as naively ported to Python (https://github.com/KeithCu/libopenshot/blob/develop/src/effects/Blur.cpp.py), could be replaced with an optimized external library like http://python-pillow.org/pillow-perf/, or Cython.

It would be interesting to study the performance issues you ran into and research any other ways to make things work well in Python / Cython. In the time it took to port, a lot of time could be spent optimizing the Python.

The fact that Python is your favorite language makes this example interesting. Not many people go from indoor plumbing back to outhouses.

In the name of performance, reliability, maintainability, ease of building, debugging, and contributing to was increased. Also, it is missing features that would be easier to leverage from Python.

**Comment by ferdnyc** [comment]
@KeithCU
> Qt is built in C++ for legacy reasons. They've got 5 million lines of code. libopenshot is about 10,000.

Well... I mean... sorry, but that's just false. Qt is _first and foremost_ a C++ library, it's written in C++ because its primary export is a set of C++ APIs. 

It's written in C++ — actually, a [greatly extended](https://wiki.qt.io/Language_Bindings#C.2B.2B_Development_with_Qt) form of C++ which they've developed — for the same reason that, for example, OpenSSL is written in C: BEcause it's much easier to create bindings for a higher-level language to call a library implemented in a lower-level language than to do the reverse.<sup>1</sup>

_Implementing_ Qt in something like Python or Ruby would make the export of bindings for other languages far more difficult, if not impossible, and the goal is not to exclude bindings for other languages but to facilitate them. Using C++ makes it possible for them to present [this list of Language Bindings](https://wiki.qt.io/Language_Bindings) on their wiki:
![image](https://user-images.githubusercontent.com/538020/54207193-1f34d600-44b0-11e9-9e6c-6aef65f817e6.png)

Granted, until fairly recently even Qt's own Python bindings were third-party development. It's only in the past year or two that they've adopted the former PySide2 project as the official [Qt for Python](https://www.qt.io/qt-for-python), over its competitor PyQt (which OpenShot uses). 

Prior to that, their first foray into higher-level language support was the QtQuick module and its [QML](https://wiki.qt.io/QML) language. From [About Qt](https://wiki.qt.io/About_Qt), QML is
> a declarative object description language that integrates Javascript for procedural programming. QtQuick provides the necessary modules for GUI development with QML. It is possible to write whole applications in QML only, but usually only the GUI is written in QML and the application's backend is implemented in C++ (see [Integrating QML and C++](https://doc.qt.io/qt-5/qtqml-cppintegration-topic.html)).

As that linked "Integrating..." document explains,
> QML applications often need to handle more advanced and performance-intensive tasks in C++.

As you can see from the bindings screenshot above, even Qt Quick has bindings available for several  languages beside QML, again because the module itself is _implemented_ in C++.

It's neither the expectation nor the goal that Qt's C++ codebase be eliminated, and in fact they had two chances to do exactly that if they'd so desired: Both Qt 4.0 and Qt 5.0 were major overhauls of the entire codebase. They were implemented in C++ not because of legacy baggage, but because the developers continue to consider it the right language for the task, and they continue to recommend that performance-critical portions of even native Qt applications be written in C++. You're free to disagree with their position.

None of this is directly relevant to OpenShot, of course.

#### Notes
1. OpenSSL has bindings available for practically every language ever created, possibly including Logo. The refrain of "this wouldn't happen if this was written in (insert high-level language du jour)" is inevitable every time a bug is found in OpenSSL, and while there may be instances where that's true, I often wonder how the people making those comments would propose to have their theoretical language-du-jour implementation support bindings for every language under the sun, on practically every OS ever released. (There's still a directory in the OpenSSL source with scripts to compile it [on frickin' VMS](https://github.com/openssl/openssl/tree/master/VMS). And it's still being maintained!) Presumably they wouldn't, and just don't care about implementation in any language other than their favorite, which makes their opinion worthless.
    Cross-language and -platform support represents a different sort of "legacy reasons", arguably. But a high-level language implementation generally locks you into supporting only that language and possibly some derivatives, and given that languages come and go, even today that's very often undesirable. (Rust appears to be an exception to this, as it can be compiled to standard ELF shared objects on Linux/macOS, and to DLLs on Windows. Then again, that's precisely because describing Rust as "high-level" is somewhat wishful thinking.)

**Comment by KeithCu** [comment]
The decision to write Qt in C++ dates back to 1991. OpenSSH started in 1999 and was created by some OpenBSD developers using existing code.

It is true that writing in C++ forces you to build bindings for other languages. However, I wonder how many people are building Qt apps using Rust, D, Haskell, OCaml, or Node.js. Meanwhile, people aren't really trying to add bindings to NumPy or PyTorch. Most people just use Python and are happy. Languages come and go, but Python has been the fastest growing language for the last few years. 

Openshot is primarily a GUI, bindings for other languages isn't an important feature. If you wanted to support talking to other apps, openshot could have a public API, perhaps in HTTP, which would be easily callable from any language. The API would likely be much smaller than complete C++ API developed here. It could also expose a public faster API, but callable only from Python initially. 

However, first there needs to be a great app before people will really care to talk to from code. I presume most of the current users care primarily about the UI. I don't think Qt and OpenSSL are good comparisons for Openshot. This app is supposed to be easy to use, have lots of effects and features, take full advantage of the hardware, be reliable, easy to improve, etc. The distraction of C++, and building bindings for multiple languages, has prevented the program from becoming amazing.

**Comment by jonoomph** [comment]
@KeithCu, as @ferdnyc mentioned, you are free to disagree with their position... and our position if you wish. OpenShot is primarily a video editing library, wrapped with Python bindings, with a simple Qt UI built to control it. Our Qt application does very little comparatively.

As your first major proof of concept, I suggest you manipulate a 1920x1080 image @ 30 FPS with Python and display it without Qt. Then, attempt to manipulate two 1920x1080 images @ 30 FPS and merge the 2 images (all channels: RGBA), and then display the resulting image without Qt. Then make it run on Windows, Linux, and Mac. Then let's reopen this ticket and celebrate your native Python image processing pipeline! In other words, I would love to see you demonstrate that Python could in fact handle this task. Without this proof of concept, I don't think many people are going to be willing to help you on this mission. Good luck!

**Comment by KeithCu** [comment]
I was working on the port because it is great practice to get better at Python and most of the changes after using cpp2python are mechanical so it goes very fast. You may already love Python, but I feel there's lots more for me to learn. 

There is tight coupling between libopenshot and the QT UI. If you wanted to add a new option for ffmpeg export, you'd probably want to change the UI too. I doubt the UI could be made to run on another library. These components are tied at the hip, but separated by language.

Thank you for giving me a proof of concept to build! It is a good task to get better at Python. I will research creating it. However, I'm confused as to why Qt isn't allowed? I could also investigate creating an ffmpeg filter graph.

Suppose this app just worked in filter graphs? That would get it out of the business of going pixel by pixel everywhere, and be faster. The key to performance is having the right abstraction. I'll bet Qt has filter graphs in all those millions of lines of code. I'm not sure which is better / faster between ffmpeg and Qt. Do you have advice on that?

**Comment by jonoomph** [comment]
I think a proof of concept would help illustrate your points better, that is all I meant to suggest. I'm confused by your question FFmpeg vs Qt... neither is better or faster than the other, since they do completely separate things.

**Comment by KeithCu** [comment]
Qt does many things, including image / video processing. ffmpeg can also do many kinds of video processing. It should be possible to use either Qt or ffmpeg to blend two videos, for example.

**Comment by ferdnyc** [comment]
It's been over four months now, I'm going to close this as abandoned. Feel free to reopen if there are any new developments.

**Comment by Kaoschuks** [comment]
I have written various projects before in c++ and even ported some to c# and javascript and c++ still maintained its speed (although that was like 2years ago) but in terms of ease of use this library is quite difficult to understand and use. i would love if the documentation was to focus on the library as a service in which one can easily use to build a on top of.
I am currently interested in using this library to build a hybrid using ionic cordova with the c++ library directly using https://www.npmjs.com/package/cordova-plugin-cpp-bridge but I have tried using this library but completely lost on how to even start.
Please I need help on this.

**Comment by ferdnyc** [comment]
@Kaoschuks I assume you've looked at the API docs, have you also taken a look at the example code in `src/examples`? For simple use the API is pretty user-friendly, you can build a software-only transcoder in about 20 lines of source.

It won't be the most performant thing in the world (and it shouldn't be ignored that libopenshot's primary focus is NOT on transcoding performance or operations performed entirely on the GPU — if that's your need it's probably the wrong choice), but it's a pretty straightforward API for frame-by-frame operations on composited video content.

If you have more specific questions I'd suggest opening a new issue with details of the problems you're having. This one is more about the internal structure of the codebase, not its public APIs for consumers of the library.

**Comment by ferdnyc** [comment]
Since SWIG version 3.0 (which we're now using) generating JavaScript bindings is apparently supported (though some users have reported difficulty getting even simple examples to work)

**Comment by ferdnyc** [comment]
Since SWIG version 3.0 (which we're now using), generating JavaScript bindings is apparently supported. (Though some StackOverflow users have reported difficulty getting even simple examples to work.) So, another possibility is adding JS bindings as a third supported language option. (Fourth, if you count C++ itself.)

I'd be up for participating in attempts to make that work and getting the changes committed to the repo.
