### ISSUE TITLE
[development]   win 10 build Document is too old ,  Can you provide the latest compilation tutorial video?

### ISSUE THREAD

**Issue by 625781186** [OpenShot/libopenshot#951]
![image](https://github.com/OpenShot/libopenshot/assets/30521429/cb56f956-0cbc-4374-a8ae-040d957e3641)

![image](https://github.com/OpenShot/libopenshot/assets/30521429/c9383ed8-3b78-4874-bb68-7ba3abdc7008)

![image](https://github.com/OpenShot/libopenshot/assets/30521429/1800b792-97e6-4a03-9346-9071efd8191f)

**Comment by jonoomph** [comment]
Windows development changes rapidly, mostly due to MSYS2 packages, which are always marching forward. I don't have a simple trick to fix this, and it will take substantial effort for someone to get all our builds working on the latest MSYS2 packages. I welcome any PR's that move us in this direction though.

For most development, we [recommend a Linux environment](https://github.com/OpenShot/openshot-qt/wiki/Become-a-Developer), since it is so simple to setup and get working. Eventually, I will be forced to upgrade our Windows build server, and will update the documentation and package support myself at that time... if someone else has not already completed it. But I don't have a firm schedule for this work yet.
