### ISSUE TITLE
Remove .cproject and .project files

### ISSUE THREAD

**Issue by jeffski** [OpenShot/libopenshot#97]
These files are environment and IDE specific and should be setup on a user by user basis - for example the .cproject file contains: `/home/jonathan/Blackmagic DeckLink SDK 9.5/Linux/include`. Please consider removing them as users will most likely want to have their own environment and IDE preferences.

**Comment by ferdnyc** [comment]
I... am of two minds about this.

For one, paths containing `/home/jonathan` are hardly confined to these dotfiles:
```console
$ find ./ -type f -print0 | xargs -0 -n100 grep 'home/jonathan'
./include/ImageWriter.h:	 * ImageWriter w("/home/jonathan/NewAnimation.gif");
./include/Profiles.h:	 * Profile p("/home/jonathan/dv_ntsc_wide"); // Load the DV NTSC Widt profile data.
./include/FFmpegWriter.h:	 * FFmpegWriter w("/home/jonathan/NewVideo.webm");
./include/FFmpegWriter.h:	 * FFmpegWriter w("/home/jonathan/NewVideo.webm");
./include/ChunkReader.h:	 * ChunkReader r("/home/jonathan/apps/chunks/chunk1/", FINAL); // Load highest quality version of this chunk file
./.cproject:									<listOptionValue builtIn="false" value="&quot;/home/jonathan/Blackmagic DeckLink SDK 9.5/Linux/include&quot;"/>
./.cproject:									<listOptionValue builtIn="false" value="&quot;/home/jonathan/Blackmagic DeckLink SDK 9.7/Linux/include&quot;"/>
./.cproject:									<listOptionValue builtIn="false" value="&quot;/home/jonathan/Blackmagic DeckLink SDK 9.5/Linux/include&quot;"/>
./.cproject:									<listOptionValue builtIn="false" value="&quot;/home/jonathan/Blackmagic DeckLink SDK 9.7/Linux/include&quot;"/>
./cmake/Modules/FindBlackMagic.cmake:			   		 "/home/jonathan/Blackmagic DeckLink SDK 10.3.1/Win/include/" )
./cmake/Modules/FindBlackMagic.cmake:					   		 "/home/jonathan/Blackmagic DeckLink SDK 10.3.1/Mac/include/" )
./cmake/Modules/FindBlackMagic.cmake:					   		 "/home/jonathan/Blackmagic DeckLink SDK 10.3.1/Linux/include/" )
./src/QtPlayer.cpp://	ZmqLogger::Instance()->Path("/home/jonathan/.openshot_qt/libopenshot.log");
./src/examples/OpenShot Wipe Tests.py:lower = openshot.ImageReader("/home/jonathan/apps/libopenshot/src/examples/back.png")
./src/examples/OpenShot Wipe Tests.py:higher = openshot.ImageReader("/home/jonathan/apps/libopenshot/src/examples/front3.png")
./src/examples/OpenShot Wipe Tests.py:e = openshot.Wipe("/home/jonathan/apps/libopenshot/src/examples/mask.png", brightness, contrast)
./src/examples/OpenShot Wipe Tests.py:e1 = openshot.Wipe("/home/jonathan/apps/libopenshot/src/examples/mask2.png", brightness, contrast)
./src/examples/ExampleBlackmagic.cpp:	ImageReader b1("/home/jonathan/Pictures/moon.jpg");
./src/examples/ExampleBlackmagic.cpp:	ImageReader b2("/home/jonathan/Pictures/trees.jpg");
./src/examples/ExampleBlackmagic.cpp:	ImageReader b3("/home/jonathan/Pictures/clouds.jpg");
./src/examples/ExampleBlackmagic.cpp:	ImageReader b4("/home/jonathan/Pictures/minecraft.png");
./src/examples/ExampleBlackmagic.cpp:	ImageReader b5("/home/jonathan/Pictures/colorpgg03.jpg");
./src/examples/ExampleBlackmagic.cpp:	Clip c3(new ImageReader("/home/jonathan/Pictures/watermark.png"));
./src/examples/ExampleBlackmagic.cpp:	Clip c4(new ImageReader("/home/jonathan/Pictures/mask_small.png"));
./src/examples/ExampleBlackmagic.cpp:					filename << "/home/jonathan/Pictures/screenshots/detailed/" << timestamp.str() << ".jpeg";
./src/examples/ExampleBlackmagic.cpp:					filename_small << "/home/jonathan/Pictures/screenshots/thumbs/" << timestamp.str() << ".jpeg";
./src/examples/ExampleBlackmagic.cpp://	ImageReader r1("/home/jonathan/Pictures/Screenshot from 2013-02-10 15:06:38.png");
./src/examples/ExampleBlackmagic.cpp://	ImageReader r2("/home/jonathan/Pictures/trees.jpg");
./src/examples/Example.cpp:    FFmpegReader r9("/home/jonathan/Videos/sintel_trailer-720p.mp4");
./src/examples/Example.cpp:    FFmpegWriter w9("/home/jonathan/metadata.mp4");
./doc/images/logo.svg:   inkscape:export-filename="/home/jonathan/apps/libopenshot/doc/images/logo.png"
```

(And pity the poor OpenShot/openshot-qt translators: The source file references in `src/language/OpenShot.pot` are _all_ absolute paths below `/home/jonathan/apps/openshot-qt-git/`.)

Second, the Eclipse project files were _explicitly_ and _intentionally_ checked in to the repo — they're not there by accident, it was a conscious decision. 

See e.g. a41afe8, which like many commits from that time contains a _shit-ton_ of completely unrelated changes across the entire source tree, but has the commit _message_ "Adding back in Eclipse project files." indicating that was the main thrust.

My guess is that's because the Eclipse files aren't merely IDE preferences, they contain build environment definitions required to compile the code from source within the IDE — something that's generally useful, basically akin to the cmake files (which, as you can see above, _also_ contain `/home/jonathan` paths). Only a few of the `.cproject` file's 405 lines, and none of the `.project` file's 94 lines, contain paths that would have to be adjusted. The remaining hundreds of lines of configuration aren't necessarily worthless just because a few paths would need updating.

Now, I said I'm of two minds on this, which I am despite the fact that everything I've said so far has argued **against** removing the files.

The reason I'm not dead-set against it isn't because the content is slightly non-portable, but because those files were last touched on 2015-02-07 (`.cproject`) or 2014-07-11 (`.project`), and I suspect their contents are no longer current enough to still be useful as-is. I'm not even sure they're supported as-is in current versions of Eclipse (version 9.5.3 didn't seem to care that they were there, in attempting to import  the source tree as any sort of existing project file), and if they are I'm not sure the contents are still valid.

Ultimately I'd still prefer that @jonoomph make the call, since he was the one to check in the files. And, ultimately, he _will_, since he'd have to commit any changes to the repo. So, I'll submit a PR to remove the files, referencing this issue — but given that there are much more critical PRs that have been sitting untouched for several months, I really have no idea when or if he'll ever look at this one. \*shrug*
